// Code generated by forge. DO NOT EDIT.

package model

import "log/slog"

// LogValue returns Credentials as it may be logged.
//
// Every exported field, with the one tagged redact replaced by a fixed string.
// Fixed rather than shortened or starred: a length is something, a prefix is
// more, and two records holding one secret are told apart by any hash of it.
//
// Implementing this is what keeps a field out of a log. slog reaches for a
// value's fields when the value does not say otherwise, so a type with a secret
// in it and no LogValue prints the secret. A handler can be given a hook that
// rewrites attributes, but that is a property of the handler rather than of the
// type, and every place the value is logged from has to have installed it.
func (v Credentials) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("User", v.User),
		slog.String("Token", "[redacted]"),
	)
}

// LogValue returns Reaches as it may be logged.
//
// Every exported field, with the one tagged redact replaced by a fixed string.
// Fixed rather than shortened or starred: a length is something, a prefix is
// more, and two records holding one secret are told apart by any hash of it.
//
// Implementing this is what keeps a field out of a log. slog reaches for a
// value's fields when the value does not say otherwise, so a type with a secret
// in it and no LogValue prints the secret. A handler can be given a hook that
// rewrites attributes, but that is a property of the handler rather than of the
// type, and every place the value is logged from has to have installed it.
func (v Reaches) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("Token", "[redacted]"),
		slog.Any("Held", v.Held),
	)
}

// LogValue returns Session as it may be logged.
//
// Implementing this is what keeps a field out of a log. slog reaches for a
// value's fields when the value does not say otherwise, so a type with a secret
// in it and no LogValue prints the secret. A handler can be given a hook that
// rewrites attributes, but that is a property of the handler rather than of the
// type, and every place the value is logged from has to have installed it.
func (v Session) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("Name", v.Name),
	)
}
