// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge (devel)
// go go1.27.1
// inputs dff9b2898e2b4227

//go:build !forgespec

package ledger

import (
	"cmp"
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"iter"
	"slices"
	"sort"
	"strconv"
	"time"
)

// CSVHeader returns the columns Entries writes, in the order it writes them.
//
// A fresh slice on every call, so that a caller sorting or rewriting what it
// was given cannot change what the next document is checked against.
func (c Entries) CSVHeader() []string {
	return []string{"id", "payee", "amount", "currency", "rate", "revision", "settled", "posted"}
}

// entriesCSVWritten counts the bytes a writer accepted.
//
// The CSV writer buffers, so what it has written and what the writer beneath it
// has taken are two numbers. This is the second, which is the one a caller
// copying the container out is entitled to.
type entriesCSVWritten struct {
	to io.Writer
	n  int64
}

// Write passes the bytes on and counts the ones that were taken.
func (w *entriesCSVWritten) Write(p []byte) (int, error) {
	n, err := w.to.Write(p)
	w.n += int64(n)
	return n, err
}

// WriteCSVTo writes the container to w as a CSV document, and reports how many
// bytes reached w.
//
// One pass over the elements and one record buffer for the whole document, so
// what it costs to write a container is what it costs to write its rows and
// nothing besides.
func (c Entries) WriteCSVTo(w io.Writer) (int64, error) {
	counted := entriesCSVWritten{to: w}

	out := csv.NewWriter(&counted)
	out.Comma = ','

	record := make([]string, 0, 8)
	var err error

	if err = out.Write(c.CSVHeader()); err != nil {
		return counted.n, err
	}
	for v := range c.All() {
		if record, err = encodeLedgerEntryCSVInto(record, v); err != nil {
			return counted.n, err
		}
		if err = out.Write(record); err != nil {
			return counted.n, err
		}
	}

	// Flushed here rather than by the caller, because the caller was handed a
	// count and a count of buffered bytes is not one.
	out.Flush()

	return counted.n, out.Error()
}

// entriesCSVRead counts the bytes a reader gave up.
//
// The CSV reader buffers, so it takes more from the reader beneath it than the
// records it has handed back account for. What is counted here is what was
// taken, which is what a caller reading into the container is entitled to know.
type entriesCSVRead struct {
	from io.Reader
	n    int64
}

// Read passes the bytes on and counts them.
func (r *entriesCSVRead) Read(p []byte) (int, error) {
	n, err := r.from.Read(p)
	r.n += int64(n)
	return n, err
}

// ReadCSVFrom reads a CSV document from r into the container, and reports how
// many bytes were taken from r.
//
// What the container held is dropped before the first row is read into it, so
// reading into one twice leaves the second document rather than both — which is
// what reading a document into a value means everywhere else. An empty reader
// empties it and reads nothing else.
//
// The rows are handed over one at a time as they are read, so the document is
// never held in memory beside the container being filled from it.
//
// What a failure leaves behind follows from that, and it is not one answer.
// Nothing is dropped until the first row arrives, so a document that fails
// before then leaves the container exactly as it was — whatever the reason, and
// there are several. One that fails once the rows have started leaves the rows
// before the failure in it, since each was handed over before the next was
// read. Read a non-nil error as leaving the container in no particular state
// rather than as leaving it alone.
//
// More bytes are usually taken from r than the document occupies, because the
// reader buffers: what is reported is what was read rather than what was used.
// So this cannot pull one document out of a stream holding several — give it a
// reader over the one document.
//
// A CRLF inside a quoted cell comes back as an LF, every time it appears. That
// is the reader's own newline handling and it cannot be turned off. A bare CR
// and a bare LF both survive; it is only the pair that collapses.
func (c *Entries) ReadCSVFrom(r io.Reader) (int64, error) {
	counted := entriesCSVRead{from: r}

	in := csv.NewReader(&counted)
	in.Comma = ','
	in.FieldsPerRecord = 8
	// The record is read into again on every call, which the row codec is
	// written for: it copies every cell out into the element before the next
	// call arrives.
	in.ReuseRecord = true

	// The header before anything else, and compared rather than skipped: a
	// document whose columns arrived in another order would otherwise fill
	// every element from the wrong fields and report nothing.
	header, err := in.Read()
	if errors.Is(err, io.EOF) {
		c.Reset()
		return counted.n, nil
	}
	if err != nil {
		return counted.n, err
	}
	if want := c.CSVHeader(); !slices.Equal(header, want) {
		return counted.n, fmt.Errorf(
			"cannot read Entries: the document is headed %q, not %q", header, want)
	}

	// What went wrong inside the walk, which a sequence has no way to answer
	// with. The container is handed elements one at a time and the failure is
	// carried out here.
	var failed error

	c.Reset()
	c.AppendSeq(func(yield func(Entry) bool) {
		for {
			record, err := in.Read()
			if errors.Is(err, io.EOF) {
				return
			}
			if err != nil {
				failed = err
				return
			}

			held, err := decodeLedgerEntryCSVFrom(record)
			if err != nil {
				failed = err
				return
			}
			if !yield(held) {
				return
			}
		}
	})

	return counted.n, failed
}

// EntriesSeq is a lazy view over the elements of Entries.
type EntriesSeq struct {
	Seq[Entry]
}

// Seq returns a lazy view over the elements. Its combinators are the shared
// Seq[Entry] view's.
func (c Entries) Seq() EntriesSeq {
	return EntriesSeq{Seq[Entry](c.All())}
}

// IDs returns the ID of every element, in order.
func (c Entries) IDs() []int {
	return c.project(func(v Entry) int {
		return v.ID
	})
}

// Payees returns the Payee of every element, in order.
func (c Entries) Payees() []string {
	return c.project(func(v Entry) string {
		return v.Payee
	})
}

// Amounts returns the Amount of every element, in order.
func (c Entries) Amounts() []Cents {
	return c.project(func(v Entry) Cents {
		return v.Amount
	})
}

// Currencies returns the Currency of every element, in order.
func (c Entries) Currencies() []Currency {
	return c.project(func(v Entry) Currency {
		return v.Currency
	})
}

// Rates returns the Rate of every element, in order.
func (c Entries) Rates() []float64 {
	return c.project(func(v Entry) float64 {
		return v.Rate
	})
}

// Revisions returns the Revision of every element, in order.
func (c Entries) Revisions() []uint8 {
	return c.project(func(v Entry) uint8 {
		return v.Revision
	})
}

// Settleds returns the Settled of every element, in order.
func (c Entries) Settleds() []bool {
	return c.project(func(v Entry) bool {
		return v.Settled
	})
}

// Posteds returns the Posted of every element, in order.
func (c Entries) Posteds() []time.Time {
	return c.project(func(v Entry) time.Time {
		return v.Posted
	})
}

// Notes returns the Note of every element, in order.
func (c Entries) Notes() []string {
	return c.project(func(v Entry) string {
		return v.Note
	})
}

// SortedByPayee returns the elements ordered by Payee, leaving equal ones as
// they were.
func (c Entries) SortedByPayee() []Entry {
	return c.ordered(func(v Entry) string {
		return v.Payee
	})
}

// ByID returns the elements keyed by ID, keeping the last of any that share
// one.
func (c Entries) ByID() map[int]Entry {
	return c.keyed(func(v Entry) int {
		return v.ID
	})
}

// Less reports whether the element at i sorts before the one at j, by Payee. It
// is one of the three sort.Sort takes: the storage answers the length, and Swap
// below is the other. The order is Payee's because it is the one sort key this
// declaration names — one naming several has several orders and no reason to
// prefer any of them, and gets its sorted views without these. Unlike
// SortedByPayee, sorting through this rearranges the collection rather than
// answering with a copy of it in order.
func (c Entries) Less(i, j int) bool {
	return c[i].Payee < c[j].Payee
}

// Swap exchanges the elements at i and j, which is the last of the three
// sort.Sort takes.
func (c Entries) Swap(i, j int) {
	c[i], c[j] = c[j], c[i]
}

// project collects one value from every element, in the order the elements come
// in.
//
// The result is grown rather than sized ahead, because what is walked is not
// always something that can be counted first — a walk is all this needs of the
// collection, and needing a length as well would be needing more.
func (c Entries) project[V any](of func(Entry) V) []V {
	var out []V
	for v := range c.All() {
		out = append(out, of(v))
	}
	return out
}

// keyed returns the elements by the key taken from each of them.
//
// Later wins where two elements share a key, which is what writing into a map
// does and is the only answer that does not need a policy. A key that has to be
// unique is a thing to check, not a thing to discover from which element came
// last.
//
// A key type that holds an interface is a key that can be built and cannot
// always be used: the map panics on a dynamic value that is not comparable,
// exactly as any other map keyed the same way does.
func (c Entries) keyed[K comparable](by func(Entry) K) map[K]Entry {
	out := make(map[K]Entry)
	for v := range c.All() {
		out[by(v)] = v
	}
	return out
}

// ordered returns the elements sorted by the key taken from each of them,
// leaving equal ones in the order they came in.
//
// A new slice rather than a sort in place: the collection is what it was, and a
// method that quietly reordered it would make asking a question change the
// answer to the next one.
func (c Entries) ordered[K cmp.Ordered](by func(Entry) K) []Entry {
	out := slices.Collect(c.All())
	slices.SortStableFunc(out, func(a, b Entry) int { return cmp.Compare(by(a), by(b)) })

	return out
}

// Entries holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type Entries []Entry

// NewEntries returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewEntries(elems ...Entry) Entries { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Entries) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Entries) All() iter.Seq[Entry] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Entries) Backward() iter.Seq[Entry] {
	return func(yield func(Entry) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Entries) AppendSeq(seq iter.Seq[Entry]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *Entries) Reset() { *s = (*s)[:0] }

// Entries satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ sort.Interface = *new(Entries)
)

// And the walk's own signature, checked without calling it.
//
// A method expression is resolved when the package is built and costs nothing
// at run time, where an interface assertion would have to name a value and
// initialise it.
var _ func(*Entries) iter.Seq[Entry] = (*Entries).All

// CSVHeader returns the columns Recent writes, in the order it writes them.
//
// A fresh slice on every call, so that a caller sorting or rewriting what it
// was given cannot change what the next document is checked against.
func (c *Recent) CSVHeader() []string {
	return []string{"id", "payee", "amount", "currency", "rate", "revision", "settled", "posted"}
}

// recentCSVWritten counts the bytes a writer accepted.
//
// The CSV writer buffers, so what it has written and what the writer beneath it
// has taken are two numbers. This is the second, which is the one a caller
// copying the container out is entitled to.
type recentCSVWritten struct {
	to io.Writer
	n  int64
}

// Write passes the bytes on and counts the ones that were taken.
func (w *recentCSVWritten) Write(p []byte) (int, error) {
	n, err := w.to.Write(p)
	w.n += int64(n)
	return n, err
}

// WriteCSVTo writes the container to w as a CSV document, and reports how many
// bytes reached w.
//
// One pass over the elements and one record buffer for the whole document, so
// what it costs to write a container is what it costs to write its rows and
// nothing besides.
func (c *Recent) WriteCSVTo(w io.Writer) (int64, error) {
	counted := recentCSVWritten{to: w}

	out := csv.NewWriter(&counted)
	out.Comma = '|'

	record := make([]string, 0, 8)
	var err error

	if err = out.Write(c.CSVHeader()); err != nil {
		return counted.n, err
	}
	for v := range c.All() {
		if record, err = encodeLedgerEntryCSVInto(record, v); err != nil {
			return counted.n, err
		}
		if err = out.Write(record); err != nil {
			return counted.n, err
		}
	}

	// Flushed here rather than by the caller, because the caller was handed a
	// count and a count of buffered bytes is not one.
	out.Flush()

	return counted.n, out.Error()
}

// recentCSVRead counts the bytes a reader gave up.
//
// The CSV reader buffers, so it takes more from the reader beneath it than the
// records it has handed back account for. What is counted here is what was
// taken, which is what a caller reading into the container is entitled to know.
type recentCSVRead struct {
	from io.Reader
	n    int64
}

// Read passes the bytes on and counts them.
func (r *recentCSVRead) Read(p []byte) (int, error) {
	n, err := r.from.Read(p)
	r.n += int64(n)
	return n, err
}

// ReadCSVFrom reads a CSV document from r into the container, and reports how
// many bytes were taken from r.
//
// What the container held is dropped before the first row is read into it, so
// reading into one twice leaves the second document rather than both — which is
// what reading a document into a value means everywhere else. An empty reader
// empties it and reads nothing else.
//
// The rows are handed over one at a time as they are read, so the document is
// never held in memory beside the container being filled from it.
//
// What a failure leaves behind follows from that, and it is not one answer.
// Nothing is dropped until the first row arrives, so a document that fails
// before then leaves the container exactly as it was — whatever the reason, and
// there are several. One that fails once the rows have started leaves the rows
// before the failure in it, since each was handed over before the next was
// read. Read a non-nil error as leaving the container in no particular state
// rather than as leaving it alone.
//
// More bytes are usually taken from r than the document occupies, because the
// reader buffers: what is reported is what was read rather than what was used.
// So this cannot pull one document out of a stream holding several — give it a
// reader over the one document.
//
// A CRLF inside a quoted cell comes back as an LF, every time it appears. That
// is the reader's own newline handling and it cannot be turned off. A bare CR
// and a bare LF both survive; it is only the pair that collapses.
func (c *Recent) ReadCSVFrom(r io.Reader) (int64, error) {
	if c.Cap() == 0 {
		return 0, errors.New("Recent holds nothing until it is constructed, so nothing can be read into it")
	}

	counted := recentCSVRead{from: r}

	in := csv.NewReader(&counted)
	in.Comma = '|'
	in.FieldsPerRecord = 8
	// The record is read into again on every call, which the row codec is
	// written for: it copies every cell out into the element before the next
	// call arrives.
	in.ReuseRecord = true

	// The header before anything else, and compared rather than skipped: a
	// document whose columns arrived in another order would otherwise fill
	// every element from the wrong fields and report nothing.
	header, err := in.Read()
	if errors.Is(err, io.EOF) {
		c.Reset()
		return counted.n, nil
	}
	if err != nil {
		return counted.n, err
	}
	if want := c.CSVHeader(); !slices.Equal(header, want) {
		return counted.n, fmt.Errorf(
			"cannot read Recent: the document is headed %q, not %q", header, want)
	}

	// What went wrong inside the walk, which a sequence has no way to answer
	// with. The container is handed elements one at a time and the failure is
	// carried out here.
	var failed error

	c.Reset()
	c.AppendSeq(func(yield func(Entry) bool) {
		for {
			record, err := in.Read()
			if errors.Is(err, io.EOF) {
				return
			}
			if err != nil {
				failed = err
				return
			}

			held, err := decodeLedgerEntryCSVFrom(record)
			if err != nil {
				failed = err
				return
			}
			if !yield(held) {
				return
			}
		}
	})

	return counted.n, failed
}

// recentFixedCap is how many elements the buffer holds.
//
// It is a constant rather than a field, so the size is part of the type rather
// than of a value: every container of this type holds the same number, the
// compiler knows it, and no caller can be handed one sized differently from the
// one it expected.
const recentFixedCap = 4

// Recent holds a fixed number of the most recent elements.
//
// The buffer is allocated once and never grows, so a producer that outruns its
// consumer costs a bounded amount of memory rather than an increasing one. That
// is the whole of what this type is for, and it is why every method that adds
// an element has an answer for a buffer that is already full.
//
// The elements live in a slice that is treated as a circle: head is where the
// oldest one is, and n is how many there are. Reading walks from head, wrapping
// at the end, so the order elements come back in is the order they went in
// — the oldest first — regardless of where in the slice they happen to sit.
//
// The zero value has no buffer at all, which is not the same as an empty
// container and is not something any method can make sense of. Adding to one
// says so rather than carrying on. Use the constructor.
type Recent struct {
	buf  []Entry
	head int
	n    int
}

// NewRecent returns an empty container, whose capacity is the one the
// declaration fixed.
func NewRecent() *Recent {
	return &Recent{buf: make([]Entry, recentFixedCap)}
}

// Cap reports how many elements the container can hold, which does not change.
func (r *Recent) Cap() int { return len(r.buf) }

// Len reports how many elements the container holds, which is never more than
// its capacity.
func (r *Recent) Len() int { return r.n }

// Push adds an element, dropping the oldest one if the buffer is full.
//
// Dropping rather than growing is the point of the type: the newest elements
// are the ones kept, and how much memory that costs was decided when the
// container was made.
func (r *Recent) Push(v Entry) {
	r.built()

	if r.n == len(r.buf) {
		r.buf[r.head] = v
		r.head = recentIndexOf(r.head, 1, len(r.buf))
		return
	}

	r.buf[recentIndexOf(r.head, r.n, len(r.buf))] = v
	r.n++
}

// All walks the container from the oldest element to the newest.
//
// Which slots the walk covers is fixed when All is called, so pushing during
// one neither lengthens it nor makes it come back round to a slot it has been
// to. What is in a slot is read when the walk reaches it: pushing to a full
// container overwrites the oldest slot, and a walk that has not yet reached
// that slot yields what was written there rather than what it displaced.
//
// Fixing that too would mean copying the elements, which is the one thing a
// container that exists to bound its memory should not do behind a caller's
// back. Walk it, or push to it, or take a copy and do both.
func (r *Recent) All() iter.Seq[Entry] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Entry) bool) {
		for i := range held {
			if !yield(r.buf[recentIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// Backward walks the container from the newest element to the oldest. Like All,
// which slots it covers is fixed when it is called.
func (r *Recent) Backward() iter.Seq[Entry] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Entry) bool) {
		for i := held - 1; i >= 0; i-- {
			if !yield(r.buf[recentIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them, dropping older ones as it fills.
//
// A sequence longer than the container leaves the last capacity elements of it,
// which is what pushing them one at a time would leave.
func (r *Recent) AppendSeq(seq iter.Seq[Entry]) {
	for v := range seq {
		r.Push(v)
	}
}

// Reset empties the container, keeping the buffer it was constructed with.
//
// The capacity is what the container is rather than what it holds, so emptying
// does not give it up: a container that has been reset takes as many elements
// as it did when it was new, and takes them without allocating again.
//
// The elements that were there stay in the buffer until they are pushed over,
// so a container holding the last reference to something large holds it until
// then. Nothing can read them: what a walk covers is the count, and the count
// is what this sets to none.
func (r *Recent) Reset() { r.head, r.n = 0, 0 }

// built stops a container that was never constructed from being added to.
//
// A zero value has no buffer, so it can hold nothing and never will. Under the
// policy that overwrites, adding to one indexes an empty slice and panics on
// its own; under the policy that refuses, it would report the container full —
// which is true and useless, since a caller checking for a full container reads
// that as back-pressure and retries for ever. Saying the same thing both ways
// makes the mistake one answer rather than two.
func (r *Recent) built() {
	if len(r.buf) == 0 {
		panic("forge: this container was never constructed; use the constructor")
	}
}

// recentIndexOf returns where the element i places after the one at from is kept.
//
// Given the buffer's own head and size it answers for the container as it is;
// given a head a walk took when it started, it answers for the container as it
// was, which is what keeps a walk on the positions it set out to visit.
//
// One subtraction rather than a remainder: i is never more than the number of
// elements held, which is never more than the size, so the sum passes the end
// of the buffer at most once.
func recentIndexOf(from, i, size int) int {
	if slot := from + i; slot < size {
		return slot
	}
	return from + i - size
}

// The walk's own signature, checked when the package is built.
//
// A method expression is resolved by the compiler and costs nothing at run
// time, where an interface assertion would have to name a value and initialise
// it. What it holds the walk to is the element type of the declaration, so a
// container that walks something else fails here rather than wherever somebody
// ranges over it.
var _ func(*Recent) iter.Seq[Entry] = (*Recent).All

// CSVHeader returns the columns Bare writes, in the order it writes them.
//
// A fresh slice on every call, so that a caller sorting or rewriting what it
// was given cannot change what the next document is checked against.
func (c Bare) CSVHeader() []string {
	return []string{"id", "payee", "amount", "currency", "rate", "revision", "settled", "posted"}
}

// bareCSVWritten counts the bytes a writer accepted.
//
// The CSV writer buffers, so what it has written and what the writer beneath it
// has taken are two numbers. This is the second, which is the one a caller
// copying the container out is entitled to.
type bareCSVWritten struct {
	to io.Writer
	n  int64
}

// Write passes the bytes on and counts the ones that were taken.
func (w *bareCSVWritten) Write(p []byte) (int, error) {
	n, err := w.to.Write(p)
	w.n += int64(n)
	return n, err
}

// WriteCSVTo writes the container to w as a CSV document, and reports how many
// bytes reached w.
//
// One pass over the elements and one record buffer for the whole document, so
// what it costs to write a container is what it costs to write its rows and
// nothing besides.
func (c Bare) WriteCSVTo(w io.Writer) (int64, error) {
	counted := bareCSVWritten{to: w}

	out := csv.NewWriter(&counted)
	out.Comma = ','

	record := make([]string, 0, 8)
	var err error

	for v := range c.All() {
		if record, err = encodeLedgerEntryCSVInto(record, v); err != nil {
			return counted.n, err
		}
		if err = out.Write(record); err != nil {
			return counted.n, err
		}
	}

	// Flushed here rather than by the caller, because the caller was handed a
	// count and a count of buffered bytes is not one.
	out.Flush()

	return counted.n, out.Error()
}

// bareCSVRead counts the bytes a reader gave up.
//
// The CSV reader buffers, so it takes more from the reader beneath it than the
// records it has handed back account for. What is counted here is what was
// taken, which is what a caller reading into the container is entitled to know.
type bareCSVRead struct {
	from io.Reader
	n    int64
}

// Read passes the bytes on and counts them.
func (r *bareCSVRead) Read(p []byte) (int, error) {
	n, err := r.from.Read(p)
	r.n += int64(n)
	return n, err
}

// ReadCSVFrom reads a CSV document from r into the container, and reports how
// many bytes were taken from r.
//
// What the container held is dropped before the first row is read into it, so
// reading into one twice leaves the second document rather than both — which is
// what reading a document into a value means everywhere else. An empty reader
// empties it and reads nothing else.
//
// The rows are handed over one at a time as they are read, so the document is
// never held in memory beside the container being filled from it.
//
// What a failure leaves behind follows from that, and it is not one answer.
// Nothing is dropped until the first row arrives, so a document that fails
// before then leaves the container exactly as it was — whatever the reason, and
// there are several. One that fails once the rows have started leaves the rows
// before the failure in it, since each was handed over before the next was
// read. Read a non-nil error as leaving the container in no particular state
// rather than as leaving it alone.
//
// More bytes are usually taken from r than the document occupies, because the
// reader buffers: what is reported is what was read rather than what was used.
// So this cannot pull one document out of a stream holding several — give it a
// reader over the one document.
//
// A CRLF inside a quoted cell comes back as an LF, every time it appears. That
// is the reader's own newline handling and it cannot be turned off. A bare CR
// and a bare LF both survive; it is only the pair that collapses.
func (c *Bare) ReadCSVFrom(r io.Reader) (int64, error) {
	counted := bareCSVRead{from: r}

	in := csv.NewReader(&counted)
	in.Comma = ','
	in.FieldsPerRecord = 8
	// The record is read into again on every call, which the row codec is
	// written for: it copies every cell out into the element before the next
	// call arrives.
	in.ReuseRecord = true

	// Nothing is read before the rows: this document carries no header, so the
	// first record is an element.

	// What went wrong inside the walk, which a sequence has no way to answer
	// with. The container is handed elements one at a time and the failure is
	// carried out here.
	var failed error

	c.Reset()
	c.AppendSeq(func(yield func(Entry) bool) {
		for {
			record, err := in.Read()
			if errors.Is(err, io.EOF) {
				return
			}
			if err != nil {
				failed = err
				return
			}

			held, err := decodeLedgerEntryCSVFrom(record)
			if err != nil {
				failed = err
				return
			}
			if !yield(held) {
				return
			}
		}
	})

	return counted.n, failed
}

// Bare holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type Bare []Entry

// NewBare returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewBare(elems ...Entry) Bare { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Bare) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Bare) All() iter.Seq[Entry] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Bare) Backward() iter.Seq[Entry] {
	return func(yield func(Entry) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Bare) AppendSeq(seq iter.Seq[Entry]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *Bare) Reset() { *s = (*s)[:0] }

// The walk's own signature, checked when the package is built.
//
// A method expression is resolved by the compiler and costs nothing at run
// time, where an interface assertion would have to name a value and initialise
// it. What it holds the walk to is the element type of the declaration, so a
// container that walks something else fails here rather than wherever somebody
// ranges over it.
var _ func(*Bare) iter.Seq[Entry] = (*Bare).All

// encodeLedgerEntryCSVInto writes one Entry into the record it is given, and
// returns the record it wrote.
//
// The record is handed in and handed back rather than allocated here, so that
// one buffer serves a whole document: a writer walking a million elements pays
// for the row once.
func encodeLedgerEntryCSVInto(record []string, v Entry) ([]string, error) {
	record = record[:0]

	record = append(record, strconv.FormatInt(int64(v.ID), 10))
	record = append(record, v.Payee)
	record = append(record, strconv.FormatInt(int64(v.Amount), 10))
	record = append(record, string(v.Currency))
	record = append(record, strconv.FormatFloat(v.Rate, 'g', -1, 64))
	record = append(record, strconv.FormatUint(uint64(v.Revision), 10))
	record = append(record, strconv.FormatBool(v.Settled))

	postedCell, err := v.Posted.MarshalText()
	if err != nil {
		return record, fmt.Errorf("writing the posted column of an Entry: %w", err)
	}
	record = append(record, string(postedCell))

	return record, nil
}

// decodeLedgerEntryCSVFrom reads one record into an Entry.
//
// Every cell is copied out, so the element does not hold on to the record: a
// reader is free to hand the same one back on the next call, and one does.
func decodeLedgerEntryCSVFrom(record []string) (Entry, error) {
	var v Entry

	// Checked rather than assumed, so that a caller who assembled the record
	// itself is answered rather than panicked at.
	if len(record) != 8 {
		return v, fmt.Errorf("an Entry has 8 columns and this record has %d", len(record))
	}

	idCell, err := strconv.ParseInt(record[0], 10, 0)
	if err != nil {
		return v, fmt.Errorf("reading the id column of an Entry: %w", err)
	}
	v.ID = int(idCell)

	v.Payee = record[1]

	amountCell, err := strconv.ParseInt(record[2], 10, 64)
	if err != nil {
		return v, fmt.Errorf("reading the amount column of an Entry: %w", err)
	}
	v.Amount = Cents(amountCell)

	v.Currency = Currency(record[3])

	rateCell, err := strconv.ParseFloat(record[4], 64)
	if err != nil {
		return v, fmt.Errorf("reading the rate column of an Entry: %w", err)
	}
	v.Rate = rateCell

	revisionCell, err := strconv.ParseUint(record[5], 10, 8)
	if err != nil {
		return v, fmt.Errorf("reading the revision column of an Entry: %w", err)
	}
	v.Revision = uint8(revisionCell)

	settledCell, err := strconv.ParseBool(record[6])
	if err != nil {
		return v, fmt.Errorf("reading the settled column of an Entry: %w", err)
	}
	v.Settled = settledCell

	if err := v.Posted.UnmarshalText([]byte(record[7])); err != nil {
		return v, fmt.Errorf("reading the posted column of an Entry: %w", err)
	}

	return v, nil
}

// Seq is a lazy view over a sequence of elements.
//
// Every operation on it is lazy: it returns another view and walks nothing. The
// walk happens once, when a terminal asks for it, and each element passes
// through the whole chain before the next one is read — so a chain over a
// million elements holds one of them at a time and allocates nothing per
// element. A chain costs a few allocations per link to build and to start, and
// that is the whole of what it costs: the same over a million elements as over
// ten.
//
// The zero view yields nothing through every method here, so one that was never
// given a sequence behaves like an empty one. Ranging over it directly is
// ranging over a function that is not there, which panics like any other nil
// call — All is what guards that, and is what to range over.
type Seq[U any] iter.Seq[U]

// All returns the view as an ordinary sequence, which is what everything taking
// an iter.Seq wants and what a range loop should read.
//
// It is also where the zero view is made safe. A view is a function underneath,
// so one that was never given a sequence is a nil function and ranging over it
// panics; this hands back an empty sequence instead, and every method below
// walks through here rather than over the view directly.
func (s Seq[U]) All() iter.Seq[U] {
	if s == nil {
		return func(func(U) bool) {}
	}
	return iter.Seq[U](s)
}

// Filter returns a view of the elements the predicate keeps.
func (s Seq[U]) Filter(keep func(U) bool) Seq[U] {
	return func(yield func(U) bool) {
		for v := range s.All() {
			if keep(v) && !yield(v) {
				return
			}
		}
	}
}

// Map returns a view of what the function makes of each element.
//
// Genuinely generic in its result, so a chain that changes type keeps chaining:
// the view a projection returns is a view like any other, and the combinators
// on it are these same ones rather than a second set written for the new type.
func (s Seq[U]) Map[V any](to func(U) V) Seq[V] {
	return func(yield func(V) bool) {
		for v := range s.All() {
			if !yield(to(v)) {
				return
			}
		}
	}
}

// Take returns a view of at most the first n elements, and of none for an n
// that is not positive.
//
// It stops the walk beneath it rather than reading on and discarding, which is
// what makes taking ten from a very long sequence cost ten.
func (s Seq[U]) Take(n int) Seq[U] {
	return func(yield func(U) bool) {
		if n <= 0 {
			return
		}

		left := n
		for v := range s.All() {
			if !yield(v) {
				return
			}

			left--
			if left == 0 {
				return
			}
		}
	}
}

// Skip returns a view of everything after the first n elements, and of
// everything for an n that is not positive.
func (s Seq[U]) Skip(n int) Seq[U] {
	return func(yield func(U) bool) {
		left := n
		for v := range s.All() {
			if left > 0 {
				left--
				continue
			}
			if !yield(v) {
				return
			}
		}
	}
}

// Dedup returns a view with runs of equal elements collapsed to their first.
//
// Adjacent elements only, which is the whole of what a lazy operation can do:
// dropping every repeat wherever it appears means remembering everything seen
// so far, and a view that grew a set as it walked would not be a view any more.
// Sort or group first if that is what is wanted.
//
// Each element is compared against the last one that was *yielded* rather than
// against the one immediately before it, so a run collapses to its first
// element however long it is. The two are the same thing for an equality, and
// differ for a comparison that is not one — a nearness test over 1, 2, 3 keeps
// 1 and 3 here, where comparing neighbours would keep only 1. The first
// argument is the element that was kept and the second the one being offered.
func (s Seq[U]) Dedup(same func(a, b U) bool) Seq[U] {
	return func(yield func(U) bool) {
		var last U
		seen := false

		for v := range s.All() {
			if seen && same(last, v) {
				continue
			}

			last, seen = v, true
			if !yield(v) {
				return
			}
		}
	}
}

// Chunk yields slices of n elements, the last of them shorter if the sequence
// does not divide evenly. It panics for an n below one, which asks for
// something there is no answer to.
//
// Each chunk is a slice of its own rather than one buffer handed out again and
// again. Reusing it would allocate less and would make a chunk kept past the
// next one silently become that one — a bug that shows up as data from the
// wrong batch, far from here. The cost is one allocation per chunk, which is
// still none per element.
//
// A plain sequence rather than another view, and that one is the language's.
// A method of this type returning a view of slices means the type mentioning
// itself over a bigger type than it was given, and the method set of that one
// mentioning a bigger one again, without end; the compiler calls it an
// instantiation cycle and refuses the file. A function beside the type could
// return one — the cycle is a property of method sets — at the price of a name
// in this package that everything else here keeps inside the view. Chunks are
// usually ranged over, which this is, and converting what it yields to a view
// of slices is the whole of the difference when they are not.
func (s Seq[U]) Chunk(n int) iter.Seq[[]U] {
	if n < 1 {
		panic("forge: Chunk of fewer than one element")
	}

	return func(yield func([]U) bool) {
		// Built on the first element that goes into it rather than ahead of
		// one, so a sequence that ends on a boundary does not pay for a batch
		// nothing is put in.
		var batch []U

		for v := range s.All() {
			if batch == nil {
				batch = make([]U, 0, n)
			}
			if batch = append(batch, v); len(batch) < n {
				continue
			}
			if !yield(batch) {
				return
			}
			batch = nil
		}

		if len(batch) > 0 {
			yield(batch)
		}
	}
}

// Collect walks the view and returns everything it yields.
func (s Seq[U]) Collect() []U { return slices.Collect(s.All()) }

// Into appends everything the view yields to a slice and returns it.
//
// It is Collect for a caller who owns the memory: passing a slice kept between
// calls turns the one allocation Collect makes into none.
func (s Seq[U]) Into(dst []U) []U { return slices.AppendSeq(dst, s.All()) }

// First returns the first element the view yields, and whether it yielded one.
// The walk stops there, so first-of-a-filter over a long sequence costs the
// elements up to the match and no more.
func (s Seq[U]) First() (U, bool) {
	for v := range s.All() {
		return v, true
	}

	var none U
	return none, false
}

// Reduce combines the elements into a single value, left to right.
//
// Generic in what it builds rather than in the element alone, so a sequence of
// values reduces to a count, a total or a map without being projected first.
func (s Seq[U]) Reduce[A any](initial A, combine func(A, U) A) A {
	out := initial
	for v := range s.All() {
		out = combine(out, v)
	}
	return out
}
