// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge/x/csv (devel)
// go go1.27.1
// inputs f5bc24d12f43b4d7

//go:build forgespec

package ledger

import (
	"cmp"
	"io"
	"iter"
	"sort"
	"time"
)

func (c Entries) CSVHeader() []string { panic("forge stub") }

type entriesCSVWritten struct {
	to io.Writer
	n  int64
}

func (w *entriesCSVWritten) Write(p []byte) (int, error) { panic("forge stub") }

func (c Entries) WriteCSVTo(w io.Writer) (int64, error) { panic("forge stub") }

type entriesCSVRead struct {
	from io.Reader
	n    int64
}

func (r *entriesCSVRead) Read(p []byte) (int, error) { panic("forge stub") }

func (c *Entries) ReadCSVFrom(r io.Reader) (int64, error) { panic("forge stub") }

type EntriesSeq struct {
	Seq[Entry]
}

func (c Entries) Seq() EntriesSeq {
	panic("forge stub")
}
func (c Entries) IDs() []int {
	panic("forge stub")
}
func (c Entries) Payees() []string {
	panic("forge stub")
}
func (c Entries) Amounts() []Cents {
	panic("forge stub")
}
func (c Entries) Currencies() []Currency {
	panic("forge stub")
}
func (c Entries) Rates() []float64 {
	panic("forge stub")
}
func (c Entries) Revisions() []uint8 {
	panic("forge stub")
}
func (c Entries) Settleds() []bool {
	panic("forge stub")
}
func (c Entries) Posteds() []time.Time {
	panic("forge stub")
}
func (c Entries) Notes() []string {
	panic("forge stub")
}
func (c Entries) SortedByPayee() []Entry {
	panic("forge stub")
}
func (c Entries) ByID() map[int]Entry {
	panic("forge stub")
}
func (c Entries) Less(i, j int) bool {
	panic("forge stub")
}
func (c Entries) Swap(i, j int) {
	panic("forge stub")
}

func (c Entries) project[V any](of func(Entry) V) []V { panic("forge stub") }

func (c Entries) keyed[K comparable](by func(Entry) K) map[K]Entry { panic("forge stub") }

func (c Entries) ordered[K cmp.Ordered](by func(Entry) K) []Entry { panic("forge stub") }

func NewEntries(elems ...Entry) Entries { panic("forge stub") }

func (s Entries) Len() int { panic("forge stub") }

func (s Entries) All() iter.Seq[Entry] { panic("forge stub") }

func (s Entries) Backward() iter.Seq[Entry] { panic("forge stub") }

func (s *Entries) AppendSeq(seq iter.Seq[Entry]) { panic("forge stub") }

func (s *Entries) Reset() { panic("forge stub") }

var (
	_ sort.Interface = *new(Entries)
)

var _ func(*Entries) iter.Seq[Entry] = (*Entries).All

func (c *Recent) CSVHeader() []string { panic("forge stub") }

type recentCSVWritten struct {
	to io.Writer
	n  int64
}

func (w *recentCSVWritten) Write(p []byte) (int, error) { panic("forge stub") }

func (c *Recent) WriteCSVTo(w io.Writer) (int64, error) { panic("forge stub") }

type recentCSVRead struct {
	from io.Reader
	n    int64
}

func (r *recentCSVRead) Read(p []byte) (int, error) { panic("forge stub") }

func (c *Recent) ReadCSVFrom(r io.Reader) (int64, error) { panic("forge stub") }

const recentFixedCap = 4

func NewRecent() *Recent { panic("forge stub") }

func (r *Recent) Cap() int { panic("forge stub") }

func (r *Recent) Len() int { panic("forge stub") }

func (r *Recent) Push(v Entry) { panic("forge stub") }

func (r *Recent) All() iter.Seq[Entry] { panic("forge stub") }

func (r *Recent) Backward() iter.Seq[Entry] { panic("forge stub") }

func (r *Recent) AppendSeq(seq iter.Seq[Entry]) { panic("forge stub") }

func (r *Recent) Reset() { panic("forge stub") }

func (r *Recent) built() { panic("forge stub") }

func recentIndexOf(from, i, size int) int { panic("forge stub") }

var _ func(*Recent) iter.Seq[Entry] = (*Recent).All

func (c Bare) CSVHeader() []string { panic("forge stub") }

type bareCSVWritten struct {
	to io.Writer
	n  int64
}

func (w *bareCSVWritten) Write(p []byte) (int, error) { panic("forge stub") }

func (c Bare) WriteCSVTo(w io.Writer) (int64, error) { panic("forge stub") }

type bareCSVRead struct {
	from io.Reader
	n    int64
}

func (r *bareCSVRead) Read(p []byte) (int, error) { panic("forge stub") }

func (c *Bare) ReadCSVFrom(r io.Reader) (int64, error) { panic("forge stub") }

func NewBare(elems ...Entry) Bare { panic("forge stub") }

func (s Bare) Len() int { panic("forge stub") }

func (s Bare) All() iter.Seq[Entry] { panic("forge stub") }

func (s Bare) Backward() iter.Seq[Entry] { panic("forge stub") }

func (s *Bare) AppendSeq(seq iter.Seq[Entry]) { panic("forge stub") }

func (s *Bare) Reset() { panic("forge stub") }

var _ func(*Bare) iter.Seq[Entry] = (*Bare).All
