// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge (devel)
// go go1.27.1
// inputs ae9c6f23661b1f28

//go:build !forgespec

package ledger

import (
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"iter"
	"slices"
)

// CSVHeader returns the columns Recent writes, in the order it writes them.
//
// A fresh slice on every call, so that a caller sorting or rewriting what it
// was given cannot change what the next document is checked against.
func (c *Recent) CSVHeader() []string {
	return []string{"id", "payee", "amount", "currency", "rate", "revision", "settled", "posted"}
}

// recentCSVWritten counts the bytes a writer accepted.
//
// The CSV writer buffers, so what it has written and what the writer beneath it
// has taken are two numbers. This is the second, which is the one a caller
// copying the container out is entitled to.
type recentCSVWritten struct {
	to io.Writer
	n  int64
}

// Write passes the bytes on and counts the ones that were taken.
func (w *recentCSVWritten) Write(p []byte) (int, error) {
	n, err := w.to.Write(p)
	w.n += int64(n)
	return n, err
}

// WriteCSVTo writes the container to w as a CSV document, and reports how many
// bytes reached w.
//
// One pass over the elements and one record buffer for the whole document, so
// what it costs to write a container is what it costs to write its rows and
// nothing besides.
func (c *Recent) WriteCSVTo(w io.Writer) (int64, error) {
	counted := recentCSVWritten{to: w}

	out := csv.NewWriter(&counted)
	out.Comma = '|'

	record := make([]string, 0, 8)
	var err error

	if err = out.Write(c.CSVHeader()); err != nil {
		return counted.n, err
	}
	for v := range c.All() {
		if record, err = encodeLedgerEntryCSVInto(record, v); err != nil {
			return counted.n, err
		}
		if err = out.Write(record); err != nil {
			return counted.n, err
		}
	}

	// Flushed here rather than by the caller, because the caller was handed a
	// count and a count of buffered bytes is not one.
	out.Flush()

	return counted.n, out.Error()
}

// recentCSVRead counts the bytes a reader gave up.
//
// The CSV reader buffers, so it takes more from the reader beneath it than the
// records it has handed back account for. What is counted here is what was
// taken, which is what a caller reading into the container is entitled to know.
type recentCSVRead struct {
	from io.Reader
	n    int64
}

// Read passes the bytes on and counts them.
func (r *recentCSVRead) Read(p []byte) (int, error) {
	n, err := r.from.Read(p)
	r.n += int64(n)
	return n, err
}

// ReadCSVFrom reads a CSV document from r into the container, and reports how
// many bytes were taken from r.
//
// What the container held is dropped before the first row is read into it, so
// reading into one twice leaves the second document rather than both — which is
// what reading a document into a value means everywhere else. An empty reader
// empties it and reads nothing else.
//
// The rows are handed over one at a time as they are read, so the document is
// never held in memory beside the container being filled from it.
//
// What a failure leaves behind follows from that, and it is not one answer.
// Nothing is dropped until the first row arrives, so a document that fails
// before then leaves the container exactly as it was — whatever the reason, and
// there are several. One that fails once the rows have started leaves the rows
// before the failure in it, since each was handed over before the next was
// read. Read a non-nil error as leaving the container in no particular state
// rather than as leaving it alone.
//
// More bytes are usually taken from r than the document occupies, because the
// reader buffers: what is reported is what was read rather than what was used.
// So this cannot pull one document out of a stream holding several — give it a
// reader over the one document.
//
// A CRLF inside a quoted cell comes back as an LF, every time it appears. That
// is the reader's own newline handling and it cannot be turned off. A bare CR
// and a bare LF both survive; it is only the pair that collapses.
func (c *Recent) ReadCSVFrom(r io.Reader) (int64, error) {
	if c.Cap() == 0 {
		return 0, errors.New("Recent holds nothing until it is constructed, so nothing can be read into it")
	}

	counted := recentCSVRead{from: r}

	in := csv.NewReader(&counted)
	in.Comma = '|'
	in.FieldsPerRecord = 8
	// The record is read into again on every call, which the row codec is
	// written for: it copies every cell out into the element before the next
	// call arrives.
	in.ReuseRecord = true

	// The header before anything else, and compared rather than skipped: a
	// document whose columns arrived in another order would otherwise fill
	// every element from the wrong fields and report nothing.
	header, err := in.Read()
	if errors.Is(err, io.EOF) {
		c.Reset()
		return counted.n, nil
	}
	if err != nil {
		return counted.n, err
	}
	if want := c.CSVHeader(); !slices.Equal(header, want) {
		return counted.n, fmt.Errorf(
			"cannot read Recent: the document is headed %q, not %q", header, want)
	}

	// What went wrong inside the walk, which a sequence has no way to answer
	// with. The container is handed elements one at a time and the failure is
	// carried out here.
	var failed error

	c.Reset()
	c.AppendSeq(func(yield func(Entry) bool) {
		for {
			record, err := in.Read()
			if errors.Is(err, io.EOF) {
				return
			}
			if err != nil {
				failed = err
				return
			}

			held, err := decodeLedgerEntryCSVFrom(record)
			if err != nil {
				failed = err
				return
			}
			if !yield(held) {
				return
			}
		}
	})

	return counted.n, failed
}

// recentFixedCap is how many elements the buffer holds.
//
// It is a constant rather than a field, so the size is part of the type rather
// than of a value: every container of this type holds the same number, the
// compiler knows it, and no caller can be handed one sized differently from the
// one it expected.
const recentFixedCap = 4

// Recent holds a fixed number of the most recent elements.
//
// The buffer is allocated once and never grows, so a producer that outruns its
// consumer costs a bounded amount of memory rather than an increasing one. That
// is the whole of what this type is for, and it is why every method that adds
// an element has an answer for a buffer that is already full.
//
// The elements live in a slice that is treated as a circle: head is where the
// oldest one is, and n is how many there are. Reading walks from head, wrapping
// at the end, so the order elements come back in is the order they went in
// — the oldest first — regardless of where in the slice they happen to sit.
//
// The zero value has no buffer at all, which is not the same as an empty
// container and is not something any method can make sense of. Adding to one
// says so rather than carrying on. Use the constructor.
type Recent struct {
	buf  []Entry
	head int
	n    int
}

// NewRecent returns an empty container, whose capacity is the one the
// declaration fixed.
func NewRecent() *Recent {
	return &Recent{buf: make([]Entry, recentFixedCap)}
}

// Cap reports how many elements the container can hold, which does not change.
func (r *Recent) Cap() int { return len(r.buf) }

// Len reports how many elements the container holds, which is never more than
// its capacity.
func (r *Recent) Len() int { return r.n }

// Push adds an element, dropping the oldest one if the buffer is full.
//
// Dropping rather than growing is the point of the type: the newest elements
// are the ones kept, and how much memory that costs was decided when the
// container was made.
func (r *Recent) Push(v Entry) {
	r.built()

	if r.n == len(r.buf) {
		r.buf[r.head] = v
		r.head = recentIndexOf(r.head, 1, len(r.buf))
		return
	}

	r.buf[recentIndexOf(r.head, r.n, len(r.buf))] = v
	r.n++
}

// All walks the container from the oldest element to the newest.
//
// Which slots the walk covers is fixed when All is called, so pushing during
// one neither lengthens it nor makes it come back round to a slot it has been
// to. What is in a slot is read when the walk reaches it: pushing to a full
// container overwrites the oldest slot, and a walk that has not yet reached
// that slot yields what was written there rather than what it displaced.
//
// Fixing that too would mean copying the elements, which is the one thing a
// container that exists to bound its memory should not do behind a caller's
// back. Walk it, or push to it, or take a copy and do both.
func (r *Recent) All() iter.Seq[Entry] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Entry) bool) {
		for i := range held {
			if !yield(r.buf[recentIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// Backward walks the container from the newest element to the oldest. Like All,
// which slots it covers is fixed when it is called.
func (r *Recent) Backward() iter.Seq[Entry] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Entry) bool) {
		for i := held - 1; i >= 0; i-- {
			if !yield(r.buf[recentIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them, dropping older ones as it fills.
//
// A sequence longer than the container leaves the last capacity elements of it,
// which is what pushing them one at a time would leave.
func (r *Recent) AppendSeq(seq iter.Seq[Entry]) {
	for v := range seq {
		r.Push(v)
	}
}

// Reset empties the container, keeping the buffer it was constructed with.
//
// The capacity is what the container is rather than what it holds, so emptying
// does not give it up: a container that has been reset takes as many elements
// as it did when it was new, and takes them without allocating again.
//
// The elements that were there stay in the buffer until they are pushed over,
// so a container holding the last reference to something large holds it until
// then. Nothing can read them: what a walk covers is the count, and the count
// is what this sets to none.
func (r *Recent) Reset() { r.head, r.n = 0, 0 }

// built stops a container that was never constructed from being added to.
//
// A zero value has no buffer, so it can hold nothing and never will. Under the
// policy that overwrites, adding to one indexes an empty slice and panics on
// its own; under the policy that refuses, it would report the container full —
// which is true and useless, since a caller checking for a full container reads
// that as back-pressure and retries for ever. Saying the same thing both ways
// makes the mistake one answer rather than two.
func (r *Recent) built() {
	if len(r.buf) == 0 {
		panic("forge: this container was never constructed; use the constructor")
	}
}

// recentIndexOf returns where the element i places after the one at from is kept.
//
// Given the buffer's own head and size it answers for the container as it is;
// given a head a walk took when it started, it answers for the container as it
// was, which is what keeps a walk on the positions it set out to visit.
//
// One subtraction rather than a remainder: i is never more than the number of
// elements held, which is never more than the size, so the sum passes the end
// of the buffer at most once.
func recentIndexOf(from, i, size int) int {
	if slot := from + i; slot < size {
		return slot
	}
	return from + i - size
}

// The walk's own signature, checked when the package is built.
//
// A method expression is resolved by the compiler and costs nothing at run
// time, where an interface assertion would have to name a value and initialise
// it. What it holds the walk to is the element type of the declaration, so a
// container that walks something else fails here rather than wherever somebody
// ranges over it.
var _ func(*Recent) iter.Seq[Entry] = (*Recent).All
