// Code generated by forge. DO NOT EDIT.

package model

import (
	"errors"
	"iter"
)

// Directory holds elements beside lookup maps over their declared fields, so
// that finding one by ID is a map access rather than a scan. The walk order is
// the order of addition, less what removal has moved: taking an element out
// swaps the last one into its hole. The maps are made on first use, so the zero
// value is ready to use.
type Directory struct {
	order []*directoryEntry
	byID  map[int]*directoryEntry
}

// ErrDirectoryDuplicate is returned by an add that found its key already held.
//
// One value rather than one per call, so that a caller can compare against it
// with errors.Is and act on the answer, which is the whole reason for refusing
// rather than replacing.
var ErrDirectoryDuplicate = errors.New("the key is already held")

// directoryEntry pairs an element with where the walk order holds it.
//
// The position is carried so that removal does not search: taking an element
// out swaps the last one into its slot, and the slot is written here rather
// than looked for. The element lives in this allocation for as long as it is
// held, which is what lets a lookup hand back a pointer that stays good while
// other elements come and go.
type directoryEntry struct {
	elem Person
	at   int
}

// NewDirectory returns a container holding the given elements, in order.
//
// The keys are declared unique, so two elements sharing one cannot both be
// held — and a constructor has no way to hand one of them back. It panics,
// because the elements a construction is given are the caller's own values
// rather than input from elsewhere: feed data that may collide through
// AppendSeq, which reports the collision instead.
func NewDirectory(elems ...Person) *Directory {
	out := &Directory{}
	for _, v := range elems {
		if err := out.placeChecked(v); err != nil {
			panic("forge: two of the elements a constructor was given share one key")
		}
	}
	return out
}

// Len reports how many elements the container holds.
func (r *Directory) Len() int { return len(r.order) }

// All walks the elements in the order they were added, less any that removal
// has since moved.
//
// Which slots the walk covers is fixed when All is called, so adding during
// one does not extend it. Removing during one moves the last element into the
// hole, so a walk that has not reached either slot sees the moved element
// where the removed one was and nothing at the end.
func (r *Directory) All() iter.Seq[Person] {
	held := r.order

	return func(yield func(Person) bool) {
		for _, e := range held {
			if !yield(e.elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, and stops at the
// first whose key is already held.
//
// What was added stays. The sequence is not read past the element that was
// refused, so a caller holding one that is expensive to produce does not pay
// to produce the rest of it.
func (r *Directory) AppendSeq(seq iter.Seq[Person]) error {
	for v := range seq {
		if err := r.placeChecked(v); err != nil {
			return err
		}
	}
	return nil
}

// pick returns a pointer to the element held under a key, and whether one is.
//
// The pointer stays good while other elements are added and removed, and stops
// meaning anything once the element it names is removed. The fields the
// lookups are keyed by are not the caller's to change through it: a container
// told nothing files the element where the old values say.
func (r *Directory) pick[K comparable](m map[K]*directoryEntry, k K) (*Person, bool) {
	e, held := m[k]
	if !held {
		return nil, false
	}
	return &e.elem, true
}

// noted files an element under its key, making the map on first use.
func (r *Directory) noted[K comparable](m map[K]*directoryEntry, k K, e *directoryEntry) map[K]*directoryEntry {
	if m == nil {
		m = make(map[K]*directoryEntry)
	}
	m[k] = e
	return m
}

// cut takes the element at one slot out of the walk order, moving the last
// element into the hole so nothing shuffles.
func (r *Directory) cut(at int) {
	last := len(r.order) - 1
	moved := r.order[last]

	r.order[at] = moved
	moved.at = at

	r.order[last] = nil
	r.order = r.order[:last]
}

// ByID returns a pointer to the element held under this ID, and whether one is.
func (r *Directory) ByID(k int) (*Person, bool) {
	return r.pick(r.byID, k)
}

// Remove takes the element held under this key out of the container, and
// reports whether one was. It costs the buckets the element was filed in and
// nothing per element held: the last entry in the walk order moves into the
// hole rather than everything shuffling down.
func (r *Directory) Remove(k int) bool {
	e, held := r.byID[k]
	if !held {
		return false
	}
	delete(r.byID, k)
	r.cut(e.at)
	return true
}

// Reset empties the container, keeping the memory it has already taken. The
// entries that were held are let go, so the elements can be collected while the
// order's own memory stays for the next fill.
func (r *Directory) Reset() {
	clear(r.order)
	r.order = r.order[:0]
	clear(r.byID)
}

// placeChecked adds one element to the order and files it under every key,
// unless its key is already held.
func (r *Directory) placeChecked(v Person) error {
	if _, held := r.byID[v.ID]; held {
		return ErrDirectoryDuplicate
	}
	e := &directoryEntry{elem: v, at: len(r.order)}
	r.order = append(r.order, e)
	r.byID = r.noted(r.byID, v.ID, e)
	return nil
}
