//go:build forgespec

// Code generated by forge's race harness. DO NOT EDIT.
//
// This is the spec side of the declarations the matrix runs: one per layer
// that makes a stack safe to share, written from the catalog rather than by
// hand, so that a layer added to the catalog cannot arrive without one.
//
// The stack under each of them is the same on purpose. A bounded container
// of elements that carry a codec is the arrangement with the most surface
// for a concurrent layer to get wrong — a walk, a count, a copy and a
// document — so it is what every one of them is put through, and the only
// thing that differs between the tests is the layer being tested.
package model

import "github.com/okian/forge"

// GuardedPersons is what the Guarded layer is put through.
//
//forge:ring cap=64
type GuardedPersons forge.Guarded[forge.Ring[forge.Json[Person]]]

// AtomicPersons is what the Atomic layer is put through.
type AtomicPersons forge.Atomic[forge.Slice[Person]]
