// Code generated by forge. DO NOT EDIT.
//
// forge v0.0.0
// markers v0.0.0
// go go1.27.0
// inputs 0000000000000000

package model

// Describe is a method a previous run wrote, which is what makes this file the
// interesting one: nothing about the method itself says it was generated, and
// go/types reports it exactly as it reports the one the author wrote.
func (p Person) Describe() string { return p.Name }
