// Code generated by forge's race harness. DO NOT EDIT.
//
// It is committed so that the ordinary test run covers it, and recorded so
// that a change to what it exercises is a diff somebody reads.

package model

import (
	"bytes"
	"encoding/json/jsontext"
	"slices"
	"sync"
	"sync/atomic"
	"testing"
)

// TestPersonsUnderConcurrentUse runs writers and readers against one
// Persons at once.
//
// The failure worth catching here is a race, which has no assertion and is
// reported by the detector — so running this without the detector says
// only that the calls work.
//
// What it does assert is that they ran at all. A scope that took the lock
// and never called what it was given races nobody and passes every check
// the detector makes, so the counters below are what tell a container that
// is correctly locked from one that does nothing.
//
// The routes taken every round are Len, Snapshot, a walk inside RDo and MarshalJSONTo,
// because each holds the value for a different length of time and a
// concurrent layer that is right about one of them is not thereby right
// about the rest. A method answering with nothing is not among them: what
// one does cannot be read off its signature, and calling it because it
// took no arguments is as likely to deadlock the run as to stress it.
func TestPersonsUnderConcurrentUse(t *testing.T) {
	t.Parallel()

	held := NewPersons(64)

	var wrote, read, walked atomic.Int64
	var done atomic.Bool

	var writing, reading sync.WaitGroup

	// The writers, which reach the container only through a write scope —
	// which is the whole of what a concurrent layer does, so a stress test
	// that got at it any other way would be stressing something no caller
	// can write.
	//
	// They run until the readers have finished rather than for a count of
	// their own: a writing round adds one element and a reading round reads
	// the whole container, so matched counts would leave the readers running
	// alone for most of the test.
	//
	// The ceiling is a backstop. A container that does not grow reaches the
	// readers' end long before it, and one that does would otherwise feed
	// itself — each element added makes every later reading round slower,
	// which gives the writers longer to add more.
	for range 4 {
		writing.Go(func() {
			var one Person

			for range 16384 {
				if done.Load() {
					break
				}

				held.Do(func(v PersonsView) {
					v.AppendSeq(slices.Values([]Person{one}))
					wrote.Add(1)
				})
			}
		})
	}

	// The readers. Each round takes every route out of the container that
	// does not change it, so the detector sees them overlapping with the
	// writers above and with each other.
	for range 4 {
		reading.Go(func() {
			for range 64 {
				_ = held.Len()
				_ = held.Snapshot()

				held.RDo(func(v PersonsView) {
					read.Add(1)

					for range v.All() {
						walked.Add(1)
					}
				})

				var out bytes.Buffer
				if err := held.MarshalJSONTo(jsontext.NewEncoder(&out)); err != nil {
					t.Errorf("writing the container: %v", err)
					return
				}
			}
		})
	}

	reading.Wait()
	done.Store(true)
	writing.Wait()

	// What a green run has to mean. Each of these is zero for a container
	// that took the lock and then did nothing with it — which races nobody,
	// passes the detector, and is not what any of this is for.
	for _, one := range []struct {
		wrong string
		ran   int64
	}{
		{"the write scope never ran what it was given", wrote.Load()},
		{"the read scope never ran what it was given", read.Load()},
		{"nothing was ever walked inside a read scope", walked.Load()},
	} {
		if one.ran == 0 {
			t.Error(one.wrong)
		}
	}
}
