// Code generated by forge. DO NOT EDIT.
//
// forge v1.2.3
// markers v1.2.3
// go go1.27.0
// inputs f931373392eeee2c

//go:build !forgespec

package model

import (
	"iter"
	"slices"
	"sync"
)

// Persons is Person behind a read-write lock.
//
// Everything the stack below offers is on personsHeld, which this holds
// and nothing else can reach. What reaches it is a scope: Do under the
// write lock, RDo under the read lock, each handed a PersonsView for
// as long as the call lasts.
//
// The zero value is ready to use, because the zero value of what it holds
// is.
//
// The lock must not be copied once it has been used, which is why every
// method here is on the pointer.
type Persons struct {
	mu   sync.RWMutex
	held personsHeld
}

// Do runs f with the write lock held.
//
// Everything beneath the lock is reachable through the view for as long as
// the call lasts, and no longer: a view kept past it reaches the same data
// with nothing held. The lock is not reentrant, so a call back into this
// value from inside f deadlocks — which the view cannot be used to write,
// and the value f closed over still can.
func (g *Persons) Do(f func(v PersonsView)) {
	g.mu.Lock()
	defer g.mu.Unlock()

	f(PersonsView{held: &g.held})
}

// RDo runs f with the read lock held.
//
// Several readers run at once and a writer waits for all of them, so a long
// read is a writer held up.
//
// What f is handed reaches the whole of what is below, including whatever
// changes it — the read lock is what this holds and not what the view
// enforces. Changing anything through it is a data race against the other
// readers this let in, and Do is what to use instead. Nothing here
// stops it: telling a method that reads from one that writes needs
// something the layers do not currently say about themselves.
//
// Nor is a read lock reentrant, which is the less obvious half: a second
// RLock taken while a writer is waiting blocks behind that writer, so
// Len, Snapshot and the codec called from inside f deadlock under
// contention and pass every test that runs without it. Do from inside f
// deadlocks outright, since it waits for the read lock f is holding.
// Read what you need through the view.
func (g *Persons) RDo(f func(v PersonsView)) {
	g.mu.RLock()
	defer g.mu.RUnlock()

	f(PersonsView{held: &g.held})
}

// Snapshot returns the elements, copied under the read lock.
//
// The slice is nobody else's, so it can be walked, sorted and held with
// nothing locked. It costs a copy of the elements, which is the price of
// walking something a writer may be changing — and the alternative is not
// a cheaper walk but a walk that races.
//
// The elements are copied the way Go copies anything, which is to say
// shallowly: a field that is a slice, a map or a pointer still refers to
// what the element in the container refers to. Writing through one of
// those from here is a write to memory another goroutine reads under the
// lock, which the lock cannot see and will not stop. Treat what comes
// back as readable rather than as yours.
//
// One allocation, because the container can say how much it holds before
// the walk starts. A copy that grew as it went would allocate once per
// doubling and copy what it had each time — which is what collecting a
// sequence of unknown length has to do, and is not what this is.
func (g *Persons) Snapshot() []Person {
	g.mu.RLock()
	defer g.mu.RUnlock()

	return slices.AppendSeq(
		make([]Person, 0, g.held.Len()),
		g.held.All())
}

// Len returns how many elements there are.
//
// Reached directly rather than through a scope, because it is one number
// read and handed back: there is nothing a caller can hold open, and asking
// them to write a closure for it would teach them that scopes are ceremony.
//
// It is a fact about the past by the time it is read, like every count of
// something another goroutine may be changing.
func (g *Persons) Len() int {
	g.mu.RLock()
	defer g.mu.RUnlock()

	return g.held.Len()
}

// PersonsView is what a scope over Persons hands the function it runs.
//
// No method on it names this type or the one it guards, so the call that
// deadlocks by accident — reaching for the value you were just handed and
// finding a way back in — cannot be written through this.
//
// Four things that leaves you, and every one of them is ordinary Go.
//
// The value the scope was opened on is still in scope inside the call, so
// calling a method on that deadlocks as it always would. Nothing here can
// hold a value inside the call it came from, so this kept past the call —
// or a sequence taken from it and walked afterwards — reaches the same data
// with nothing held. A way out spelled some other way, through an
// interface or an alias, is a name this cannot recognise. And this type
// is declared in your own package, so its field is reachable by hand and
// its zero value exists — neither of which any arrangement of methods can
// prevent.
type PersonsView struct {
	held *personsHeld
}

// Len how many elements the container holds
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) Len() int {
	return v.held.Len()
}

// All walks from the first element to the last
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) All() iter.Seq[Person] {
	return v.held.All()
}

// Backward walks from the last element to the first
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) Backward() iter.Seq[Person] {
	return v.held.Backward()
}

// AppendSeq adds every element a sequence yields
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) AppendSeq(a0 iter.Seq[Person]) {
	v.held.AppendSeq(a0)
}

// Reset empties the container, keeping the memory it has taken
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) Reset() {
	v.held.Reset()
}

// personsHeld holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type personsHeld []Person

// newPersonsHeld returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func newPersonsHeld(elems ...Person) personsHeld { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s personsHeld) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s personsHeld) All() iter.Seq[Person] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s personsHeld) Backward() iter.Seq[Person] {
	return func(yield func(Person) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *personsHeld) AppendSeq(seq iter.Seq[Person]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *personsHeld) Reset() { *s = (*s)[:0] }
