// Code generated by forge. DO NOT EDIT.
//
// forge v1.2.3
// markers v1.2.3
// go go1.27.0
// inputs 58d63021d9424a2e

//go:build !forgespec

package model

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"iter"
	"slices"
	"sync"
)

// Persons is Person behind a read-write lock.
//
// Everything the stack below offers is on personsHeld, which this holds
// and nothing else can reach. What reaches it is a scope: Do under the
// write lock, RDo under the read lock, each handed a PersonsView for
// as long as the call lasts.
//
// The zero value holds a container that was never made and can hold
// nothing, so use NewPersons.
//
// The lock must not be copied once it has been used, which is why every
// method here is on the pointer.
type Persons struct {
	mu   sync.RWMutex
	held personsHeld
}

// NewPersons returns a lock around a new personsHeld.
//
// The container beneath a lock is made rather than declared — it has to be
// told how much it holds — so this is the way in, and the zero value of
// this type is a lock around a container that will refuse every element.
//
// What is made here is reachable through this lock and through nothing
// else, which is the whole of what the lock is for.
func NewPersons() *Persons {
	return &Persons{held: *newPersonsHeld()}
}

// Do runs f with the write lock held.
//
// Everything beneath the lock is reachable through the view for as long as
// the call lasts, and no longer: a view kept past it reaches the same data
// with nothing held. The lock is not reentrant, so a call back into this
// value from inside f deadlocks — which the view cannot be used to write,
// and the value f closed over still can.
func (g *Persons) Do(f func(v PersonsView)) {
	g.mu.Lock()
	defer g.mu.Unlock()

	f(PersonsView{held: &g.held})
}

// RDo runs f with the read lock held.
//
// Several readers run at once and a writer waits for all of them, so a long
// read is a writer held up.
//
// What f is handed reaches the whole of what is below, including whatever
// changes it — the read lock is what this holds and not what the view
// enforces. Changing anything through it is a data race against the other
// readers this let in, and Do is what to use instead. Nothing here
// stops it: telling a method that reads from one that writes needs
// something the layers do not currently say about themselves.
//
// Nor is a read lock reentrant, which is the less obvious half: a second
// RLock taken while a writer is waiting blocks behind that writer, so
// Len, Snapshot and the codec called from inside f deadlock under
// contention and pass every test that runs without it. Do from inside f
// deadlocks outright, since it waits for the read lock f is holding.
// Read what you need through the view.
func (g *Persons) RDo(f func(v PersonsView)) {
	g.mu.RLock()
	defer g.mu.RUnlock()

	f(PersonsView{held: &g.held})
}

// Snapshot returns the elements, copied under the read lock.
//
// The slice is nobody else's, so it can be walked, sorted and held with
// nothing locked. It costs a copy of the elements, which is the price of
// walking something a writer may be changing — and the alternative is not
// a cheaper walk but a walk that races.
//
// The elements are copied the way Go copies anything, which is to say
// shallowly: a field that is a slice, a map or a pointer still refers to
// what the element in the container refers to. Writing through one of
// those from here is a write to memory another goroutine reads under the
// lock, which the lock cannot see and will not stop. Treat what comes
// back as readable rather than as yours.
//
// One allocation, because the container can say how much it holds before
// the walk starts. A copy that grew as it went would allocate once per
// doubling and copy what it had each time — which is what collecting a
// sequence of unknown length has to do, and is not what this is.
func (g *Persons) Snapshot() []Person {
	g.mu.RLock()
	defer g.mu.RUnlock()

	return slices.AppendSeq(
		make([]Person, 0, g.held.Len()),
		g.held.All())
}

// Len returns how many elements there are.
//
// Reached directly rather than through a scope, because it is one number
// read and handed back: there is nothing a caller can hold open, and asking
// them to write a closure for it would teach them that scopes are ceremony.
//
// It is a fact about the past by the time it is read, like every count of
// something another goroutine may be changing.
func (g *Persons) Len() int {
	g.mu.RLock()
	defer g.mu.RUnlock()

	return g.held.Len()
}

// Lock and Unlock take and release the write lock, making this a
// sync.Locker.
//
// Written because the declaration asked for them. They are what the rest of
// this type exists to make unnecessary: a caller holding the lock directly
// can reach nothing the lock guards — everything beneath it is behind a
// scope, and a scope takes the lock itself.
//
// Which is the same sentence read the other way round: every method that
// reaches the data takes the lock, so calling one while holding it
// deadlocks. What these are for is handing this value to something that
// asks for a sync.Locker and does not otherwise touch it — a sync.Cond is
// the case worth having them for — and not for reaching the data.
func (g *Persons) Lock() { g.mu.Lock() }

// Unlock releases the write lock.
func (g *Persons) Unlock() { g.mu.Unlock() }

// MarshalJSONTo writes the container as a JSON array, with the read
// lock held for the length of the write.
//
// Written this way because the declaration asked for it, and it is the
// right answer only when the encoder's writer is one the caller controls:
// nothing is copied, and every writer of this container waits for however
// long the encoder takes to finish. A writer that blocks blocks them all.
func (g *Persons) MarshalJSONTo(enc *jsontext.Encoder) error {
	g.mu.RLock()
	defer g.mu.RUnlock()

	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}
	for v := range g.held.All() {
		if err := v.MarshalJSONTo(enc); err != nil {
			return err
		}
	}
	return enc.WriteToken(jsontext.EndArray)
}

// PersonsView is what a scope over Persons hands the function it runs.
//
// No method on it names this type or the one it guards, so the call that
// deadlocks by accident — reaching for the value you were just handed and
// finding a way back in — cannot be written through this.
//
// Four things that leaves you, and every one of them is ordinary Go.
//
// The value the scope was opened on is still in scope inside the call, so
// calling a method on that deadlocks as it always would. Nothing here can
// hold a value inside the call it came from, so this kept past the call —
// or a sequence taken from it and walked afterwards — reaches the same data
// with nothing held. A way out spelled some other way, through an
// interface or an alias, is a name this cannot recognise. And this type
// is declared in your own package, so its field is reachable by hand and
// its zero value exists — neither of which any arrangement of methods can
// prevent.
type PersonsView struct {
	held *personsHeld
}

// Cap how many elements the container can hold
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) Cap() int {
	return v.held.Cap()
}

// Len how many elements the container holds
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) Len() int {
	return v.held.Len()
}

// All walks from the oldest element to the newest
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) All() iter.Seq[Person] {
	return v.held.All()
}

// Backward walks from the newest element to the oldest
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) Backward() iter.Seq[Person] {
	return v.held.Backward()
}

// Reset empties the container, keeping the buffer it was constructed with
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) Reset() {
	v.held.Reset()
}

// Push adds an element, dropping the oldest to make room
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) Push(a0 Person) {
	v.held.Push(a0)
}

// AppendSeq adds every element a sequence yields, dropping older ones as it fills
//
// It is the same method the stack below declares, reached through the view.
func (v PersonsView) AppendSeq(a0 iter.Seq[Person]) {
	v.held.AppendSeq(a0)
}

// personsHeldFixedCap is how many elements the buffer holds.
//
// It is a constant rather than a field, so the size is part of the type rather
// than of a value: every container of this type holds the same number, the
// compiler knows it, and no caller can be handed one sized differently from the
// one it expected.
const personsHeldFixedCap = 8

// personsHeld holds a fixed number of the most recent elements.
//
// The buffer is allocated once and never grows, so a producer that outruns its
// consumer costs a bounded amount of memory rather than an increasing one. That
// is the whole of what this type is for, and it is why every method that adds
// an element has an answer for a buffer that is already full.
//
// The elements live in a slice that is treated as a circle: head is where the
// oldest one is, and n is how many there are. Reading walks from head, wrapping
// at the end, so the order elements come back in is the order they went in
// — the oldest first — regardless of where in the slice they happen to sit.
//
// The zero value has no buffer at all, which is not the same as an empty
// container and is not something any method can make sense of. Adding to one
// says so rather than carrying on. Use the constructor.
type personsHeld struct {
	buf  []Person
	head int
	n    int
}

// newPersonsHeld returns an empty container, whose capacity is the one the
// declaration fixed.
func newPersonsHeld() *personsHeld {
	return &personsHeld{buf: make([]Person, personsHeldFixedCap)}
}

// Cap reports how many elements the container can hold, which does not change.
func (r *personsHeld) Cap() int { return len(r.buf) }

// Len reports how many elements the container holds, which is never more than
// its capacity.
func (r *personsHeld) Len() int { return r.n }

// Push adds an element, dropping the oldest one if the buffer is full.
//
// Dropping rather than growing is the point of the type: the newest elements
// are the ones kept, and how much memory that costs was decided when the
// container was made.
func (r *personsHeld) Push(v Person) {
	r.built()

	if r.n == len(r.buf) {
		r.buf[r.head] = v
		r.head = personsHeldIndexOf(r.head, 1, len(r.buf))
		return
	}

	r.buf[personsHeldIndexOf(r.head, r.n, len(r.buf))] = v
	r.n++
}

// All walks the container from the oldest element to the newest.
//
// Which slots the walk covers is fixed when All is called, so pushing during
// one neither lengthens it nor makes it come back round to a slot it has been
// to. What is in a slot is read when the walk reaches it: pushing to a full
// container overwrites the oldest slot, and a walk that has not yet reached
// that slot yields what was written there rather than what it displaced.
//
// Fixing that too would mean copying the elements, which is the one thing a
// container that exists to bound its memory should not do behind a caller's
// back. Walk it, or push to it, or take a copy and do both.
func (r *personsHeld) All() iter.Seq[Person] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Person) bool) {
		for i := range held {
			if !yield(r.buf[personsHeldIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// Backward walks the container from the newest element to the oldest. Like All,
// which slots it covers is fixed when it is called.
func (r *personsHeld) Backward() iter.Seq[Person] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Person) bool) {
		for i := held - 1; i >= 0; i-- {
			if !yield(r.buf[personsHeldIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them, dropping older ones as it fills.
//
// A sequence longer than the container leaves the last capacity elements of it,
// which is what pushing them one at a time would leave.
func (r *personsHeld) AppendSeq(seq iter.Seq[Person]) {
	for v := range seq {
		r.Push(v)
	}
}

// Reset empties the container, keeping the buffer it was constructed with.
//
// The capacity is what the container is rather than what it holds, so emptying
// does not give it up: a container that has been reset takes as many elements
// as it did when it was new, and takes them without allocating again.
//
// The elements that were there stay in the buffer until they are pushed over,
// so a container holding the last reference to something large holds it until
// then. Nothing can read them: what a walk covers is the count, and the count
// is what this sets to none.
func (r *personsHeld) Reset() { r.head, r.n = 0, 0 }

// built stops a container that was never constructed from being added to.
//
// A zero value has no buffer, so it can hold nothing and never will. Under the
// policy that overwrites, adding to one indexes an empty slice and panics on
// its own; under the policy that refuses, it would report the container full —
// which is true and useless, since a caller checking for a full container reads
// that as back-pressure and retries for ever. Saying the same thing both ways
// makes the mistake one answer rather than two.
func (r *personsHeld) built() {
	if len(r.buf) == 0 {
		panic("forge: this container was never constructed; use the constructor")
	}
}

// personsHeldIndexOf returns where the element i places after the one at from is kept.
//
// Given the buffer's own head and size it answers for the container as it is;
// given a head a walk took when it started, it answers for the container as it
// was, which is what keeps a walk on the positions it set out to visit.
//
// One subtraction rather than a remainder: i is never more than the number of
// elements held, which is never more than the size, so the sum passes the end
// of the buffer at most once.
func personsHeldIndexOf(from, i, size int) int {
	if slot := from + i; slot < size {
		return slot
	}
	return from + i - size
}

// Persons satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ json.MarshalerTo = (*Persons)(nil)
	_ sync.Locker      = (*Persons)(nil)
)

// encodeModelPersonJSONTo writes a Person as JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func encodeModelPersonJSONTo(enc *jsontext.Encoder, v Person) error {
	return v.MarshalJSONTo(enc)
}

// MarshalJSONTo writes the Person as a JSON object.
//
// Members are written in the order the fields are declared, an embedded
// struct's where the embedded field is. A field that takes a name from a
// shallower one keeps its own place rather than the excluded one's.
func (v Person) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("ID")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.Int(int64(v.ID))); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("Name")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(string(v.Name))); err != nil {
		return err
	}
	return enc.WriteToken(jsontext.EndObject)
}

// decodeModelPersonJSONFrom reads a Person from JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func decodeModelPersonJSONFrom(dec *jsontext.Decoder, v *Person) error {
	return v.UnmarshalJSONFrom(dec)
}

// UnmarshalJSONFrom reads a JSON object into the Person.
//
// A member the object holds and the type does not is skipped, which is
// what keeps a reader working against a writer that has since added one.
func (v *Person) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if dec.PeekKind() == 'n' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		var zero Person
		*v = zero
		return nil
	}
	if kind := dec.PeekKind(); kind != '{' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		return fmt.Errorf("cannot read Person from a JSON %s", kind)
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		name, err := dec.ReadToken()
		if err != nil {
			return err
		}
		switch name.String() {
		case "ID":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero int
					v.ID = zero
				case '0':
					number, err := raw.Int()
					if err != nil {
						return err
					}
					if int64(int(number)) != number {
						return fmt.Errorf("%d is out of range for int", number)
					}
					v.ID = int(number)
				default:
					return fmt.Errorf("cannot read int from a JSON %s", raw.Kind())
				}
			}
		case "Name":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero string
					v.Name = zero
				case '"':
					v.Name = string(raw.String())
				default:
					return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
				}
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	_, err := dec.ReadToken()
	return err
}

// Person satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ json.MarshalerTo     = *new(Person)
	_ json.UnmarshalerFrom = (*Person)(nil)
)
