// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge (devel)
// go go1.27.1
// inputs e1adbd4484ad970e

//go:build !forgespec

package people

import (
	"cmp"
	"encoding"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"io"
	"iter"
	"log/slog"
	"math"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"sync"
)

// PersonsSeq is a lazy view over the elements of Persons.
type PersonsSeq struct {
	Seq[Person]
}

// Seq returns a lazy view over the elements. Its combinators are the shared
// Seq[Person] view's.
func (c Persons) Seq() PersonsSeq {
	return PersonsSeq{Seq[Person](c.All())}
}

// IDs returns the ID of every element, in order.
func (c Persons) IDs() []int {
	return c.project(func(v Person) int {
		return v.ID
	})
}

// Names returns the Name of every element, in order.
func (c Persons) Names() []string {
	return c.project(func(v Person) string {
		return v.Name
	})
}

// Emails returns the Email of every element, in order.
func (c Persons) Emails() []string {
	return c.project(func(v Person) string {
		return v.Email
	})
}

// Ages returns the Age of every element, in order.
func (c Persons) Ages() []int {
	return c.project(func(v Person) int {
		return v.Age
	})
}

// Aliases returns the Aliases of every element, in order.
func (c Persons) Aliases() [][]string {
	return c.project(func(v Person) []string {
		return v.Aliases
	})
}

// SortedByName returns the elements ordered by Name, leaving equal ones as they
// were.
func (c Persons) SortedByName() []Person {
	return c.ordered(func(v Person) string {
		return v.Name
	})
}

// SortedByAge returns the elements ordered by Age, leaving equal ones as they
// were.
func (c Persons) SortedByAge() []Person {
	return c.ordered(func(v Person) int {
		return v.Age
	})
}

// ByID returns the elements keyed by ID, keeping the last of any that share
// one.
func (c Persons) ByID() map[int]Person {
	return c.keyed(func(v Person) int {
		return v.ID
	})
}

// project collects one value from every element, in the order the elements come
// in.
//
// The result is grown rather than sized ahead, because what is walked is not
// always something that can be counted first — a walk is all this needs of the
// collection, and needing a length as well would be needing more.
func (c Persons) project[V any](of func(Person) V) []V {
	var out []V
	for v := range c.All() {
		out = append(out, of(v))
	}
	return out
}

// keyed returns the elements by the key taken from each of them.
//
// Later wins where two elements share a key, which is what writing into a map
// does and is the only answer that does not need a policy. A key that has to be
// unique is a thing to check, not a thing to discover from which element came
// last.
//
// A key type that holds an interface is a key that can be built and cannot
// always be used: the map panics on a dynamic value that is not comparable,
// exactly as any other map keyed the same way does.
func (c Persons) keyed[K comparable](by func(Person) K) map[K]Person {
	out := make(map[K]Person)
	for v := range c.All() {
		out[by(v)] = v
	}
	return out
}

// ordered returns the elements sorted by the key taken from each of them,
// leaving equal ones in the order they came in.
//
// A new slice rather than a sort in place: the collection is what it was, and a
// method that quietly reordered it would make asking a question change the
// answer to the next one.
func (c Persons) ordered[K cmp.Ordered](by func(Person) K) []Person {
	out := slices.Collect(c.All())
	slices.SortStableFunc(out, func(a, b Person) int { return cmp.Compare(by(a), by(b)) })

	return out
}

// NewPersons returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewPersons(elems ...Person) Persons { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Persons) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Persons) All() iter.Seq[Person] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Persons) Backward() iter.Seq[Person] {
	return func(yield func(Person) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Persons) AppendSeq(seq iter.Seq[Person]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *Persons) Reset() { *s = (*s)[:0] }

// The walk's own signature, checked when the package is built.
//
// A method expression is resolved by the compiler and costs nothing at run
// time, where an interface assertion would have to name a value and initialise
// it. What it holds the walk to is the element type of the declaration, so a
// container that walks something else fails here rather than wherever somebody
// ranges over it.
var _ func(*Persons) iter.Seq[Person] = (*Persons).All

// RecentSeq is a lazy view over the elements of Recent.
type RecentSeq struct {
	Seq[Person]
}

// Seq returns a lazy view over the elements. Its combinators are the shared
// Seq[Person] view's.
func (c Recent) Seq() RecentSeq {
	return RecentSeq{Seq[Person](c.All())}
}

// IDs returns the ID of every element, in order.
func (c Recent) IDs() []int {
	return c.project(func(v Person) int {
		return v.ID
	})
}

// Names returns the Name of every element, in order.
func (c Recent) Names() []string {
	return c.project(func(v Person) string {
		return v.Name
	})
}

// Emails returns the Email of every element, in order.
func (c Recent) Emails() []string {
	return c.project(func(v Person) string {
		return v.Email
	})
}

// Ages returns the Age of every element, in order.
func (c Recent) Ages() []int {
	return c.project(func(v Person) int {
		return v.Age
	})
}

// Aliases returns the Aliases of every element, in order.
func (c Recent) Aliases() [][]string {
	return c.project(func(v Person) []string {
		return v.Aliases
	})
}

// project collects one value from every element, in the order the elements come
// in.
//
// The result is grown rather than sized ahead, because what is walked is not
// always something that can be counted first — a walk is all this needs of the
// collection, and needing a length as well would be needing more.
func (c Recent) project[V any](of func(Person) V) []V {
	var out []V
	for v := range c.All() {
		out = append(out, of(v))
	}
	return out
}

// recentFixedCap is how many elements the buffer holds.
//
// It is a constant rather than a field, so the size is part of the type rather
// than of a value: every container of this type holds the same number, the
// compiler knows it, and no caller can be handed one sized differently from the
// one it expected.
const recentFixedCap = 1024

// Recent holds a fixed number of the most recent elements.
//
// The buffer is allocated once and never grows, so a producer that outruns its
// consumer costs a bounded amount of memory rather than an increasing one. That
// is the whole of what this type is for, and it is why every method that adds
// an element has an answer for a buffer that is already full.
//
// The elements live in a slice that is treated as a circle: head is where the
// oldest one is, and n is how many there are. Reading walks from head, wrapping
// at the end, so the order elements come back in is the order they went in
// — the oldest first — regardless of where in the slice they happen to sit.
//
// The zero value has no buffer at all, which is not the same as an empty
// container and is not something any method can make sense of. Adding to one
// says so rather than carrying on. Use the constructor.
type Recent struct {
	buf  []Person
	head int
	n    int
}

// NewRecent returns an empty container, whose capacity is the one the
// declaration fixed.
func NewRecent() *Recent {
	return &Recent{buf: make([]Person, recentFixedCap)}
}

// Cap reports how many elements the container can hold, which does not change.
func (r *Recent) Cap() int { return len(r.buf) }

// Len reports how many elements the container holds, which is never more than
// its capacity.
func (r *Recent) Len() int { return r.n }

// Push adds an element, dropping the oldest one if the buffer is full.
//
// Dropping rather than growing is the point of the type: the newest elements
// are the ones kept, and how much memory that costs was decided when the
// container was made.
func (r *Recent) Push(v Person) {
	r.built()

	if r.n == len(r.buf) {
		r.buf[r.head] = v
		r.head = recentIndexOf(r.head, 1, len(r.buf))
		return
	}

	r.buf[recentIndexOf(r.head, r.n, len(r.buf))] = v
	r.n++
}

// All walks the container from the oldest element to the newest.
//
// Which slots the walk covers is fixed when All is called, so pushing during
// one neither lengthens it nor makes it come back round to a slot it has been
// to. What is in a slot is read when the walk reaches it: pushing to a full
// container overwrites the oldest slot, and a walk that has not yet reached
// that slot yields what was written there rather than what it displaced.
//
// Fixing that too would mean copying the elements, which is the one thing a
// container that exists to bound its memory should not do behind a caller's
// back. Walk it, or push to it, or take a copy and do both.
func (r *Recent) All() iter.Seq[Person] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Person) bool) {
		for i := range held {
			if !yield(r.buf[recentIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// Backward walks the container from the newest element to the oldest. Like All,
// which slots it covers is fixed when it is called.
func (r *Recent) Backward() iter.Seq[Person] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Person) bool) {
		for i := held - 1; i >= 0; i-- {
			if !yield(r.buf[recentIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them, dropping older ones as it fills.
//
// A sequence longer than the container leaves the last capacity elements of it,
// which is what pushing them one at a time would leave.
func (r *Recent) AppendSeq(seq iter.Seq[Person]) {
	for v := range seq {
		r.Push(v)
	}
}

// Reset empties the container, keeping the buffer it was constructed with.
//
// The capacity is what the container is rather than what it holds, so emptying
// does not give it up: a container that has been reset takes as many elements
// as it did when it was new, and takes them without allocating again.
//
// The elements that were there stay in the buffer until they are pushed over,
// so a container holding the last reference to something large holds it until
// then. Nothing can read them: what a walk covers is the count, and the count
// is what this sets to none.
func (r *Recent) Reset() { r.head, r.n = 0, 0 }

// built stops a container that was never constructed from being added to.
//
// A zero value has no buffer, so it can hold nothing and never will. Under the
// policy that overwrites, adding to one indexes an empty slice and panics on
// its own; under the policy that refuses, it would report the container full —
// which is true and useless, since a caller checking for a full container reads
// that as back-pressure and retries for ever. Saying the same thing both ways
// makes the mistake one answer rather than two.
func (r *Recent) built() {
	if len(r.buf) == 0 {
		panic("forge: this container was never constructed; use the constructor")
	}
}

// recentIndexOf returns where the element i places after the one at from is kept.
//
// Given the buffer's own head and size it answers for the container as it is;
// given a head a walk took when it started, it answers for the container as it
// was, which is what keeps a walk on the positions it set out to visit.
//
// One subtraction rather than a remainder: i is never more than the number of
// elements held, which is never more than the size, so the sum passes the end
// of the buffer at most once.
func recentIndexOf(from, i, size int) int {
	if slot := from + i; slot < size {
		return slot
	}
	return from + i - size
}

// MarshalJSONTo writes the container as a JSON array.
//
// One pass over the elements and straight into the encoder. No part of the
// document is assembled anywhere else first, so what it costs to write a
// container is what it costs to write its elements and nothing besides.
func (c *Recent) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}
	for v := range c.All() {
		if err := encodePeoplePersonJSONTo(enc, v); err != nil {
			return err
		}
	}
	return enc.WriteToken(jsontext.EndArray)
}

// recentCounting counts the bytes a writer accepted.
//
// The encoder buffers, so what it has written and what the writer beneath it
// has taken are two numbers. This is the second, which is the one a caller
// copying from the container is entitled to.
type recentCounting struct {
	to io.Writer
	n  int64
}

// Write passes the bytes on and counts the ones that were taken.
func (w *recentCounting) Write(p []byte) (int, error) {
	n, err := w.to.Write(p)
	w.n += int64(n)
	return n, err
}

// WriteTo writes the container to w as a JSON array, and reports how many bytes
// reached w.
//
// Straight to w rather than into a buffer this then copies, so a container of
// any size costs the encoder's own buffer and no more. The document ends with
// a newline, which is what an encoder leaves between the values of a stream.
func (c *Recent) WriteTo(w io.Writer) (int64, error) {
	counted := recentCounting{to: w}
	enc := jsontext.NewEncoder(&counted, jsontext.AllowDuplicateNames(true))
	if err := c.MarshalJSONTo(enc); err != nil {
		return counted.n, err
	}
	return counted.n, nil
}

// UnmarshalJSONFrom reads a JSON array into the container.
//
// What the container held is dropped first, so reading into one twice leaves
// the second document rather than both — which is what reading a document
// into a value means everywhere else. A JSON null empties it and reads
// nothing else: a container is empty or holds elements, so null and an empty
// array are read alike and both are written back as an empty array.
//
// The elements are handed over one at a time as they are read, so the
// document is never held in memory beside the container being filled from
// it.
func (c *Recent) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if c.Cap() == 0 {
		return errors.New("Recent holds nothing until it is constructed, so nothing can be read into it")
	}
	if dec.PeekKind() == 'n' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		c.Reset()
		return nil
	}
	if kind := dec.PeekKind(); kind != '[' {
		// A decoder that failed reports no kind at all, and reading is what
		// says why; a document of the wrong shape reads fine and is wrong.
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		return fmt.Errorf("cannot read Recent from a JSON %s", kind)
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	c.Reset()

	var failed error
	c.AppendSeq(func(yield func(Person) bool) {
		for dec.PeekKind() != ']' {
			var v Person
			if err := decodePeoplePersonJSONFrom(dec, &v); err != nil {
				failed = err
				return
			}
			if !yield(v) {
				return
			}
		}
	})

	if failed != nil {
		return failed
	}
	if kind := dec.PeekKind(); kind != ']' && kind != 0 {
		return errors.New("Recent stopped taking elements before the JSON array ended")
	}
	_, err := dec.ReadToken()
	return err
}

// ReadFrom reads one JSON array from r into the container, and reports how many
// bytes that array took.
//
// One array rather than everything r holds, because a JSON document ends
// where it ends. The decoder reads r in blocks, so bytes following the array
// may already have been taken out of r and are dropped with it: this reads a
// reader holding one document, and a stream of them is read through a decoder
// that outlives each. A reader holding nothing reports io.EOF.
func (c *Recent) ReadFrom(r io.Reader) (int64, error) {
	dec := jsontext.NewDecoder(r)
	if err := c.UnmarshalJSONFrom(dec); err != nil {
		return dec.InputOffset(), err
	}
	return dec.InputOffset(), nil
}

// Recent satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ io.WriterTo          = (*Recent)(nil)
	_ io.ReaderFrom        = (*Recent)(nil)
	_ json.MarshalerTo     = (*Recent)(nil)
	_ json.UnmarshalerFrom = (*Recent)(nil)
)

// And the walk's own signature, checked without calling it.
//
// A method expression is resolved when the package is built and costs nothing
// at run time, where an interface assertion would have to name a value and
// initialise it.
var _ func(*Recent) iter.Seq[Person] = (*Recent).All

// Roster is Person behind a read-write lock.
//
// Everything the stack below offers is on rosterHeld, which this holds
// and nothing else can reach. What reaches it is a scope: Do under the
// write lock, RDo under the read lock, each handed a RosterView for
// as long as the call lasts.
//
// The zero value holds a container that was never made and can hold
// nothing, so use NewRoster.
//
// The lock must not be copied once it has been used, which is why every
// method here is on the pointer.
type Roster struct {
	mu   sync.RWMutex
	held rosterHeld
}

// NewRoster returns a lock around a new rosterHeld.
//
// The container beneath a lock is made rather than declared — it has to be
// told how much it holds — so this is the way in, and the zero value of
// this type is a lock around a container that will refuse every element.
//
// What is made here is reachable through this lock and through nothing
// else, which is the whole of what the lock is for.
func NewRoster() *Roster {
	return &Roster{held: *newRosterHeld()}
}

// Do runs f with the write lock held.
//
// Everything beneath the lock is reachable through the view for as long as
// the call lasts, and no longer: a view kept past it reaches the same data
// with nothing held. The lock is not reentrant, so a call back into this
// value from inside f deadlocks — which the view cannot be used to write,
// and the value f closed over still can.
func (g *Roster) Do(f func(v RosterView)) {
	g.mu.Lock()
	defer g.mu.Unlock()

	f(RosterView{held: &g.held})
}

// RDo runs f with the read lock held.
//
// Several readers run at once and a writer waits for all of them, so a long
// read is a writer held up.
//
// What f is handed reaches the whole of what is below, including whatever
// changes it — the read lock is what this holds and not what the view
// enforces. Changing anything through it is a data race against the other
// readers this let in, and Do is what to use instead. Nothing here
// stops it: telling a method that reads from one that writes needs
// something the layers do not currently say about themselves.
//
// Nor is a read lock reentrant, which is the less obvious half: a second
// RLock taken while a writer is waiting blocks behind that writer, so
// Len, Snapshot and the codec called from inside f deadlock under
// contention and pass every test that runs without it. Do from inside f
// deadlocks outright, since it waits for the read lock f is holding.
// Read what you need through the view.
func (g *Roster) RDo(f func(v RosterView)) {
	g.mu.RLock()
	defer g.mu.RUnlock()

	f(RosterView{held: &g.held})
}

// Snapshot returns the elements, copied under the read lock.
//
// The slice is nobody else's, so it can be walked, sorted and held with
// nothing locked. It costs a copy of the elements, which is the price of
// walking something a writer may be changing — and the alternative is not
// a cheaper walk but a walk that races.
//
// The elements are copied the way Go copies anything, which is to say
// shallowly: a field that is a slice, a map or a pointer still refers to
// what the element in the container refers to. Writing through one of
// those from here is a write to memory another goroutine reads under the
// lock, which the lock cannot see and will not stop. Treat what comes
// back as readable rather than as yours.
//
// One allocation, because the container can say how much it holds before
// the walk starts. A copy that grew as it went would allocate once per
// doubling and copy what it had each time — which is what collecting a
// sequence of unknown length has to do, and is not what this is.
func (g *Roster) Snapshot() []Person {
	g.mu.RLock()
	defer g.mu.RUnlock()

	return slices.AppendSeq(
		make([]Person, 0, g.held.Len()),
		g.held.All())
}

// Len returns how many elements there are.
//
// Reached directly rather than through a scope, because it is one number
// read and handed back: there is nothing a caller can hold open, and asking
// them to write a closure for it would teach them that scopes are ceremony.
//
// It is a fact about the past by the time it is read, like every count of
// something another goroutine may be changing.
func (g *Roster) Len() int {
	g.mu.RLock()
	defer g.mu.RUnlock()

	return g.held.Len()
}

// MarshalJSONTo writes the container as a JSON array.
//
// The elements are copied under the read lock and the copy is what is
// written, so the lock is held for a copy rather than for a write. That
// matters because the encoder's writer is the caller's: a socket that
// stopped reading would otherwise hold this container against every writer
// for as long as it took to time out.
//
// It costs one copy of the elements per document. A caller who owns their
// writer and would rather not pay it can ask for the lock to be held
// instead.
func (g *Roster) MarshalJSONTo(enc *jsontext.Encoder) error {
	held := g.Snapshot()

	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}
	for i := range held {
		if err := held[i].MarshalJSONTo(enc); err != nil {
			return err
		}
	}
	return enc.WriteToken(jsontext.EndArray)
}

// RosterView is what a scope over Roster hands the function it runs.
//
// No method on it names this type or the one it guards, so the call that
// deadlocks by accident — reaching for the value you were just handed and
// finding a way back in — cannot be written through this.
//
// Four things that leaves you, and every one of them is ordinary Go.
//
// The value the scope was opened on is still in scope inside the call, so
// calling a method on that deadlocks as it always would. Nothing here can
// hold a value inside the call it came from, so this kept past the call —
// or a sequence taken from it and walked afterwards — reaches the same data
// with nothing held. A way out spelled some other way, through an
// interface or an alias, is a name this cannot recognise. And this type
// is declared in your own package, so its field is reachable by hand and
// its zero value exists — neither of which any arrangement of methods can
// prevent.
type RosterView struct {
	held *rosterHeld
}

// Cap how many elements the container can hold
//
// It is the same method the stack below declares, reached through the view.
func (v RosterView) Cap() int {
	return v.held.Cap()
}

// Len how many elements the container holds
//
// It is the same method the stack below declares, reached through the view.
func (v RosterView) Len() int {
	return v.held.Len()
}

// All walks from the oldest element to the newest
//
// It is the same method the stack below declares, reached through the view.
func (v RosterView) All() iter.Seq[Person] {
	return v.held.All()
}

// Backward walks from the newest element to the oldest
//
// It is the same method the stack below declares, reached through the view.
func (v RosterView) Backward() iter.Seq[Person] {
	return v.held.Backward()
}

// Reset empties the container, keeping the buffer it was constructed with
//
// It is the same method the stack below declares, reached through the view.
func (v RosterView) Reset() {
	v.held.Reset()
}

// Push adds an element, dropping the oldest to make room
//
// It is the same method the stack below declares, reached through the view.
func (v RosterView) Push(a0 Person) {
	v.held.Push(a0)
}

// AppendSeq adds every element a sequence yields, dropping older ones as it fills
//
// It is the same method the stack below declares, reached through the view.
func (v RosterView) AppendSeq(a0 iter.Seq[Person]) {
	v.held.AppendSeq(a0)
}

// rosterHeldFixedCap is how many elements the buffer holds.
//
// It is a constant rather than a field, so the size is part of the type rather
// than of a value: every container of this type holds the same number, the
// compiler knows it, and no caller can be handed one sized differently from the
// one it expected.
const rosterHeldFixedCap = 64

// rosterHeld holds a fixed number of the most recent elements.
//
// The buffer is allocated once and never grows, so a producer that outruns its
// consumer costs a bounded amount of memory rather than an increasing one. That
// is the whole of what this type is for, and it is why every method that adds
// an element has an answer for a buffer that is already full.
//
// The elements live in a slice that is treated as a circle: head is where the
// oldest one is, and n is how many there are. Reading walks from head, wrapping
// at the end, so the order elements come back in is the order they went in
// — the oldest first — regardless of where in the slice they happen to sit.
//
// The zero value has no buffer at all, which is not the same as an empty
// container and is not something any method can make sense of. Adding to one
// says so rather than carrying on. Use the constructor.
type rosterHeld struct {
	buf  []Person
	head int
	n    int
}

// newRosterHeld returns an empty container, whose capacity is the one the
// declaration fixed.
func newRosterHeld() *rosterHeld {
	return &rosterHeld{buf: make([]Person, rosterHeldFixedCap)}
}

// Cap reports how many elements the container can hold, which does not change.
func (r *rosterHeld) Cap() int { return len(r.buf) }

// Len reports how many elements the container holds, which is never more than
// its capacity.
func (r *rosterHeld) Len() int { return r.n }

// Push adds an element, dropping the oldest one if the buffer is full.
//
// Dropping rather than growing is the point of the type: the newest elements
// are the ones kept, and how much memory that costs was decided when the
// container was made.
func (r *rosterHeld) Push(v Person) {
	r.built()

	if r.n == len(r.buf) {
		r.buf[r.head] = v
		r.head = rosterHeldIndexOf(r.head, 1, len(r.buf))
		return
	}

	r.buf[rosterHeldIndexOf(r.head, r.n, len(r.buf))] = v
	r.n++
}

// All walks the container from the oldest element to the newest.
//
// Which slots the walk covers is fixed when All is called, so pushing during
// one neither lengthens it nor makes it come back round to a slot it has been
// to. What is in a slot is read when the walk reaches it: pushing to a full
// container overwrites the oldest slot, and a walk that has not yet reached
// that slot yields what was written there rather than what it displaced.
//
// Fixing that too would mean copying the elements, which is the one thing a
// container that exists to bound its memory should not do behind a caller's
// back. Walk it, or push to it, or take a copy and do both.
func (r *rosterHeld) All() iter.Seq[Person] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Person) bool) {
		for i := range held {
			if !yield(r.buf[rosterHeldIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// Backward walks the container from the newest element to the oldest. Like All,
// which slots it covers is fixed when it is called.
func (r *rosterHeld) Backward() iter.Seq[Person] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Person) bool) {
		for i := held - 1; i >= 0; i-- {
			if !yield(r.buf[rosterHeldIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them, dropping older ones as it fills.
//
// A sequence longer than the container leaves the last capacity elements of it,
// which is what pushing them one at a time would leave.
func (r *rosterHeld) AppendSeq(seq iter.Seq[Person]) {
	for v := range seq {
		r.Push(v)
	}
}

// Reset empties the container, keeping the buffer it was constructed with.
//
// The capacity is what the container is rather than what it holds, so emptying
// does not give it up: a container that has been reset takes as many elements
// as it did when it was new, and takes them without allocating again.
//
// The elements that were there stay in the buffer until they are pushed over,
// so a container holding the last reference to something large holds it until
// then. Nothing can read them: what a walk covers is the count, and the count
// is what this sets to none.
func (r *rosterHeld) Reset() { r.head, r.n = 0, 0 }

// built stops a container that was never constructed from being added to.
//
// A zero value has no buffer, so it can hold nothing and never will. Under the
// policy that overwrites, adding to one indexes an empty slice and panics on
// its own; under the policy that refuses, it would report the container full —
// which is true and useless, since a caller checking for a full container reads
// that as back-pressure and retries for ever. Saying the same thing both ways
// makes the mistake one answer rather than two.
func (r *rosterHeld) built() {
	if len(r.buf) == 0 {
		panic("forge: this container was never constructed; use the constructor")
	}
}

// rosterHeldIndexOf returns where the element i places after the one at from is kept.
//
// Given the buffer's own head and size it answers for the container as it is;
// given a head a walk took when it started, it answers for the container as it
// was, which is what keeps a walk on the positions it set out to visit.
//
// One subtraction rather than a remainder: i is never more than the number of
// elements held, which is never more than the size, so the sum passes the end
// of the buffer at most once.
func rosterHeldIndexOf(from, i, size int) int {
	if slot := from + i; slot < size {
		return slot
	}
	return from + i - size
}

// Roster satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ json.MarshalerTo = (*Roster)(nil)
)

// Statuses holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type Statuses []Status

// NewStatuses returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewStatuses(elems ...Status) Statuses { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Statuses) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Statuses) All() iter.Seq[Status] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Statuses) Backward() iter.Seq[Status] {
	return func(yield func(Status) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Statuses) AppendSeq(seq iter.Seq[Status]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *Statuses) Reset() { *s = (*s)[:0] }

// The walk's own signature, checked when the package is built.
//
// A method expression is resolved by the compiler and costs nothing at run
// time, where an interface assertion would have to name a value and initialise
// it. What it holds the walk to is the element type of the declaration, so a
// container that walks something else fails here rather than wherever somebody
// ranges over it.
var _ func(*Statuses) iter.Seq[Status] = (*Statuses).All

// CredentialsSeq is a lazy view over the elements of Credentials.
type CredentialsSeq struct {
	Seq[Credential]
}

// Seq returns a lazy view over the elements. Its combinators are the shared
// Seq[Credential] view's.
func (c Credentials) Seq() CredentialsSeq {
	return CredentialsSeq{Seq[Credential](c.All())}
}

// Owners returns the Owner of every element, in order.
func (c Credentials) Owners() []int {
	return c.project(func(v Credential) int {
		return v.Owner
	})
}

// States returns the State of every element, in order.
func (c Credentials) States() []Status {
	return c.project(func(v Credential) Status {
		return v.State
	})
}

// Secrets returns the Secret of every element, in order.
func (c Credentials) Secrets() []*Secret {
	return c.project(func(v Credential) *Secret {
		return v.Secret
	})
}

// SortedByOwner returns the elements ordered by Owner, leaving equal ones as
// they were.
func (c Credentials) SortedByOwner() []Credential {
	return c.ordered(func(v Credential) int {
		return v.Owner
	})
}

// ByOwner returns the elements keyed by Owner, keeping the last of any that
// share one.
func (c Credentials) ByOwner() map[int]Credential {
	return c.keyed(func(v Credential) int {
		return v.Owner
	})
}

// Less reports whether the element at i sorts before the one at j, by Owner. It
// is one of the three sort.Sort takes: the storage answers the length, and Swap
// below is the other. The order is Owner's because it is the one sort key this
// declaration names — one naming several has several orders and no reason to
// prefer any of them, and gets its sorted views without these. Unlike
// SortedByOwner, sorting through this rearranges the collection rather than
// answering with a copy of it in order.
func (c Credentials) Less(i, j int) bool {
	return c[i].Owner < c[j].Owner
}

// Swap exchanges the elements at i and j, which is the last of the three
// sort.Sort takes.
func (c Credentials) Swap(i, j int) {
	c[i], c[j] = c[j], c[i]
}

// project collects one value from every element, in the order the elements come
// in.
//
// The result is grown rather than sized ahead, because what is walked is not
// always something that can be counted first — a walk is all this needs of the
// collection, and needing a length as well would be needing more.
func (c Credentials) project[V any](of func(Credential) V) []V {
	var out []V
	for v := range c.All() {
		out = append(out, of(v))
	}
	return out
}

// keyed returns the elements by the key taken from each of them.
//
// Later wins where two elements share a key, which is what writing into a map
// does and is the only answer that does not need a policy. A key that has to be
// unique is a thing to check, not a thing to discover from which element came
// last.
//
// A key type that holds an interface is a key that can be built and cannot
// always be used: the map panics on a dynamic value that is not comparable,
// exactly as any other map keyed the same way does.
func (c Credentials) keyed[K comparable](by func(Credential) K) map[K]Credential {
	out := make(map[K]Credential)
	for v := range c.All() {
		out[by(v)] = v
	}
	return out
}

// ordered returns the elements sorted by the key taken from each of them,
// leaving equal ones in the order they came in.
//
// A new slice rather than a sort in place: the collection is what it was, and a
// method that quietly reordered it would make asking a question change the
// answer to the next one.
func (c Credentials) ordered[K cmp.Ordered](by func(Credential) K) []Credential {
	out := slices.Collect(c.All())
	slices.SortStableFunc(out, func(a, b Credential) int { return cmp.Compare(by(a), by(b)) })

	return out
}

// Credentials holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type Credentials []Credential

// NewCredentials returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewCredentials(elems ...Credential) Credentials { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Credentials) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Credentials) All() iter.Seq[Credential] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Credentials) Backward() iter.Seq[Credential] {
	return func(yield func(Credential) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Credentials) AppendSeq(seq iter.Seq[Credential]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *Credentials) Reset() { *s = (*s)[:0] }

// MarshalJSONTo writes the container as a JSON array.
//
// One pass over the elements and straight into the encoder. No part of the
// document is assembled anywhere else first, so what it costs to write a
// container is what it costs to write its elements and nothing besides.
func (c Credentials) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}
	for v := range c.All() {
		if err := encodePeopleCredentialJSONTo(enc, v); err != nil {
			return err
		}
	}
	return enc.WriteToken(jsontext.EndArray)
}

// credentialsCounting counts the bytes a writer accepted.
//
// The encoder buffers, so what it has written and what the writer beneath it
// has taken are two numbers. This is the second, which is the one a caller
// copying from the container is entitled to.
type credentialsCounting struct {
	to io.Writer
	n  int64
}

// Write passes the bytes on and counts the ones that were taken.
func (w *credentialsCounting) Write(p []byte) (int, error) {
	n, err := w.to.Write(p)
	w.n += int64(n)
	return n, err
}

// WriteTo writes the container to w as a JSON array, and reports how many bytes
// reached w.
//
// Straight to w rather than into a buffer this then copies, so a container of
// any size costs the encoder's own buffer and no more. The document ends with
// a newline, which is what an encoder leaves between the values of a stream.
func (c Credentials) WriteTo(w io.Writer) (int64, error) {
	counted := credentialsCounting{to: w}
	enc := jsontext.NewEncoder(&counted, jsontext.AllowDuplicateNames(true))
	if err := c.MarshalJSONTo(enc); err != nil {
		return counted.n, err
	}
	return counted.n, nil
}

// UnmarshalJSONFrom reads a JSON array into the container.
//
// What the container held is dropped first, so reading into one twice leaves
// the second document rather than both — which is what reading a document
// into a value means everywhere else. A JSON null empties it and reads
// nothing else: a container is empty or holds elements, so null and an empty
// array are read alike and both are written back as an empty array.
//
// The elements are handed over one at a time as they are read, so the
// document is never held in memory beside the container being filled from
// it.
func (c *Credentials) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if dec.PeekKind() == 'n' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		c.Reset()
		return nil
	}
	if kind := dec.PeekKind(); kind != '[' {
		// A decoder that failed reports no kind at all, and reading is what
		// says why; a document of the wrong shape reads fine and is wrong.
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		return fmt.Errorf("cannot read Credentials from a JSON %s", kind)
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	c.Reset()

	var failed error
	c.AppendSeq(func(yield func(Credential) bool) {
		for dec.PeekKind() != ']' {
			var v Credential
			if err := decodePeopleCredentialJSONFrom(dec, &v); err != nil {
				failed = err
				return
			}
			if !yield(v) {
				return
			}
		}
	})

	if failed != nil {
		return failed
	}
	if kind := dec.PeekKind(); kind != ']' && kind != 0 {
		return errors.New("Credentials stopped taking elements before the JSON array ended")
	}
	_, err := dec.ReadToken()
	return err
}

// ReadFrom reads one JSON array from r into the container, and reports how many
// bytes that array took.
//
// One array rather than everything r holds, because a JSON document ends
// where it ends. The decoder reads r in blocks, so bytes following the array
// may already have been taken out of r and are dropped with it: this reads a
// reader holding one document, and a stream of them is read through a decoder
// that outlives each. A reader holding nothing reports io.EOF.
func (c *Credentials) ReadFrom(r io.Reader) (int64, error) {
	dec := jsontext.NewDecoder(r)
	if err := c.UnmarshalJSONFrom(dec); err != nil {
		return dec.InputOffset(), err
	}
	return dec.InputOffset(), nil
}

// Credentials satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ io.WriterTo          = *new(Credentials)
	_ io.ReaderFrom        = (*Credentials)(nil)
	_ json.MarshalerTo     = *new(Credentials)
	_ json.UnmarshalerFrom = (*Credentials)(nil)
	_ sort.Interface       = *new(Credentials)
)

// And the walk's own signature, checked without calling it.
//
// A method expression is resolved when the package is built and costs nothing
// at run time, where an interface assertion would have to name a value and
// initialise it.
var _ func(*Credentials) iter.Seq[Credential] = (*Credentials).All

// PersonBuilder builds one Person, a field at a time.
//
// Each setter answers with the builder, so the fields may be written in
// whatever order suits the caller and the compiler still checks every one. The
// zero value is a builder holding nothing, so a variable of this type is ready
// without being made.
//
// Build refuses a value whose required fields were never given, and reports
// every one of them rather than the first.
type PersonBuilder struct {
	// held is the value being built, which every setter writes one field of.
	held Person

	// given records which of the required fields have been given, in the order
	// Build reports them: Name, Email.
	//
	// Recorded rather than read off the value, because a field given the zero
	// value was still given: a caller who set it meant to, and whether the zero
	// value will do is a rule rather than an omission.
	given [2]bool
}

// NewPersonBuilder returns a builder for one Person.
func NewPersonBuilder() *PersonBuilder { return &PersonBuilder{} }

// ID sets the ID of the Person being built.
func (b *PersonBuilder) ID(v int) *PersonBuilder {
	b.held.ID = v
	return b
}

// Name sets the Name of the Person being built.
func (b *PersonBuilder) Name(v string) *PersonBuilder {
	b.held.Name = v
	b.given[0] = true
	return b
}

// Email sets the Email of the Person being built.
func (b *PersonBuilder) Email(v string) *PersonBuilder {
	b.held.Email = v
	b.given[1] = true
	return b
}

// Age sets the Age of the Person being built.
func (b *PersonBuilder) Age(v int) *PersonBuilder {
	b.held.Age = v
	return b
}

// Aliases sets the Aliases of the Person being built.
func (b *PersonBuilder) Aliases(v []string) *PersonBuilder {
	b.held.Aliases = v
	return b
}

// Build returns the Person that was built.
//
// A field the author tagged as one a value has to carry, and whose setter was
// never called, is reported rather than left at its zero. Every one of them
// rather than the first, because a caller filling in a form wants the whole
// list.
//
// What was given is not checked here. A caller who set a field has set it, and
// whether what they set is any good is what the rules on the field say — which
// is a different question, asked somewhere a rule added to the tag reaches.
func (b *PersonBuilder) Build() (Person, error) {
	var failed ValidationErrors

	if !b.given[0] {
		failed = append(failed, ValidationError{Path: "Name", Rule: "required", Want: "a value"})
	}
	if !b.given[1] {
		failed = append(failed, ValidationError{Path: "Email", Rule: "required", Want: "a value"})
	}

	if len(failed) > 0 {
		var zero Person
		return zero, failed
	}
	return b.held, nil
}

// clonePerson returns a copy of v that shares nothing with it.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func clonePerson(v Person) Person {
	return v.Clone()
}

// Clone returns a copy of the Person that shares nothing with it.
//
// Everything reachable is copied, so what is done to the copy is invisible in
// the original and the other way round. The copy starts as an assignment, which
// is already the whole of it for a field holding a number, a string or anything
// else made only of those; what follows is the fields for which an assignment
// would have copied a reference rather than what it refers to.
func (v Person) Clone() Person {
	out := v

	out.Aliases = slices.Clone(v.Aliases)
	return out
}

// String returns the subject as the display tags on its fields ask for it.
//
// The fields in the order they were written, separated by a space, each
// labelled where its tag gave it a name. It is a rendering for a person to
// read rather than a format anything should parse: nothing here escapes a
// separator that turns up inside a value, because a reader can see what
// happened and a parser was never the point.
func (v Person) String() string {
	var b strings.Builder

	b.WriteString(v.Name)

	b.WriteString(" ")
	b.WriteString("age=")
	b.WriteString(strconv.FormatInt(int64(v.Age), 10))

	return b.String()
}

// String returns what this member is called.
//
// A value nobody declared renders as the type and the value it holds, rather
// than as one of the members. It is not one, and a rendering that said
// otherwise would let an undeclared value travel through a log and a document
// with nothing saying where it came from.
func (v Status) String() string {
	switch v {
	case StatusPending:
		return "pending"
	case StatusActive:
		return "active"
	case StatusRevoked:
		return "revoked"
	}
	return "Status(" + strconv.FormatInt(int64(v), 10) + ")"
}

// Valid reports whether this is a member of the set.
//
// Worth asking, because a value of the type is not necessarily one of them: the
// type is the whole range of whatever it is a name for, and the set is the
// constants declared of it. A number off a wire, out of a database, or cast
// from an integer is a value nobody declared, and there is no zero to compare
// against — for a set counted from iota the zero is an ordinary member.
func (v Status) Valid() bool {
	switch v {
	case StatusPending,
		StatusActive,
		StatusRevoked:
		return true
	}
	return false
}

// ValuesStatus returns every member, in the order they were declared.
//
// Declaration order rather than sorted, because that is the order the constant
// block reads in and the order a run counted by iota means. A fresh slice each
// call, so that a caller sorting or appending to what they were given does not
// change what the next one is given.
func ValuesStatus() []Status {
	return []Status{
		StatusPending,
		StatusActive,
		StatusRevoked,
	}
}

// ParseStatus returns the member with this name.
//
// Every name a member has, which for a set with two names for one value is both
// of them: aliasing is what a package does while a name is being changed, and a
// reader that took only the new one would break every caller the moment the old
// one was added.
func ParseStatus(s string) (Status, error) {
	switch s {
	case "pending":
		return StatusPending, nil
	case "active":
		return StatusActive, nil
	case "revoked":
		return StatusRevoked, nil
	}

	var zero Status
	return zero, errors.New(strconv.Quote(s) + " is not a member of Status")
}

// MarshalText returns the member's name as text.
//
// The same text String renders, because a closed set has one spelling and two
// would be a value that read one way and travelled another. It is also what a
// JSON codec reaches for when the type has none of its own, so the member goes
// over the wire under the name it is known by rather than as the number behind
// it.
//
// A value nobody declared is refused rather than written. String renders one as
// the type and the value it holds, which is what a log wants and is nothing a
// reader could take back — so letting it onto a wire would be writing a
// document that cannot be read, and the zero of a set whose members start
// elsewhere is exactly such a value.
func (v Status) MarshalText() ([]byte, error) {
	if !v.Valid() {
		return nil, errors.New(v.String() + " is not a member of Status")
	}

	return []byte(v.String()), nil
}

// AppendText writes the member's name onto the end of a buffer.
//
// What MarshalText does without the slice it has to allocate, for a caller who
// owns the buffer already. encoding/json reaches for this in preference where a
// type has it, so it refuses what that refuses: a value nobody declared, which
// the two would otherwise disagree about depending on which the codec happened
// to call.
func (v Status) AppendText(b []byte) ([]byte, error) {
	if !v.Valid() {
		return nil, errors.New(v.String() + " is not a member of Status")
	}

	return append(b, v.String()...), nil
}

// UnmarshalText reads a member back from its name.
//
// A name nobody declared is an error rather than a zero value. The zero of a
// set counted from iota is an ordinary member, so decoding an unknown name into
// it would turn a typo in a document into a value the receiver treats as meant
// — which is the failure a closed set exists to prevent.
func (v *Status) UnmarshalText(b []byte) error {
	held, err := ParseStatus(string(b))
	if err != nil {
		return err
	}

	*v = held
	return nil
}

// nestedValidation folds what a field's own check reported into the failures of
// the value that holds it, under the path that reaches the field.
//
// The path is what makes a nested check worth having. A City that is too short
// is reported by Address as "City", and the value holding the address has to
// say "Address.City" or a caller has no way to know which of two addresses it
// was.
//
// An error that is not a list of failures is carried whole, under the field's
// own path. That is what a check the author wrote returns, and what a type from
// somewhere else returns, and neither is this package's to take apart.
//
// Found through the chain rather than in the hand, so that failures wrapped by
// a check of somebody's own still reach the caller as failures with paths. A
// wrapper that meant to hide them can say so by not wrapping them.
func nestedValidation(into ValidationErrors, at string, err error) ValidationErrors {
	var held ValidationErrors
	if !errors.As(err, &held) {
		return append(into, ValidationError{Path: at, Cause: err})
	}

	for _, one := range held {
		one.Path = at + "." + one.Path
		into = append(into, one)
	}
	return into
}

// ValidationError is one rule a value did not satisfy.
//
// It carries where rather than only what. A form with a bad postcode is not a
// form that is invalid; it is a form whose Address.Postcode is too short, and
// the difference is whether the caller can put the message beside the field it
// is about.
type ValidationError struct {
	// Path reaches the field from the value that was checked: "Email", or
	// "Address.City" for a field inside another struct.
	Path string

	// Rule is the rule that was not met, written as it was written in the tag,
	// so that the failure and the source read alike. It is empty for a failure
	// that came from a check the author wrote themselves.
	Rule string

	// Want says what the rule wanted, in words, so that a message can be shown
	// to somebody who has never seen the tag.
	Want string

	// Cause is what a check the author wrote returned. It is nil for a failure
	// of a rule, which has nothing underneath it.
	Cause error
}

// Error describes the failure, naming the field first.
func (e ValidationError) Error() string {
	switch {
	case e.Cause != nil:
		return e.Path + ": " + e.Cause.Error()
	case e.Want != "":
		return e.Path + ": " + e.Rule + " wants " + e.Want
	default:
		return e.Path + ": " + e.Rule
	}
}

// Unwrap returns what a check the author wrote returned, so that errors.Is and
// errors.As reach it.
func (e ValidationError) Unwrap() error { return e.Cause }

// ValidationErrors is every rule a value did not satisfy, in the order the
// fields are declared and the rules are written.
//
// Every failure rather than the first, because a caller showing a form to
// somebody wants to show them everything that is wrong with it at once.
type ValidationErrors []ValidationError

// Error describes every failure, one per line where there is more than one.
//
// A line each rather than a sentence joined by commas: the failures are about
// different fields, and a reader scanning for their own field finds it faster
// down the left edge than in the middle of a paragraph.
func (e ValidationErrors) Error() string {
	switch len(e) {
	case 0:
		// Nothing failed, which is not a state a caller reaches through this:
		// a check that found nothing wrong returns no error at all rather than
		// an empty list of them.
		return "nothing failed"
	case 1:
		return e[0].Error()
	}

	var out strings.Builder
	out.WriteString(strconv.Itoa(len(e)))
	out.WriteString(" failures:")

	for _, one := range e {
		out.WriteString("\n\t")
		out.WriteString(one.Error())
	}
	return out.String()
}

// Unwrap returns the failures as errors, so that errors.Is and errors.As reach
// each of them.
func (e ValidationErrors) Unwrap() []error {
	out := make([]error, len(e))
	for i, one := range e {
		out[i] = one
	}
	return out
}

// hashPerson returns a content hash of v.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func hashPerson(v Person) uint64 {
	return v.Hash()
}

// Hash returns a content hash of the Person.
//
// Two values that are the same all the way down hash to the same number,
// in this process and in every other, on any machine and in any build. Two
// that differ almost certainly do not: this is a hash rather than an
// identity, so a caller who cannot afford a collision compares as well.
//
// It allocates nothing, which is what makes it affordable to take on every
// lookup rather than once and cache.
func (v Person) Hash() uint64 {
	h := fnvSeed
	h = fnvUint64(h, uint64(v.ID))
	h = fnvString(h, string(v.Name))
	h = fnvString(h, string(v.Email))
	h = fnvUint64(h, uint64(v.Age))
	h = fnvBool(h, v.Aliases != nil)
	h = fnvUint64(h, uint64(len(v.Aliases)))
	for _, one := range v.Aliases {
		h = fnvString(h, string(one))
	}
	return h
}

// The two numbers FNV-1a is made of: what an empty stream hashes to, and the
// multiplier each byte is mixed with.
//
// Written out rather than taken from hash/fnv. That package answers through an
// interface, so a hash taken through it allocates and is called rather than
// inlined — and what is wanted here is arithmetic in the middle of a method,
// not an object with a lifetime.
const (
	fnvSeed  uint64 = 14695981039346656037
	fnvPrime uint64 = 1099511628211
)

// fnvUint64 mixes a whole number into a hash, eight bytes at a time.
//
// Eight whatever the number was declared as, so that a value held in an int
// hashes the same where an int is four bytes and where it is eight. A number
// that hashed differently depending on the machine would not be a stable
// identity, which is the only thing this is for.
func fnvUint64(h, v uint64) uint64 {
	for range 8 {
		h = (h ^ (v & 0xff)) * fnvPrime
		v >>= 8
	}
	return h
}

// fnvString mixes a string's length and then its bytes.
//
// The length as well as the bytes, because the bytes alone do not say where one
// string ended and the next began: "ab" beside "c" and "a" beside "bc" are the
// same five bytes in the same order and are not the same pair of values.
func fnvString(h uint64, s string) uint64 {
	h = fnvUint64(h, uint64(len(s)))
	for i := range len(s) {
		h = (h ^ uint64(s[i])) * fnvPrime
	}
	return h
}

// fnvBool mixes the one byte a boolean is worth.
func fnvBool(h uint64, b bool) uint64 {
	if b {
		return (h ^ 1) * fnvPrime
	}
	return h * fnvPrime
}

// fnvFloat mixes a floating-point number by its bits, with the two values
// whose bits are not a function of the number written down first.
//
// Zero is one number with two spellings, since the sign bit is free, and a hash
// taken straight off the bits would give positive and negative zero two answers
// though they compare equal. Not-a-number is the opposite case: it is many bit
// patterns, no one of which equals any other or even itself, so no answer
// agrees with comparison and the least surprising one is that they all hash
// alike.
func fnvFloat(h uint64, f float64) uint64 {
	switch {
	case math.IsNaN(f):
		return fnvUint64(h, fnvNaN)
	case f == 0:
		return fnvUint64(h, 0)
	default:
		return fnvUint64(h, math.Float64bits(f))
	}
}

// fnvNaN is what every not-a-number hashes as. A constant of this file rather
// than the bits of math.NaN, so that what a value hashes to is decided here and
// cannot move under a library release.
const fnvNaN uint64 = 0x7ff8000000000001

// The member names this codec writes, quoted once here rather than on
// every call. A name is the same bytes every time, and quoting it is a
// scan the generator has already done.
var (
	peopleCredentialJSONNameOwner  = jsontext.Value("\"Owner\"")
	peopleCredentialJSONNameState  = jsontext.Value("\"State\"")
	peopleCredentialJSONNameSecret = jsontext.Value("\"Secret\"")
)

// encodePeopleCredentialJSONTo writes a Credential as JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func encodePeopleCredentialJSONTo(enc *jsontext.Encoder, v Credential) error {
	return v.MarshalJSONTo(enc)
}

// MarshalJSONTo writes the Credential as a JSON object.
//
// Members are written in the order the fields are declared, an embedded
// struct's where the embedded field is. A field that takes a name from a
// shallower one keeps its own place rather than the excluded one's.
func (v Credential) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteValue(peopleCredentialJSONNameOwner); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.Int(int64(v.Owner))); err != nil {
		return err
	}
	if err := enc.WriteValue(peopleCredentialJSONNameState); err != nil {
		return err
	}
	{
		held := v.State
		text, err := held.MarshalText()
		if err != nil {
			return err
		}
		if err := enc.WriteToken(jsontext.String(string(text))); err != nil {
			return err
		}
	}
	if err := enc.WriteValue(peopleCredentialJSONNameSecret); err != nil {
		return err
	}
	if v.Secret == nil {
		if err := enc.WriteToken(jsontext.Null); err != nil {
			return err
		}
	} else {
		if err := encodePeopleSecretJSONTo(enc, (*v.Secret)); err != nil {
			return err
		}
	}
	return enc.WriteToken(jsontext.EndObject)
}

// decodePeopleCredentialJSONFrom reads a Credential from JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func decodePeopleCredentialJSONFrom(dec *jsontext.Decoder, v *Credential) error {
	return v.UnmarshalJSONFrom(dec)
}

// UnmarshalJSONFrom reads a JSON object into the Credential.
//
// A member the object holds and the type does not is skipped, which is
// what keeps a reader working against a writer that has since added one.
func (v *Credential) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if dec.PeekKind() == 'n' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		var zero Credential
		*v = zero
		return nil
	}
	if kind := dec.PeekKind(); kind != '{' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		return fmt.Errorf("cannot read Credential from a JSON %s", kind)
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		name, err := dec.ReadToken()
		if err != nil {
			return err
		}
		switch name.String() {
		case "Owner":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero int
					v.Owner = zero
				case '0':
					number, err := raw.Int()
					if err != nil {
						return err
					}
					if int64(int(number)) != number {
						return fmt.Errorf("%d is out of range for int", number)
					}
					v.Owner = int(number)
				default:
					return fmt.Errorf("cannot read int from a JSON %s", raw.Kind())
				}
			}
		case "State":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero Status
					v.State = zero
				case '"':
					if err := v.State.UnmarshalText([]byte(raw.String())); err != nil {
						return err
					}
				default:
					return fmt.Errorf("cannot read Status from a JSON %s", raw.Kind())
				}
			}
		case "Secret":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				v.Secret = nil
			} else {
				var held Secret
				if err := decodePeopleSecretJSONFrom(dec, &held); err != nil {
					return err
				}
				v.Secret = &held
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	_, err := dec.ReadToken()
	return err
}

// The member names this codec writes, quoted once here rather than on
// every call. A name is the same bytes every time, and quoting it is a
// scan the generator has already done.
var (
	peoplePersonJSONNameID      = jsontext.Value("\"ID\"")
	peoplePersonJSONNameName    = jsontext.Value("\"Name\"")
	peoplePersonJSONNameEmail   = jsontext.Value("\"Email\"")
	peoplePersonJSONNameAge     = jsontext.Value("\"Age\"")
	peoplePersonJSONNameAliases = jsontext.Value("\"Aliases\"")
)

// encodePeoplePersonJSONTo writes a Person as JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func encodePeoplePersonJSONTo(enc *jsontext.Encoder, v Person) error {
	return v.MarshalJSONTo(enc)
}

// MarshalJSONTo writes the Person as a JSON object.
//
// Members are written in the order the fields are declared, an embedded
// struct's where the embedded field is. A field that takes a name from a
// shallower one keeps its own place rather than the excluded one's.
func (v Person) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteValue(peoplePersonJSONNameID); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.Int(int64(v.ID))); err != nil {
		return err
	}
	if err := enc.WriteValue(peoplePersonJSONNameName); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(string(v.Name))); err != nil {
		return err
	}
	if err := enc.WriteValue(peoplePersonJSONNameEmail); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(string(v.Email))); err != nil {
		return err
	}
	if err := enc.WriteValue(peoplePersonJSONNameAge); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.Int(int64(v.Age))); err != nil {
		return err
	}
	if err := enc.WriteValue(peoplePersonJSONNameAliases); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}
	for _, one := range v.Aliases {
		if err := enc.WriteToken(jsontext.String(string(one))); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndArray); err != nil {
		return err
	}
	return enc.WriteToken(jsontext.EndObject)
}

// decodePeoplePersonJSONFrom reads a Person from JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func decodePeoplePersonJSONFrom(dec *jsontext.Decoder, v *Person) error {
	return v.UnmarshalJSONFrom(dec)
}

// UnmarshalJSONFrom reads a JSON object into the Person.
//
// A member the object holds and the type does not is skipped, which is
// what keeps a reader working against a writer that has since added one.
func (v *Person) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if dec.PeekKind() == 'n' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		var zero Person
		*v = zero
		return nil
	}
	if kind := dec.PeekKind(); kind != '{' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		return fmt.Errorf("cannot read Person from a JSON %s", kind)
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		name, err := dec.ReadToken()
		if err != nil {
			return err
		}
		switch name.String() {
		case "ID":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero int
					v.ID = zero
				case '0':
					number, err := raw.Int()
					if err != nil {
						return err
					}
					if int64(int(number)) != number {
						return fmt.Errorf("%d is out of range for int", number)
					}
					v.ID = int(number)
				default:
					return fmt.Errorf("cannot read int from a JSON %s", raw.Kind())
				}
			}
		case "Name":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero string
					v.Name = zero
				case '"':
					v.Name = string(raw.String())
				default:
					return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
				}
			}
		case "Email":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero string
					v.Email = zero
				case '"':
					v.Email = string(raw.String())
				default:
					return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
				}
			}
		case "Age":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero int
					v.Age = zero
				case '0':
					number, err := raw.Int()
					if err != nil {
						return err
					}
					if int64(int(number)) != number {
						return fmt.Errorf("%d is out of range for int", number)
					}
					v.Age = int(number)
				default:
					return fmt.Errorf("cannot read int from a JSON %s", raw.Kind())
				}
			}
		case "Aliases":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				v.Aliases = nil
			} else {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				out := v.Aliases[:0]
				for dec.PeekKind() != ']' {
					var one string
					{
						raw, err := dec.ReadToken()
						if err != nil {
							return err
						}
						switch raw.Kind() {
						case 'n':
							var zero string
							one = zero
						case '"':
							one = string(raw.String())
						default:
							return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
						}
					}
					out = append(out, one)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				if out == nil {
					out = []string{}
				}
				v.Aliases = out
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	_, err := dec.ReadToken()
	return err
}

// The member names this codec writes, quoted once here rather than on
// every call. A name is the same bytes every time, and quoting it is a
// scan the generator has already done.
var (
	peopleSecretJSONNameIssued = jsontext.Value("\"Issued\"")
	peopleSecretJSONNameToken  = jsontext.Value("\"Token\"")
)

// encodePeopleSecretJSONTo writes a Secret as JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func encodePeopleSecretJSONTo(enc *jsontext.Encoder, v Secret) error {
	return v.MarshalJSONTo(enc)
}

// MarshalJSONTo writes the Secret as a JSON object.
//
// Members are written in the order the fields are declared, an embedded
// struct's where the embedded field is. A field that takes a name from a
// shallower one keeps its own place rather than the excluded one's.
func (v Secret) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteValue(peopleSecretJSONNameIssued); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(string(v.Issued))); err != nil {
		return err
	}
	if err := enc.WriteValue(peopleSecretJSONNameToken); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(string(v.Token))); err != nil {
		return err
	}
	return enc.WriteToken(jsontext.EndObject)
}

// decodePeopleSecretJSONFrom reads a Secret from JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func decodePeopleSecretJSONFrom(dec *jsontext.Decoder, v *Secret) error {
	return v.UnmarshalJSONFrom(dec)
}

// UnmarshalJSONFrom reads a JSON object into the Secret.
//
// A member the object holds and the type does not is skipped, which is
// what keeps a reader working against a writer that has since added one.
func (v *Secret) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if dec.PeekKind() == 'n' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		var zero Secret
		*v = zero
		return nil
	}
	if kind := dec.PeekKind(); kind != '{' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		return fmt.Errorf("cannot read Secret from a JSON %s", kind)
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		name, err := dec.ReadToken()
		if err != nil {
			return err
		}
		switch name.String() {
		case "Issued":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero string
					v.Issued = zero
				case '"':
					v.Issued = string(raw.String())
				default:
					return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
				}
			}
		case "Token":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero string
					v.Token = zero
				case '"':
					v.Token = string(raw.String())
				default:
					return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
				}
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	_, err := dec.ReadToken()
	return err
}

// LogValue returns the subject as it may be logged.
//
// Every exported field, with the ones tagged redact replaced by a fixed
// string. Fixed rather than shortened or starred: a length is something,
// a prefix is more, and a field marked as not for logs was marked by
// somebody who did not want to work out which of those is safe.
//
// Implementing this is what takes the field out of a log. slog reaches for
// a value's fields when the value does not say otherwise, so a type with a
// secret in it and no LogValue prints the secret.
func (v Person) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Int64("ID", int64(v.ID)),
		slog.String("Name", v.Name),
		slog.String("Email", "[redacted]"),
		slog.Int64("Age", int64(v.Age)),
		slog.Any("Aliases", v.Aliases),
	)
}

// PersonPatch is a partial Person: the fields it is asked to change, and
// nothing about the rest.
//
// Each field is a pointer because a pointer is how Go says there is something
// here about a value that has a zero. A nil one is a field the patch was not
// asked about; one pointing at the zero value is a field it was asked to clear,
// and those are different instructions.
type PersonPatch struct {
	// ID is what to set the ID to, and is nil where the patch says nothing about
	// it.
	ID *int `validate:"min=1"`

	// Name is what to set the Name to, and is nil where the patch says nothing
	// about it.
	Name *string `validate:"required,max=64" display:""`

	// Email is what to set the Email to, and is nil where the patch says nothing
	// about it.
	Email *string `validate:"required,regexp=^[^@[:space:]]+@[^@[:space:]]+$" redact:""`

	// Age is what to set the Age to, and is nil where the patch says nothing about
	// it.
	Age *int `validate:"min=0,max=150" display:"age"`

	// Aliases is what to set the Aliases to, and is nil where the patch says
	// nothing about it.
	Aliases *[]string
}

// Apply writes the fields the patch sets over the Person given, and leaves the
// rest as they were.
//
// It replaces rather than merges: a field holding a slice becomes that slice
// rather than gaining its elements, and one holding a struct becomes that
// struct rather than being patched inside. A partial update of a value inside
// another is a patch for that value.
//
// Nothing is checked here. Whether what the patch holds is something the rules
// would accept is a question about the whole value, and the whole value exists
// only once this has run.
//
// Nothing is copied either. A field holding a slice, a map or a pointer leaves
// the value sharing it with whatever filled the patch in, so a patch applied
// twice gives two values that share, and writing through what was put into the
// patch writes into both. Where that matters, copy before applying.
func (p PersonPatch) Apply(into *Person) {
	if p.ID != nil {
		into.ID = *p.ID
	}
	if p.Name != nil {
		into.Name = *p.Name
	}
	if p.Email != nil {
		into.Email = *p.Email
	}
	if p.Age != nil {
		into.Age = *p.Age
	}
	if p.Aliases != nil {
		into.Aliases = *p.Aliases
	}
}

// IsZero reports that the patch sets no field, which is a patch nobody asked
// for anything by.
//
// It is also the name a codec looks for: a member of a struct tagged omitzero
// is left out when its value says it is zero, so a patch held as a field of
// something larger goes over the wire as nothing rather than as an object of
// absent members. A patch that is the whole document is written out in full
// either way, since there is no member for the tag to be on.
func (p PersonPatch) IsZero() bool {
	return p.ID == nil &&
		p.Name == nil &&
		p.Email == nil &&
		p.Age == nil &&
		p.Aliases == nil
}

// LogValue returns Credential as it may be logged.
//
// Implementing this is what keeps a field out of a log. slog reaches for a
// value's fields when the value does not say otherwise, so a type with a secret
// in it and no LogValue prints the secret. A handler can be given a hook that
// rewrites attributes, but that is a property of the handler rather than of the
// type, and every place the value is logged from has to have installed it.
func (v Credential) LogValue() slog.Value {
	secretLogged := slog.AnyValue(nil)
	if v.Secret != nil {
		secretLogged = v.Secret.LogValue()
	}

	return slog.GroupValue(
		slog.Int64("Owner", int64(v.Owner)),
		slog.Any("State", v.State),
		slog.Attr{Key: "Secret", Value: secretLogged},
	)
}

// LogValue returns Secret as it may be logged.
//
// Every exported field, with the one tagged redact replaced by a fixed string.
// Fixed rather than shortened or starred: a length is something, a prefix is
// more, and two records holding one secret are told apart by any hash of it.
//
// Implementing this is what keeps a field out of a log. slog reaches for a
// value's fields when the value does not say otherwise, so a type with a secret
// in it and no LogValue prints the secret. A handler can be given a hook that
// rewrites attributes, but that is a property of the handler rather than of the
// type, and every place the value is logged from has to have installed it.
func (v Secret) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("Issued", v.Issued),
		slog.String("Token", "[redacted]"),
	)
}

// patternPersonEmail is the pattern Email is checked against.
//
// Compiled when the package loads rather than at each check: compiling a
// pattern costs many times what matching against one does, and the pattern
// is the same every time because it was written in the source.
var patternPersonEmail = regexp.MustCompile("^[^@[:space:]]+@[^@[:space:]]+$")

// validatePerson reports every rule v does not satisfy.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func validatePerson(v Person) error {
	return v.Validate()
}

// Validate reports every rule the Person does not satisfy, and nothing when it
// satisfies them all.
//
// Every failure rather than the first, because a value with three things
// wrong is not three round trips. Nothing is allocated until something
// fails, so a value that is in order costs the comparisons and no memory.
func (v Person) Validate() error {
	var failed ValidationErrors

	if v.ID < 1 {
		failed = append(failed, ValidationError{Path: "ID", Rule: "min=1", Want: "at least 1"})
	}
	switch {
	case v.Name == "":
		failed = append(failed, ValidationError{Path: "Name", Rule: "required", Want: "a value"})
	case len(v.Name) > 64:
		failed = append(failed, ValidationError{Path: "Name", Rule: "max=64", Want: "at most 64 characters"})
	}
	switch {
	case v.Email == "":
		failed = append(failed, ValidationError{Path: "Email", Rule: "required", Want: "a value"})
	case !patternPersonEmail.MatchString(string(v.Email)):
		failed = append(failed, ValidationError{Path: "Email", Rule: "regexp=^[^@[:space:]]+@[^@[:space:]]+$", Want: "a value matching ^[^@[:space:]]+@[^@[:space:]]+$"})
	}
	switch {
	case v.Age < 0:
		failed = append(failed, ValidationError{Path: "Age", Rule: "min=0", Want: "at least 0"})
	case v.Age > 150:
		failed = append(failed, ValidationError{Path: "Age", Rule: "max=150", Want: "at most 150"})
	}
	if len(failed) == 0 {
		return nil
	}
	return failed
}

// Seq is a lazy view over a sequence of elements.
//
// Every operation on it is lazy: it returns another view and walks nothing. The
// walk happens once, when a terminal asks for it, and each element passes
// through the whole chain before the next one is read — so a chain over a
// million elements holds one of them at a time and allocates nothing per
// element. A chain costs a few allocations per link to build and to start, and
// that is the whole of what it costs: the same over a million elements as over
// ten.
//
// The zero view yields nothing through every method here, so one that was never
// given a sequence behaves like an empty one. Ranging over it directly is
// ranging over a function that is not there, which panics like any other nil
// call — All is what guards that, and is what to range over.
type Seq[U any] iter.Seq[U]

// All returns the view as an ordinary sequence, which is what everything taking
// an iter.Seq wants and what a range loop should read.
//
// It is also where the zero view is made safe. A view is a function underneath,
// so one that was never given a sequence is a nil function and ranging over it
// panics; this hands back an empty sequence instead, and every method below
// walks through here rather than over the view directly.
func (s Seq[U]) All() iter.Seq[U] {
	if s == nil {
		return func(func(U) bool) {}
	}
	return iter.Seq[U](s)
}

// Filter returns a view of the elements the predicate keeps.
func (s Seq[U]) Filter(keep func(U) bool) Seq[U] {
	return func(yield func(U) bool) {
		for v := range s.All() {
			if keep(v) && !yield(v) {
				return
			}
		}
	}
}

// Map returns a view of what the function makes of each element.
//
// Genuinely generic in its result, so a chain that changes type keeps chaining:
// the view a projection returns is a view like any other, and the combinators
// on it are these same ones rather than a second set written for the new type.
func (s Seq[U]) Map[V any](to func(U) V) Seq[V] {
	return func(yield func(V) bool) {
		for v := range s.All() {
			if !yield(to(v)) {
				return
			}
		}
	}
}

// Take returns a view of at most the first n elements, and of none for an n
// that is not positive.
//
// It stops the walk beneath it rather than reading on and discarding, which is
// what makes taking ten from a very long sequence cost ten.
func (s Seq[U]) Take(n int) Seq[U] {
	return func(yield func(U) bool) {
		if n <= 0 {
			return
		}

		left := n
		for v := range s.All() {
			if !yield(v) {
				return
			}

			left--
			if left == 0 {
				return
			}
		}
	}
}

// Skip returns a view of everything after the first n elements, and of
// everything for an n that is not positive.
func (s Seq[U]) Skip(n int) Seq[U] {
	return func(yield func(U) bool) {
		left := n
		for v := range s.All() {
			if left > 0 {
				left--
				continue
			}
			if !yield(v) {
				return
			}
		}
	}
}

// Dedup returns a view with runs of equal elements collapsed to their first.
//
// Adjacent elements only, which is the whole of what a lazy operation can do:
// dropping every repeat wherever it appears means remembering everything seen
// so far, and a view that grew a set as it walked would not be a view any more.
// Sort or group first if that is what is wanted.
//
// Each element is compared against the last one that was *yielded* rather than
// against the one immediately before it, so a run collapses to its first
// element however long it is. The two are the same thing for an equality, and
// differ for a comparison that is not one — a nearness test over 1, 2, 3 keeps
// 1 and 3 here, where comparing neighbours would keep only 1. The first
// argument is the element that was kept and the second the one being offered.
func (s Seq[U]) Dedup(same func(a, b U) bool) Seq[U] {
	return func(yield func(U) bool) {
		var last U
		seen := false

		for v := range s.All() {
			if seen && same(last, v) {
				continue
			}

			last, seen = v, true
			if !yield(v) {
				return
			}
		}
	}
}

// Chunk yields slices of n elements, the last of them shorter if the sequence
// does not divide evenly. It panics for an n below one, which asks for
// something there is no answer to.
//
// Each chunk is a slice of its own rather than one buffer handed out again and
// again. Reusing it would allocate less and would make a chunk kept past the
// next one silently become that one — a bug that shows up as data from the
// wrong batch, far from here. The cost is one allocation per chunk, which is
// still none per element.
//
// A plain sequence rather than another view, and that one is the language's.
// A method of this type returning a view of slices means the type mentioning
// itself over a bigger type than it was given, and the method set of that one
// mentioning a bigger one again, without end; the compiler calls it an
// instantiation cycle and refuses the file. A function beside the type could
// return one — the cycle is a property of method sets — at the price of a name
// in this package that everything else here keeps inside the view. Chunks are
// usually ranged over, which this is, and converting what it yields to a view
// of slices is the whole of the difference when they are not.
func (s Seq[U]) Chunk(n int) iter.Seq[[]U] {
	if n < 1 {
		panic("forge: Chunk of fewer than one element")
	}

	return func(yield func([]U) bool) {
		// Built on the first element that goes into it rather than ahead of
		// one, so a sequence that ends on a boundary does not pay for a batch
		// nothing is put in.
		var batch []U

		for v := range s.All() {
			if batch == nil {
				batch = make([]U, 0, n)
			}
			if batch = append(batch, v); len(batch) < n {
				continue
			}
			if !yield(batch) {
				return
			}
			batch = nil
		}

		if len(batch) > 0 {
			yield(batch)
		}
	}
}

// Collect walks the view and returns everything it yields.
func (s Seq[U]) Collect() []U { return slices.Collect(s.All()) }

// Into appends everything the view yields to a slice and returns it.
//
// It is Collect for a caller who owns the memory: passing a slice kept between
// calls turns the one allocation Collect makes into none.
func (s Seq[U]) Into(dst []U) []U { return slices.AppendSeq(dst, s.All()) }

// First returns the first element the view yields, and whether it yielded one.
// The walk stops there, so first-of-a-filter over a long sequence costs the
// elements up to the match and no more.
func (s Seq[U]) First() (U, bool) {
	for v := range s.All() {
		return v, true
	}

	var none U
	return none, false
}

// Reduce combines the elements into a single value, left to right.
//
// Generic in what it builds rather than in the element alone, so a sequence of
// values reduces to a count, a total or a map without being projected first.
func (s Seq[U]) Reduce[A any](initial A, combine func(A, U) A) A {
	out := initial
	for v := range s.All() {
		out = combine(out, v)
	}
	return out
}

// Person satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ json.MarshalerTo     = *new(Person)
	_ json.UnmarshalerFrom = (*Person)(nil)
	_ fmt.Stringer         = *new(Person)
	_ slog.LogValuer       = *new(Person)
)

// Status satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ fmt.Stringer             = *new(Status)
	_ encoding.TextAppender    = *new(Status)
	_ encoding.TextMarshaler   = *new(Status)
	_ encoding.TextUnmarshaler = (*Status)(nil)
)

// Credential satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ json.MarshalerTo     = *new(Credential)
	_ json.UnmarshalerFrom = (*Credential)(nil)
	_ slog.LogValuer       = *new(Credential)
)
