// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge (devel)
// go go1.27.1
// inputs 9072330789e4797c

//go:build forgespec

package people

import (
	"cmp"
	"encoding"
	"encoding/json/v2"
	"errors"
	"fmt"
	"io"
	"iter"
	"log/slog"
	"regexp"
	"sort"
	"sync"
)

type PersonsSeq struct {
	Seq[Person]
}

func (c Persons) Seq() PersonsSeq {
	panic("forge stub")
}

func (c Persons) IDs() []int {
	panic("forge stub")
}

func (c Persons) Names() []string {
	panic("forge stub")
}

func (c Persons) Emails() []string {
	panic("forge stub")
}

func (c Persons) Ages() []int {
	panic("forge stub")
}

func (c Persons) Aliases() [][]string {
	panic("forge stub")
}

func (c Persons) SortedByName() []Person {
	panic("forge stub")
}

func (c Persons) SortedByAge() []Person {
	panic("forge stub")
}

func (c Persons) ByID() map[int]Person {
	panic("forge stub")
}

func (c Persons) project[V any](of func(Person) V) []V { panic("forge stub") }

func (c Persons) keyed[K comparable](by func(Person) K) map[K]Person { panic("forge stub") }

func (c Persons) ordered[K cmp.Ordered](by func(Person) K) []Person { panic("forge stub") }

func NewPersons(elems ...Person) Persons { panic("forge stub") }

func (s Persons) Len() int { panic("forge stub") }

func (s Persons) All() iter.Seq[Person] { panic("forge stub") }

func (s Persons) Backward() iter.Seq[Person] { panic("forge stub") }

func (s *Persons) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (s *Persons) Reset() { panic("forge stub") }

var _ func(*Persons) iter.Seq[Person] = (*Persons).All

type RecentSeq struct {
	Seq[Person]
}

func (c Recent) Seq() RecentSeq {
	panic("forge stub")
}

func (c Recent) IDs() []int {
	panic("forge stub")
}

func (c Recent) Names() []string {
	panic("forge stub")
}

func (c Recent) Emails() []string {
	panic("forge stub")
}

func (c Recent) Ages() []int {
	panic("forge stub")
}

func (c Recent) Aliases() [][]string {
	panic("forge stub")
}

func (c Recent) project[V any](of func(Person) V) []V { panic("forge stub") }

const recentFixedCap = 1024

func NewRecent() *Recent { panic("forge stub") }

func (r *Recent) Cap() int { panic("forge stub") }

func (r *Recent) Len() int { panic("forge stub") }

func (r *Recent) Push(v Person) { panic("forge stub") }

func (r *Recent) All() iter.Seq[Person] { panic("forge stub") }

func (r *Recent) Backward() iter.Seq[Person] { panic("forge stub") }

func (r *Recent) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (r *Recent) Reset() { panic("forge stub") }

func (r *Recent) built() { panic("forge stub") }

func recentIndexOf(from, i, size int) int { panic("forge stub") }

func (c *Recent) AppendJSON(dst []byte) ([]byte, error) { panic("forge stub") }

func (c *Recent) MarshalJSON() ([]byte, error) { panic("forge stub") }

func (c *Recent) WriteTo(w io.Writer) (int64, error) { panic("forge stub") }

func recentReadJSON(c *Recent, data []byte, borrow bool) error { panic("forge stub") }

func (c *Recent) UnmarshalJSON(data []byte) error { panic("forge stub") }

func (c *Recent) UnmarshalJSONBorrowed(data []byte) error { panic("forge stub") }

func (c *Recent) ReadFrom(r io.Reader) (int64, error) { panic("forge stub") }

var (
	_ io.WriterTo      = (*Recent)(nil)
	_ io.ReaderFrom    = (*Recent)(nil)
	_ json.Marshaler   = (*Recent)(nil)
	_ json.Unmarshaler = (*Recent)(nil)
)

var _ func(*Recent) iter.Seq[Person] = (*Recent).All

func NewRoster() *Roster { panic("forge stub") }

func (g *Roster) Do(f func(v RosterView)) { panic("forge stub") }

func (g *Roster) RDo(f func(v RosterView)) { panic("forge stub") }

func (g *Roster) Snapshot() []Person { panic("forge stub") }

func (g *Roster) Len() int { panic("forge stub") }

func (g *Roster) AppendJSON(dst []byte) ([]byte, error) { panic("forge stub") }

func (g *Roster) MarshalJSON() ([]byte, error) { panic("forge stub") }

type RosterView struct {
	held *rosterHeld
}

func (v RosterView) Cap() int { panic("forge stub") }

func (v RosterView) Len() int { panic("forge stub") }

func (v RosterView) All() iter.Seq[Person] { panic("forge stub") }

func (v RosterView) Backward() iter.Seq[Person] { panic("forge stub") }

func (v RosterView) Reset() { panic("forge stub") }

func (v RosterView) Push(a0 Person) { panic("forge stub") }

func (v RosterView) AppendSeq(a0 iter.Seq[Person]) { panic("forge stub") }

const rosterHeldFixedCap = 64

type rosterHeld struct {
	buf  []Person
	head int
	n    int
}

func newRosterHeld() *rosterHeld { panic("forge stub") }

func (r *rosterHeld) Cap() int { panic("forge stub") }

func (r *rosterHeld) Len() int { panic("forge stub") }

func (r *rosterHeld) Push(v Person) { panic("forge stub") }

func (r *rosterHeld) All() iter.Seq[Person] { panic("forge stub") }

func (r *rosterHeld) Backward() iter.Seq[Person] { panic("forge stub") }

func (r *rosterHeld) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (r *rosterHeld) Reset() { panic("forge stub") }

func (r *rosterHeld) built() { panic("forge stub") }

func rosterHeldIndexOf(from, i, size int) int { panic("forge stub") }

var _ json.Marshaler = (*Roster)(nil)

func NewStatuses(elems ...Status) Statuses { panic("forge stub") }

func (s Statuses) Len() int { panic("forge stub") }

func (s Statuses) All() iter.Seq[Status] { panic("forge stub") }

func (s Statuses) Backward() iter.Seq[Status] { panic("forge stub") }

func (s *Statuses) AppendSeq(seq iter.Seq[Status]) { panic("forge stub") }

func (s *Statuses) Reset() { panic("forge stub") }

var _ func(*Statuses) iter.Seq[Status] = (*Statuses).All

type CredentialsSeq struct {
	Seq[Credential]
}

func (c Credentials) Seq() CredentialsSeq {
	panic("forge stub")
}

func (c Credentials) Owners() []int {
	panic("forge stub")
}

func (c Credentials) States() []Status {
	panic("forge stub")
}

func (c Credentials) Secrets() []*Secret {
	panic("forge stub")
}

func (c Credentials) SortedByOwner() []Credential {
	panic("forge stub")
}

func (c Credentials) ByOwner() map[int]Credential {
	panic("forge stub")
}

func (c Credentials) Less(i, j int) bool {
	panic("forge stub")
}

func (c Credentials) Swap(i, j int) {
	panic("forge stub")
}

func (c Credentials) project[V any](of func(Credential) V) []V { panic("forge stub") }

func (c Credentials) keyed[K comparable](by func(Credential) K) map[K]Credential { panic("forge stub") }

func (c Credentials) ordered[K cmp.Ordered](by func(Credential) K) []Credential { panic("forge stub") }

func NewCredentials(elems ...Credential) Credentials { panic("forge stub") }

func (s Credentials) Len() int { panic("forge stub") }

func (s Credentials) All() iter.Seq[Credential] { panic("forge stub") }

func (s Credentials) Backward() iter.Seq[Credential] { panic("forge stub") }

func (s *Credentials) AppendSeq(seq iter.Seq[Credential]) { panic("forge stub") }

func (s *Credentials) Reset() { panic("forge stub") }

func (c Credentials) AppendJSON(dst []byte) ([]byte, error) { panic("forge stub") }

func (c Credentials) MarshalJSON() ([]byte, error) { panic("forge stub") }

func (c Credentials) WriteTo(w io.Writer) (int64, error) { panic("forge stub") }

func credentialsReadJSON(c *Credentials, data []byte, borrow bool) error { panic("forge stub") }

func (c *Credentials) UnmarshalJSON(data []byte) error { panic("forge stub") }

func (c *Credentials) UnmarshalJSONBorrowed(data []byte) error { panic("forge stub") }

func (c *Credentials) ReadFrom(r io.Reader) (int64, error) { panic("forge stub") }

var (
	_ io.WriterTo      = *new(Credentials)
	_ io.ReaderFrom    = (*Credentials)(nil)
	_ json.Marshaler   = *new(Credentials)
	_ json.Unmarshaler = (*Credentials)(nil)
	_ sort.Interface   = *new(Credentials)
)

var _ func(*Credentials) iter.Seq[Credential] = (*Credentials).All

func PersonFromApplicant(src *Applicant) Person { panic("forge stub") }

type PersonBuilder struct {
	// held is the value being built, which every setter writes one field of.
	held Person

	// given records which of the required fields have been given, in the order
	// Build reports them: Name, Email.
	//
	// Recorded rather than read off the value, because a field given the zero
	// value was still given: a caller who set it meant to, and whether the zero
	// value will do is a rule rather than an omission.
	given [2]bool
}

func NewPersonBuilder() *PersonBuilder { panic("forge stub") }

func (b *PersonBuilder) ID(v int) *PersonBuilder { panic("forge stub") }

func (b *PersonBuilder) Name(v string) *PersonBuilder { panic("forge stub") }

func (b *PersonBuilder) Email(v string) *PersonBuilder { panic("forge stub") }

func (b *PersonBuilder) Age(v int) *PersonBuilder { panic("forge stub") }

func (b *PersonBuilder) Aliases(v []string) *PersonBuilder { panic("forge stub") }

func (b *PersonBuilder) Build() (Person, error) { panic("forge stub") }

func clonePerson(v Person) Person { panic("forge stub") }

func (v Person) Clone() Person { panic("forge stub") }

func (v Person) String() string { panic("forge stub") }

func (v Status) String() string { panic("forge stub") }

func (v Status) Valid() bool { panic("forge stub") }

func ValuesStatus() []Status { panic("forge stub") }

func ParseStatus(s string) (Status, error) { panic("forge stub") }

func (v Status) MarshalText() ([]byte, error) { panic("forge stub") }

func (v Status) AppendText(b []byte) ([]byte, error) { panic("forge stub") }

func (v *Status) UnmarshalText(b []byte) error { panic("forge stub") }

func nestedValidation(into ValidationErrors, at string, err error) ValidationErrors {
	panic("forge stub")
}

type ValidationError struct {
	// Path reaches the field from the value that was checked: "Email", or
	// "Address.City" for a field inside another struct.
	Path string

	// Rule is the rule that was not met, written as it was written in the tag,
	// so that the failure and the source read alike. It is empty for a failure
	// that came from a check the author wrote themselves.
	Rule string

	// Want says what the rule wanted, in words, so that a message can be shown
	// to somebody who has never seen the tag.
	Want string

	// Cause is what a check the author wrote returned. It is nil for a failure
	// of a rule, which has nothing underneath it.
	Cause error
}

func (e ValidationError) Error() string { panic("forge stub") }

func (e ValidationError) Unwrap() error { panic("forge stub") }

type ValidationErrors []ValidationError

func (e ValidationErrors) Error() string { panic("forge stub") }

func (e ValidationErrors) Unwrap() []error { panic("forge stub") }

func hashPerson(v Person) uint64 { panic("forge stub") }

func (v Person) Hash() uint64 { panic("forge stub") }

const (
	fnvSeed  uint64 = 14695981039346656037
	fnvPrime uint64 = 1099511628211
)

func fnvUint64(h, v uint64) uint64 { panic("forge stub") }

func fnvString(h uint64, s string) uint64 { panic("forge stub") }

func fnvBool(h uint64, b bool) uint64 { panic("forge stub") }

func fnvFloat(h uint64, f float64) uint64 { panic("forge stub") }

const fnvNaN uint64 = 0x7ff8000000000001

func appendPeopleCredentialJSON(dst []byte, v Credential) ([]byte, error) { panic("forge stub") }

func (v Credential) AppendJSON(dst []byte) ([]byte, error) { panic("forge stub") }

func (v Credential) MarshalJSON() ([]byte, error) { panic("forge stub") }

func (v *Credential) UnmarshalJSON(data []byte) error { panic("forge stub") }

func (v *Credential) UnmarshalJSONBorrowed(data []byte) error { panic("forge stub") }

func decodePeopleCredentialJSON(b []byte, i, depth int, v *Credential, borrow bool) (int, error) {
	panic("forge stub")
}

func appendPeoplePersonJSON(dst []byte, v Person) ([]byte, error) { panic("forge stub") }

func (v Person) AppendJSON(dst []byte) ([]byte, error) { panic("forge stub") }

func (v Person) MarshalJSON() ([]byte, error) { panic("forge stub") }

func (v *Person) UnmarshalJSON(data []byte) error { panic("forge stub") }

func (v *Person) UnmarshalJSONBorrowed(data []byte) error { panic("forge stub") }

func decodePeoplePersonJSON(b []byte, i, depth int, v *Person, borrow bool) (int, error) {
	panic("forge stub")
}

func appendPeopleSecretJSON(dst []byte, v Secret) ([]byte, error) { panic("forge stub") }

func (v Secret) AppendJSON(dst []byte) ([]byte, error) { panic("forge stub") }

func (v Secret) MarshalJSON() ([]byte, error) { panic("forge stub") }

func (v *Secret) UnmarshalJSON(data []byte) error { panic("forge stub") }

func (v *Secret) UnmarshalJSONBorrowed(data []byte) error { panic("forge stub") }

func decodePeopleSecretJSON(b []byte, i, depth int, v *Secret, borrow bool) (int, error) {
	panic("forge stub")
}

func (v Person) LogValue() slog.Value { panic("forge stub") }

func AppendPersonJSONFromApplicant(dst []byte, src *Applicant) ([]byte, error) { panic("forge stub") }

func WritePersonJSONFromApplicant(w io.Writer, src *Applicant) (int64, error) { panic("forge stub") }

type PersonPatch struct {
	// ID is what to set the ID to, and is nil where the patch says nothing about
	// it.
	ID *int `validate:"min=1"`

	// Name is what to set the Name to, and is nil where the patch says nothing
	// about it.
	Name *string `validate:"required,max=64" display:""`

	// Email is what to set the Email to, and is nil where the patch says nothing
	// about it.
	Email *string `validate:"required,regexp=^[^@[:space:]]+@[^@[:space:]]+$" redact:"" from:"Applicant.Contact"`

	// Age is what to set the Age to, and is nil where the patch says nothing about
	// it.
	Age *int `validate:"min=0,max=150" display:"age"`

	// Aliases is what to set the Aliases to, and is nil where the patch says
	// nothing about it.
	Aliases *[]string
}

func (p PersonPatch) Apply(into *Person) { panic("forge stub") }

func (p PersonPatch) IsZero() bool { panic("forge stub") }

func (v Credential) LogValue() slog.Value { panic("forge stub") }

func (v Secret) LogValue() slog.Value { panic("forge stub") }

var patternPersonEmail = regexp.MustCompile("^[^@[:space:]]+@[^@[:space:]]+$")

func validatePerson(v Person) error { panic("forge stub") }

func (v Person) Validate() error { panic("forge stub") }

type Seq[U any] iter.Seq[U]

func (s Seq[U]) All() iter.Seq[U] { panic("forge stub") }

func (s Seq[U]) Filter(keep func(U) bool) Seq[U] { panic("forge stub") }

func (s Seq[U]) Map[V any](to func(U) V) Seq[V] { panic("forge stub") }

func (s Seq[U]) Take(n int) Seq[U] { panic("forge stub") }

func (s Seq[U]) Skip(n int) Seq[U] { panic("forge stub") }

func (s Seq[U]) Dedup(same func(a, b U) bool) Seq[U] { panic("forge stub") }

func (s Seq[U]) Chunk(n int) iter.Seq[[]U] { panic("forge stub") }

func (s Seq[U]) Collect() []U { panic("forge stub") }

func (s Seq[U]) Into(dst []U) []U { panic("forge stub") }

func (s Seq[U]) First() (U, bool) { panic("forge stub") }

func (s Seq[U]) Reduce[A any](initial A, combine func(A, U) A) A { panic("forge stub") }

var (
	errJSONSyntax    = errors.New("json: invalid syntax")
	errJSONUTF8      = errors.New("json: invalid UTF-8")
	errJSONEscape    = errors.New("json: invalid escape")
	errJSONTruncated = errors.New("json: unexpected end of input")
	errJSONDuplicate = errors.New("json: duplicate object member name")
	errJSONSurrogate = errors.New("json: invalid surrogate pair")
	errJSONRange     = errors.New("json: number out of range for its Go type")
	errJSONDeep      = errors.New("json: value nested deeper than a reader reads")
	errJSONNonfinite = errors.New("json: a non-finite number has no JSON form")
)

const jsonMaxDepth = 10000

const jsonScratchCap = 1 << 16

var jsonScratch = sync.Pool{New: func() any { b := make([]byte, 0, 256); return &b }}

func jsonTakeScratch() *[]byte { panic("forge stub") }

func jsonDropScratch(b *[]byte) { panic("forge stub") }

func jsonAppendString(dst []byte, s string) ([]byte, error) { panic("forge stub") }

func jsonCloseText(dst []byte, mark int) ([]byte, error) { panic("forge stub") }

func jsonEscapeBehind(dst []byte, mark, from int) ([]byte, error) { panic("forge stub") }

const (
	jsonOnes    = 0x0101010101010101
	jsonHighs   = 0x8080808080808080
	jsonQuotes  = 0x2222222222222222 // '"' in every byte
	jsonSlashes = 0x5c5c5c5c5c5c5c5c // '\\' in every byte
)

func jsonPlainWords(s string, i int) int { panic("forge stub") }

func jsonAnyZero(w uint64) uint64 { panic("forge stub") }

func jsonBelow(w uint64, n byte) uint64 { panic("forge stub") }

func jsonAppendEscape(dst []byte, c byte) []byte { panic("forge stub") }

func jsonAppendFloat(dst []byte, f float64, width int) []byte { panic("forge stub") }

func jsonAppendFinite(dst []byte, f float64, width int) ([]byte, error) { panic("forge stub") }

func jsonSkipSpace(b []byte, i int) int { panic("forge stub") }

func jsonAtEnd(b []byte, i int) error { panic("forge stub") }

func jsonScanString(b []byte, i int) (lo, hi, next int, esc bool, err error) { panic("forge stub") }

func jsonPlainBytes(b []byte, i int) int { panic("forge stub") }

func jsonScanEscape(b []byte, i int) (int, error) { panic("forge stub") }

func jsonScanUnicode(b []byte, i int) (int, error) { panic("forge stub") }

func jsonUnescape(dst, b []byte) ([]byte, error) { panic("forge stub") }

func jsonScanEscapedRune(b []byte) (rune, int, error) { panic("forge stub") }

func jsonHex4(b []byte) (rune, error) { panic("forge stub") }

func jsonScanNumber(b []byte, i int) (lo, hi int, err error) { panic("forge stub") }

func jsonScanWhole(b []byte, i int) (int, error) { panic("forge stub") }

func jsonScanFraction(b []byte, i int) (int, error) { panic("forge stub") }

func jsonScanExponent(b []byte, i int) (int, error) { panic("forge stub") }

func jsonIsDigit(c byte) bool { panic("forge stub") }

func jsonScanInt(b []byte, i, width int) (int64, int, error) { panic("forge stub") }

func jsonScanUint(b []byte, i, width int) (uint64, int, error) { panic("forge stub") }

func jsonDigits(b []byte, i int) (uint64, int, error) { panic("forge stub") }

func jsonScanFloat(b []byte, i, width int) (float64, int, error) { panic("forge stub") }

func jsonScanBool(b []byte, i int) (bool, int, error) { panic("forge stub") }

func jsonScanNull(b []byte, i int) (int, bool) { panic("forge stub") }

func jsonSkipValue(b []byte, i, depth int) (int, error) { panic("forge stub") }

func jsonSkipObject(b []byte, i, depth int) (int, error) { panic("forge stub") }

func jsonSkipArray(b []byte, i, depth int) (int, error) { panic("forge stub") }

type jsonNames struct {
	declared uint64
	spilled  []uint64
	few      [8]jsonSpan
	n        int
	more     []jsonSpan
}

type jsonSpan struct {
	lo, hi int
	esc    bool
}

func (n *jsonNames) declare(index int) bool { panic("forge stub") }

func (n *jsonNames) saw(index int) bool { panic("forge stub") }

func (n *jsonNames) unknown(b []byte, lo, hi int, esc bool) bool { panic("forge stub") }

func jsonSameName(b []byte, a, c jsonSpan) bool { panic("forge stub") }

func jsonMemberNext(b []byte, i int, first bool) (int, bool, error) { panic("forge stub") }

func jsonMemberName(b []byte, i int) (lo, hi, next int, esc bool, err error) { panic("forge stub") }

func jsonElementNext(b []byte, i int, first bool) (int, bool, error) { panic("forge stub") }

func jsonName(b []byte, lo, hi int, esc bool, scratch *[]byte) []byte { panic("forge stub") }

func jsonString(b []byte, lo, hi int, esc, borrow bool) string { panic("forge stub") }

func jsonAppendBytes(dst, held []byte) []byte { panic("forge stub") }

func jsonScanBytes(b []byte, lo, hi int, esc bool, dst []byte) ([]byte, error) { panic("forge stub") }

func jsonWroteEmpty(b []byte, at int) bool { panic("forge stub") }

var jsonKeysScratch = sync.Pool{New: func() any { held := make([]string, 0, 16); return &held }}

func jsonSortedKeys[K ~string, V any](m map[K]V) *[]string { panic("forge stub") }

func jsonTakeKeys() *[]string { panic("forge stub") }

func jsonDropKeys(keys *[]string) { panic("forge stub") }

var jsonNumsScratch = sync.Pool{New: func() any { held := make([]uint64, 0, 16); return &held }}

func jsonTakeNums() *[]uint64 { panic("forge stub") }

func jsonDropNums(keys *[]uint64) { panic("forge stub") }

func jsonSortedIntKeys[K ~int | ~int8 | ~int16 | ~int32 | ~int64, V any](m map[K]V) *[]uint64 {
	panic("forge stub")
}

func jsonSortedUintKeys[K ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr, V any](m map[K]V) *[]uint64 {
	panic("forge stub")
}

func jsonSortedFloatKeys[K ~float32 | ~float64, V any](m map[K]V, width int) *[]uint64 {
	panic("forge stub")
}

func jsonNameInt(name []byte, width int) (int64, error) { panic("forge stub") }

func jsonNameUint(name []byte, width int) (uint64, error) { panic("forge stub") }

func jsonNameFloat(name []byte, width int) (float64, error) { panic("forge stub") }

func jsonFinish(scratch *[]byte, b []byte, err error) ([]byte, error) { panic("forge stub") }

func jsonCannotRead(what string, b []byte, i int) error { panic("forge stub") }

func jsonKindName(b []byte, i int) string { panic("forge stub") }

const jsonFlushWindow = 1 << 12

type jsonScanState struct {
	depth int
	str   bool
	esc   bool
}

func jsonValueEnd(b []byte, i int, st *jsonScanState) (int, bool) { panic("forge stub") }

type jsonFeed struct {
	r    io.Reader
	buf  *[]byte
	i    int
	done int64
}

func jsonNewFeed(r io.Reader) jsonFeed { panic("forge stub") }

func (f *jsonFeed) close() { panic("forge stub") }

func (f *jsonFeed) offset() int64 { panic("forge stub") }

func (f *jsonFeed) more() error { panic("forge stub") }

func (f *jsonFeed) peek() (byte, error) { panic("forge stub") }

func (f *jsonFeed) take() { panic("forge stub") }

func (f *jsonFeed) null() (bool, error) { panic("forge stub") }

func (f *jsonFeed) cannotRead(what string) error { panic("forge stub") }

func (f *jsonFeed) element() ([]byte, error) { panic("forge stub") }

var (
	_ json.Marshaler   = *new(Person)
	_ json.Unmarshaler = (*Person)(nil)
	_ fmt.Stringer     = *new(Person)
	_ slog.LogValuer   = *new(Person)
)

var (
	_ fmt.Stringer             = *new(Status)
	_ encoding.TextAppender    = *new(Status)
	_ encoding.TextMarshaler   = *new(Status)
	_ encoding.TextUnmarshaler = (*Status)(nil)
)

var (
	_ json.Marshaler   = *new(Credential)
	_ json.Unmarshaler = (*Credential)(nil)
	_ slog.LogValuer   = *new(Credential)
)
