// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge (devel)
// go go1.27.0
// inputs 75f4e0b5edae3546

//go:build forgespec

package people

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"io"
	"iter"
)

type RecentSeq struct {
	Seq[Person]
}

func (c Recent) Seq() RecentSeq {
	panic("forge stub")
}
func (c Recent) IDs() []int {
	panic("forge stub")
}
func (c Recent) Names() []string {
	panic("forge stub")
}
func (c Recent) Emails() []string {
	panic("forge stub")
}
func (c Recent) Ages() []int {
	panic("forge stub")
}
func (c Recent) Aliaseses() [][]string {
	panic("forge stub")
}

func (c Recent) project[V any](of func(Person) V) []V { panic("forge stub") }

const recentFixedCap = 1024

func NewRecent() *Recent { panic("forge stub") }

func (r *Recent) Cap() int { panic("forge stub") }

func (r *Recent) Len() int { panic("forge stub") }

func (r *Recent) Push(v Person) { panic("forge stub") }

func (r *Recent) All() iter.Seq[Person] { panic("forge stub") }

func (r *Recent) Backward() iter.Seq[Person] { panic("forge stub") }

func (r *Recent) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (r *Recent) Reset() { panic("forge stub") }

func (r *Recent) built() { panic("forge stub") }

func recentIndexOf(from, i, size int) int { panic("forge stub") }

func (c *Recent) MarshalJSONTo(enc *jsontext.Encoder) error { panic("forge stub") }

type recentCounting struct {
	to io.Writer
	n  int64
}

func (w *recentCounting) Write(p []byte) (int, error) { panic("forge stub") }

func (c *Recent) WriteTo(w io.Writer) (int64, error) { panic("forge stub") }

func (c *Recent) UnmarshalJSONFrom(dec *jsontext.Decoder) error { panic("forge stub") }

func (c *Recent) ReadFrom(r io.Reader) (int64, error) { panic("forge stub") }

var (
	_ io.WriterTo          = (*Recent)(nil)
	_ io.ReaderFrom        = (*Recent)(nil)
	_ json.MarshalerTo     = (*Recent)(nil)
	_ json.UnmarshalerFrom = (*Recent)(nil)
)

var _ func(*Recent) iter.Seq[Person] = (*Recent).All
