// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge (devel)
// go go1.27.0
// inputs 9cb46019963acad6

package people

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"math"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

// clonePerson returns a copy of v that shares nothing with it.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func clonePerson(v Person) Person {
	return v.Clone()
}

// Clone returns a copy of the Person that shares nothing with it.
//
// Everything reachable is copied, so what is done to the copy is invisible in
// the original and the other way round. The copy starts as an assignment, which
// is already the whole of it for a field holding a number, a string or anything
// else made only of those; what follows is the fields for which an assignment
// would have copied a reference rather than what it refers to.
func (v Person) Clone() Person {
	out := v

	out.Aliases = slices.Clone(v.Aliases)
	return out
}

// String returns the subject as the display tags on its fields ask for it.
//
// The fields in the order they were written, separated by a space, each
// labelled where its tag gave it a name. It is a rendering for a person to
// read rather than a format anything should parse: nothing here escapes a
// separator that turns up inside a value, because a reader can see what
// happened and a parser was never the point.
func (v Person) String() string {
	var b strings.Builder

	b.WriteString(v.Name)

	b.WriteString(" ")
	b.WriteString("age=")
	b.WriteString(strconv.FormatInt(int64(v.Age), 10))

	return b.String()
}

// hashPerson returns a content hash of v.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func hashPerson(v Person) uint64 {
	return v.Hash()
}

// Hash returns a content hash of the Person.
//
// Two values that are the same all the way down hash to the same number,
// in this process and in every other, on any machine and in any build. Two
// that differ almost certainly do not: this is a hash rather than an
// identity, so a caller who cannot afford a collision compares as well.
//
// It allocates nothing, which is what makes it affordable to take on every
// lookup rather than once and cache.
func (v Person) Hash() uint64 {
	h := fnvSeed
	h = fnvUint64(h, uint64(v.ID))
	h = fnvString(h, string(v.Name))
	h = fnvString(h, string(v.Email))
	h = fnvUint64(h, uint64(v.Age))
	h = fnvBool(h, v.Aliases != nil)
	h = fnvUint64(h, uint64(len(v.Aliases)))
	for _, one := range v.Aliases {
		h = fnvString(h, string(one))
	}
	return h
}

// The two numbers FNV-1a is made of: what an empty stream hashes to, and the
// multiplier each byte is mixed with.
//
// Written out rather than taken from hash/fnv. That package answers through an
// interface, so a hash taken through it allocates and is called rather than
// inlined — and what is wanted here is arithmetic in the middle of a method,
// not an object with a lifetime.
const (
	fnvSeed  uint64 = 14695981039346656037
	fnvPrime uint64 = 1099511628211
)

// fnvUint64 mixes a whole number into a hash, eight bytes at a time.
//
// Eight whatever the number was declared as, so that a value held in an int
// hashes the same where an int is four bytes and where it is eight. A number
// that hashed differently depending on the machine would not be a stable
// identity, which is the only thing this is for.
func fnvUint64(h, v uint64) uint64 {
	for range 8 {
		h = (h ^ (v & 0xff)) * fnvPrime
		v >>= 8
	}
	return h
}

// fnvString mixes a string's length and then its bytes.
//
// The length as well as the bytes, because the bytes alone do not say where one
// string ended and the next began: "ab" beside "c" and "a" beside "bc" are the
// same five bytes in the same order and are not the same pair of values.
func fnvString(h uint64, s string) uint64 {
	h = fnvUint64(h, uint64(len(s)))
	for i := range len(s) {
		h = (h ^ uint64(s[i])) * fnvPrime
	}
	return h
}

// fnvBool mixes the one byte a boolean is worth.
func fnvBool(h uint64, b bool) uint64 {
	if b {
		return (h ^ 1) * fnvPrime
	}
	return h * fnvPrime
}

// fnvFloat mixes a floating-point number by its bits, with the two values
// whose bits are not a function of the number written down first.
//
// Zero is one number with two spellings, since the sign bit is free, and a hash
// taken straight off the bits would give positive and negative zero two answers
// though they compare equal. Not-a-number is the opposite case: it is many bit
// patterns, no one of which equals any other or even itself, so no answer
// agrees with comparison and the least surprising one is that they all hash
// alike.
func fnvFloat(h uint64, f float64) uint64 {
	switch {
	case math.IsNaN(f):
		return fnvUint64(h, fnvNaN)
	case f == 0:
		return fnvUint64(h, 0)
	default:
		return fnvUint64(h, math.Float64bits(f))
	}
}

// fnvNaN is what every not-a-number hashes as. A constant of this file rather
// than the bits of math.NaN, so that what a value hashes to is decided here and
// cannot move under a library release.
const fnvNaN uint64 = 0x7ff8000000000001

// encodePeoplePersonJSONTo writes a Person as JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func encodePeoplePersonJSONTo(enc *jsontext.Encoder, v Person) error {
	return v.MarshalJSONTo(enc)
}

// MarshalJSONTo writes the Person as a JSON object.
//
// Members are written in the order the fields are declared, an embedded
// struct's where the embedded field is. A field that takes a name from a
// shallower one keeps its own place rather than the excluded one's.
func (v Person) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginObject); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("ID")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.Int(int64(v.ID))); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("Name")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(string(v.Name))); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("Email")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String(string(v.Email))); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("Age")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.Int(int64(v.Age))); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.String("Aliases")); err != nil {
		return err
	}
	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}
	for _, one := range v.Aliases {
		if err := enc.WriteToken(jsontext.String(string(one))); err != nil {
			return err
		}
	}
	if err := enc.WriteToken(jsontext.EndArray); err != nil {
		return err
	}
	return enc.WriteToken(jsontext.EndObject)
}

// decodePeoplePersonJSONFrom reads a Person from JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func decodePeoplePersonJSONFrom(dec *jsontext.Decoder, v *Person) error {
	return v.UnmarshalJSONFrom(dec)
}

// UnmarshalJSONFrom reads a JSON object into the Person.
//
// A member the object holds and the type does not is skipped, which is
// what keeps a reader working against a writer that has since added one.
func (v *Person) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if dec.PeekKind() == 'n' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		var zero Person
		*v = zero
		return nil
	}
	if kind := dec.PeekKind(); kind != '{' {
		if _, err := dec.ReadToken(); err != nil {
			return err
		}
		return fmt.Errorf("cannot read Person from a JSON %s", kind)
	}
	if _, err := dec.ReadToken(); err != nil {
		return err
	}
	for dec.PeekKind() != '}' {
		name, err := dec.ReadToken()
		if err != nil {
			return err
		}
		switch name.String() {
		case "ID":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero int
					v.ID = zero
				case '0':
					number, err := raw.Int()
					if err != nil {
						return err
					}
					if int64(int(number)) != number {
						return fmt.Errorf("%d is out of range for int", number)
					}
					v.ID = int(number)
				default:
					return fmt.Errorf("cannot read int from a JSON %s", raw.Kind())
				}
			}
		case "Name":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero string
					v.Name = zero
				case '"':
					v.Name = string(raw.String())
				default:
					return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
				}
			}
		case "Email":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero string
					v.Email = zero
				case '"':
					v.Email = string(raw.String())
				default:
					return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
				}
			}
		case "Age":
			{
				raw, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch raw.Kind() {
				case 'n':
					var zero int
					v.Age = zero
				case '0':
					number, err := raw.Int()
					if err != nil {
						return err
					}
					if int64(int(number)) != number {
						return fmt.Errorf("%d is out of range for int", number)
					}
					v.Age = int(number)
				default:
					return fmt.Errorf("cannot read int from a JSON %s", raw.Kind())
				}
			}
		case "Aliases":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				v.Aliases = nil
			} else {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				out := v.Aliases[:0]
				for dec.PeekKind() != ']' {
					var one string
					{
						raw, err := dec.ReadToken()
						if err != nil {
							return err
						}
						switch raw.Kind() {
						case 'n':
							var zero string
							one = zero
						case '"':
							one = string(raw.String())
						default:
							return fmt.Errorf("cannot read string from a JSON %s", raw.Kind())
						}
					}
					out = append(out, one)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				if out == nil {
					out = []string{}
				}
				v.Aliases = out
			}
		default:
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
	_, err := dec.ReadToken()
	return err
}

// LogValue returns the subject as it may be logged.
//
// Every exported field, with the ones tagged redact replaced by a fixed
// string. Fixed rather than shortened or starred: a length is something,
// a prefix is more, and a field marked as not for logs was marked by
// somebody who did not want to work out which of those is safe.
//
// Implementing this is what takes the field out of a log. slog reaches for
// a value's fields when the value does not say otherwise, so a type with a
// secret in it and no LogValue prints the secret.
func (v Person) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Int64("ID", int64(v.ID)),
		slog.String("Name", v.Name),
		slog.String("Email", "[redacted]"),
		slog.Int64("Age", int64(v.Age)),
		slog.Any("Aliases", v.Aliases),
	)
}

// patternPersonEmail is the pattern Email is checked against.
//
// Compiled when the package loads rather than at each check: compiling a
// pattern costs many times what matching against one does, and the pattern
// is the same every time because it was written in the source.
var patternPersonEmail = regexp.MustCompile("^[^@[:space:]]+@[^@[:space:]]+$")

// validatePerson reports every rule v does not satisfy.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func validatePerson(v Person) error {
	return v.Validate()
}

// Validate reports every rule the Person does not satisfy, and nothing when it
// satisfies them all.
//
// Every failure rather than the first, because a value with three things
// wrong is not three round trips. Nothing is allocated until something
// fails, so a value that is in order costs the comparisons and no memory.
func (v Person) Validate() error {
	var failed ValidationErrors

	if v.ID < 1 {
		failed = append(failed, ValidationError{Path: "ID", Rule: "min=1", Want: "at least 1"})
	}
	switch {
	case v.Name == "":
		failed = append(failed, ValidationError{Path: "Name", Rule: "required", Want: "a value"})
	case len(v.Name) > 64:
		failed = append(failed, ValidationError{Path: "Name", Rule: "max=64", Want: "at most 64 characters"})
	}
	switch {
	case v.Email == "":
		failed = append(failed, ValidationError{Path: "Email", Rule: "required", Want: "a value"})
	case !patternPersonEmail.MatchString(string(v.Email)):
		failed = append(failed, ValidationError{Path: "Email", Rule: "regexp=^[^@[:space:]]+@[^@[:space:]]+$", Want: "a value matching ^[^@[:space:]]+@[^@[:space:]]+$"})
	}
	switch {
	case v.Age < 0:
		failed = append(failed, ValidationError{Path: "Age", Rule: "min=0", Want: "at least 0"})
	case v.Age > 150:
		failed = append(failed, ValidationError{Path: "Age", Rule: "max=150", Want: "at most 150"})
	}
	if len(failed) == 0 {
		return nil
	}
	return failed
}

// ValidationError is one rule a value did not satisfy.
//
// It carries where rather than only what. A form with a bad postcode is not a
// form that is invalid; it is a form whose Address.Postcode is too short, and
// the difference is whether the caller can put the message beside the field it
// is about.
type ValidationError struct {
	// Path reaches the field from the value that was checked: "Email", or
	// "Address.City" for a field inside another struct.
	Path string

	// Rule is the rule that was not met, written as it was written in the tag,
	// so that the failure and the source read alike. It is empty for a failure
	// that came from a check the author wrote themselves.
	Rule string

	// Want says what the rule wanted, in words, so that a message can be shown
	// to somebody who has never seen the tag.
	Want string

	// Cause is what a check the author wrote returned. It is nil for a failure
	// of a rule, which has nothing underneath it.
	Cause error
}

// Error describes the failure, naming the field first.
func (e ValidationError) Error() string {
	switch {
	case e.Cause != nil:
		return e.Path + ": " + e.Cause.Error()
	case e.Want != "":
		return e.Path + ": " + e.Rule + " wants " + e.Want
	default:
		return e.Path + ": " + e.Rule
	}
}

// Unwrap returns what a check the author wrote returned, so that errors.Is and
// errors.As reach it.
func (e ValidationError) Unwrap() error { return e.Cause }

// ValidationErrors is every rule a value did not satisfy, in the order the
// fields are declared and the rules are written.
//
// Every failure rather than the first, because a caller showing a form to
// somebody wants to show them everything that is wrong with it at once.
type ValidationErrors []ValidationError

// Error describes every failure, one per line where there is more than one.
//
// A line each rather than a sentence joined by commas: the failures are about
// different fields, and a reader scanning for their own field finds it faster
// down the left edge than in the middle of a paragraph.
func (e ValidationErrors) Error() string {
	switch len(e) {
	case 0:
		// Nothing failed, which is not a state a caller reaches through this:
		// a check that found nothing wrong returns no error at all rather than
		// an empty list of them.
		return "nothing failed"
	case 1:
		return e[0].Error()
	}

	var out strings.Builder
	out.WriteString(strconv.Itoa(len(e)))
	out.WriteString(" failures:")

	for _, one := range e {
		out.WriteString("\n\t")
		out.WriteString(one.Error())
	}
	return out.String()
}

// Unwrap returns the failures as errors, so that errors.Is and errors.As reach
// each of them.
func (e ValidationErrors) Unwrap() []error {
	out := make([]error, len(e))
	for i, one := range e {
		out[i] = one
	}
	return out
}

// nestedValidation folds what a field's own check reported into the failures of
// the value that holds it, under the path that reaches the field.
//
// The path is what makes a nested check worth having. A City that is too short
// is reported by Address as "City", and the value holding the address has to
// say "Address.City" or a caller has no way to know which of two addresses it
// was.
//
// An error that is not a list of failures is carried whole, under the field's
// own path. That is what a check the author wrote returns, and what a type from
// somewhere else returns, and neither is this package's to take apart.
//
// Found through the chain rather than in the hand, so that failures wrapped by
// a check of somebody's own still reach the caller as failures with paths. A
// wrapper that meant to hide them can say so by not wrapping them.
func nestedValidation(into ValidationErrors, at string, err error) ValidationErrors {
	var held ValidationErrors
	if !errors.As(err, &held) {
		return append(into, ValidationError{Path: at, Cause: err})
	}

	for _, one := range held {
		one.Path = at + "." + one.Path
		into = append(into, one)
	}
	return into
}

// Seq is a lazy view over a sequence of elements.
//
// Every operation on it is lazy: it returns another view and walks nothing. The
// walk happens once, when a terminal asks for it, and each element passes
// through the whole chain before the next one is read — so a chain over a
// million elements holds one of them at a time and allocates nothing per
// element. A chain costs a few allocations per link to build and to start, and
// that is the whole of what it costs: the same over a million elements as over
// ten.
//
// The zero view yields nothing through every method here, so one that was never
// given a sequence behaves like an empty one. Ranging over it directly is
// ranging over a function that is not there, which panics like any other nil
// call — All is what guards that, and is what to range over.
type Seq[U any] iter.Seq[U]

// All returns the view as an ordinary sequence, which is what everything taking
// an iter.Seq wants and what a range loop should read.
//
// It is also where the zero view is made safe. A view is a function underneath,
// so one that was never given a sequence is a nil function and ranging over it
// panics; this hands back an empty sequence instead, and every method below
// walks through here rather than over the view directly.
func (s Seq[U]) All() iter.Seq[U] {
	if s == nil {
		return func(func(U) bool) {}
	}
	return iter.Seq[U](s)
}

// Filter returns a view of the elements the predicate keeps.
func (s Seq[U]) Filter(keep func(U) bool) Seq[U] {
	return func(yield func(U) bool) {
		for v := range s.All() {
			if keep(v) && !yield(v) {
				return
			}
		}
	}
}

// Map returns a view of what the function makes of each element.
//
// Genuinely generic in its result, so a chain that changes type keeps chaining:
// the view a projection returns is a view like any other, and the combinators
// on it are these same ones rather than a second set written for the new type.
func (s Seq[U]) Map[V any](to func(U) V) Seq[V] {
	return func(yield func(V) bool) {
		for v := range s.All() {
			if !yield(to(v)) {
				return
			}
		}
	}
}

// Take returns a view of at most the first n elements, and of none for an n
// that is not positive.
//
// It stops the walk beneath it rather than reading on and discarding, which is
// what makes taking ten from a very long sequence cost ten.
func (s Seq[U]) Take(n int) Seq[U] {
	return func(yield func(U) bool) {
		if n <= 0 {
			return
		}

		left := n
		for v := range s.All() {
			if !yield(v) {
				return
			}

			left--
			if left == 0 {
				return
			}
		}
	}
}

// Skip returns a view of everything after the first n elements, and of
// everything for an n that is not positive.
func (s Seq[U]) Skip(n int) Seq[U] {
	return func(yield func(U) bool) {
		left := n
		for v := range s.All() {
			if left > 0 {
				left--
				continue
			}
			if !yield(v) {
				return
			}
		}
	}
}

// Dedup returns a view with runs of equal elements collapsed to their first.
//
// Adjacent elements only, which is the whole of what a lazy operation can do:
// dropping every repeat wherever it appears means remembering everything seen
// so far, and a view that grew a set as it walked would not be a view any more.
// Sort or group first if that is what is wanted.
//
// Each element is compared against the last one that was *yielded* rather than
// against the one immediately before it, so a run collapses to its first
// element however long it is. The two are the same thing for an equality, and
// differ for a comparison that is not one — a nearness test over 1, 2, 3 keeps
// 1 and 3 here, where comparing neighbours would keep only 1. The first
// argument is the element that was kept and the second the one being offered.
func (s Seq[U]) Dedup(same func(a, b U) bool) Seq[U] {
	return func(yield func(U) bool) {
		var last U
		seen := false

		for v := range s.All() {
			if seen && same(last, v) {
				continue
			}

			last, seen = v, true
			if !yield(v) {
				return
			}
		}
	}
}

// Chunk yields slices of n elements, the last of them shorter if the sequence
// does not divide evenly. It panics for an n below one, which asks for
// something there is no answer to.
//
// Each chunk is a slice of its own rather than one buffer handed out again and
// again. Reusing it would allocate less and would make a chunk kept past the
// next one silently become that one — a bug that shows up as data from the
// wrong batch, far from here. The cost is one allocation per chunk, which is
// still none per element.
//
// A plain sequence rather than another view, and that one is the language's.
// A method of this type returning a view of slices means the type mentioning
// itself over a bigger type than it was given, and the method set of that one
// mentioning a bigger one again, without end; the compiler calls it an
// instantiation cycle and refuses the file. A function beside the type could
// return one — the cycle is a property of method sets — at the price of a name
// in this package that everything else here keeps inside the view. Chunks are
// usually ranged over, which this is, and converting what it yields to a view
// of slices is the whole of the difference when they are not.
func (s Seq[U]) Chunk(n int) iter.Seq[[]U] {
	if n < 1 {
		panic("forge: Chunk of fewer than one element")
	}

	return func(yield func([]U) bool) {
		// Built on the first element that goes into it rather than ahead of
		// one, so a sequence that ends on a boundary does not pay for a batch
		// nothing is put in.
		var batch []U

		for v := range s.All() {
			if batch == nil {
				batch = make([]U, 0, n)
			}
			if batch = append(batch, v); len(batch) < n {
				continue
			}
			if !yield(batch) {
				return
			}
			batch = nil
		}

		if len(batch) > 0 {
			yield(batch)
		}
	}
}

// Collect walks the view and returns everything it yields.
func (s Seq[U]) Collect() []U { return slices.Collect(s.All()) }

// Into appends everything the view yields to a slice and returns it.
//
// It is Collect for a caller who owns the memory: passing a slice kept between
// calls turns the one allocation Collect makes into none.
func (s Seq[U]) Into(dst []U) []U { return slices.AppendSeq(dst, s.All()) }

// First returns the first element the view yields, and whether it yielded one.
// The walk stops there, so first-of-a-filter over a long sequence costs the
// elements up to the match and no more.
func (s Seq[U]) First() (U, bool) {
	for v := range s.All() {
		return v, true
	}

	var none U
	return none, false
}

// Reduce combines the elements into a single value, left to right.
//
// Generic in what it builds rather than in the element alone, so a sequence of
// values reduces to a count, a total or a map without being projected first.
func (s Seq[U]) Reduce[A any](initial A, combine func(A, U) A) A {
	out := initial
	for v := range s.All() {
		out = combine(out, v)
	}
	return out
}

// Person satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ json.MarshalerTo     = *new(Person)
	_ json.UnmarshalerFrom = (*Person)(nil)
	_ fmt.Stringer         = *new(Person)
	_ slog.LogValuer       = *new(Person)
)
