// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge (devel)
// go go1.27.1
// inputs 019d47cf92479e37

//go:build !forgespec

package people

import (
	"iter"
	"slices"
)

// Statuses holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type Statuses []Status

// NewStatuses returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewStatuses(elems ...Status) Statuses { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Statuses) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Statuses) All() iter.Seq[Status] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Statuses) Backward() iter.Seq[Status] {
	return func(yield func(Status) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Statuses) AppendSeq(seq iter.Seq[Status]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *Statuses) Reset() { *s = (*s)[:0] }

// The walk's own signature, checked when the package is built.
//
// A method expression is resolved by the compiler and costs nothing at run
// time, where an interface assertion would have to name a value and initialise
// it. What it holds the walk to is the element type of the declaration, so a
// container that walks something else fails here rather than wherever somebody
// ranges over it.
var _ func(*Statuses) iter.Seq[Status] = (*Statuses).All
