// Code generated by forge. DO NOT EDIT.
//
// forge (devel)
// markers github.com/okian/forge (devel)
// go go1.27.0
// inputs 49747c291edebfa4

//go:build forgespec

package people

import (
	"cmp"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"io"
	"iter"
	"sort"
)

type RecentSeq struct {
	Seq[Person]
}

func (c Recent) Seq() RecentSeq {
	panic("forge stub")
}
func (c Recent) IDs() []int {
	panic("forge stub")
}
func (c Recent) Names() []string {
	panic("forge stub")
}
func (c Recent) Emails() []string {
	panic("forge stub")
}
func (c Recent) Ages() []int {
	panic("forge stub")
}
func (c Recent) Aliaseses() [][]string {
	panic("forge stub")
}

func (c Recent) project[V any](of func(Person) V) []V { panic("forge stub") }

const recentFixedCap = 1024

func NewRecent() *Recent { panic("forge stub") }

func (r *Recent) Cap() int { panic("forge stub") }

func (r *Recent) Len() int { panic("forge stub") }

func (r *Recent) Push(v Person) { panic("forge stub") }

func (r *Recent) All() iter.Seq[Person] { panic("forge stub") }

func (r *Recent) Backward() iter.Seq[Person] { panic("forge stub") }

func (r *Recent) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (r *Recent) Reset() { panic("forge stub") }

func (r *Recent) built() { panic("forge stub") }

func recentIndexOf(from, i, size int) int { panic("forge stub") }

func (c *Recent) MarshalJSONTo(enc *jsontext.Encoder) error { panic("forge stub") }

type recentCounting struct {
	to io.Writer
	n  int64
}

func (w *recentCounting) Write(p []byte) (int, error) { panic("forge stub") }

func (c *Recent) WriteTo(w io.Writer) (int64, error) { panic("forge stub") }

func (c *Recent) UnmarshalJSONFrom(dec *jsontext.Decoder) error { panic("forge stub") }

func (c *Recent) ReadFrom(r io.Reader) (int64, error) { panic("forge stub") }

var (
	_ io.WriterTo          = (*Recent)(nil)
	_ io.ReaderFrom        = (*Recent)(nil)
	_ json.MarshalerTo     = (*Recent)(nil)
	_ json.UnmarshalerFrom = (*Recent)(nil)
)

var _ func(*Recent) iter.Seq[Person] = (*Recent).All

func NewRoster() *Roster { panic("forge stub") }

func (g *Roster) Do(f func(v RosterView)) { panic("forge stub") }

func (g *Roster) RDo(f func(v RosterView)) { panic("forge stub") }

func (g *Roster) Snapshot() []Person { panic("forge stub") }

func (g *Roster) Len() int { panic("forge stub") }

func (g *Roster) MarshalJSONTo(enc *jsontext.Encoder) error { panic("forge stub") }

type RosterView struct {
	held *rosterHeld
}

func (v RosterView) Cap() int { panic("forge stub") }

func (v RosterView) Len() int { panic("forge stub") }

func (v RosterView) All() iter.Seq[Person] { panic("forge stub") }

func (v RosterView) Backward() iter.Seq[Person] { panic("forge stub") }

func (v RosterView) Reset() { panic("forge stub") }

func (v RosterView) Push(a0 Person) { panic("forge stub") }

func (v RosterView) AppendSeq(a0 iter.Seq[Person]) { panic("forge stub") }

const rosterHeldFixedCap = 64

type rosterHeld struct {
	buf  []Person
	head int
	n    int
}

func newRosterHeld() *rosterHeld { panic("forge stub") }

func (r *rosterHeld) Cap() int { panic("forge stub") }

func (r *rosterHeld) Len() int { panic("forge stub") }

func (r *rosterHeld) Push(v Person) { panic("forge stub") }

func (r *rosterHeld) All() iter.Seq[Person] { panic("forge stub") }

func (r *rosterHeld) Backward() iter.Seq[Person] { panic("forge stub") }

func (r *rosterHeld) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (r *rosterHeld) Reset() { panic("forge stub") }

func (r *rosterHeld) built() { panic("forge stub") }

func rosterHeldIndexOf(from, i, size int) int { panic("forge stub") }

var (
	_ json.MarshalerTo = (*Roster)(nil)
)

func NewStatuses(elems ...Status) Statuses { panic("forge stub") }

func (s Statuses) Len() int { panic("forge stub") }

func (s Statuses) All() iter.Seq[Status] { panic("forge stub") }

func (s Statuses) Backward() iter.Seq[Status] { panic("forge stub") }

func (s *Statuses) AppendSeq(seq iter.Seq[Status]) { panic("forge stub") }

func (s *Statuses) Reset() { panic("forge stub") }

var _ func(*Statuses) iter.Seq[Status] = (*Statuses).All

type CredentialsSeq struct {
	Seq[Credential]
}

func (c Credentials) Seq() CredentialsSeq {
	panic("forge stub")
}
func (c Credentials) Owners() []int {
	panic("forge stub")
}
func (c Credentials) States() []Status {
	panic("forge stub")
}
func (c Credentials) Secrets() []*Secret {
	panic("forge stub")
}
func (c Credentials) SortedByOwner() []Credential {
	panic("forge stub")
}
func (c Credentials) ByOwner() map[int]Credential {
	panic("forge stub")
}
func (c Credentials) Less(i, j int) bool {
	panic("forge stub")
}
func (c Credentials) Swap(i, j int) {
	panic("forge stub")
}

func (c Credentials) project[V any](of func(Credential) V) []V { panic("forge stub") }

func (c Credentials) keyed[K comparable](by func(Credential) K) map[K]Credential { panic("forge stub") }

func (c Credentials) ordered[K cmp.Ordered](by func(Credential) K) []Credential { panic("forge stub") }

func NewCredentials(elems ...Credential) Credentials { panic("forge stub") }

func (s Credentials) Len() int { panic("forge stub") }

func (s Credentials) All() iter.Seq[Credential] { panic("forge stub") }

func (s Credentials) Backward() iter.Seq[Credential] { panic("forge stub") }

func (s *Credentials) AppendSeq(seq iter.Seq[Credential]) { panic("forge stub") }

func (s *Credentials) Reset() { panic("forge stub") }

func (c Credentials) MarshalJSONTo(enc *jsontext.Encoder) error { panic("forge stub") }

type credentialsCounting struct {
	to io.Writer
	n  int64
}

func (w *credentialsCounting) Write(p []byte) (int, error) { panic("forge stub") }

func (c Credentials) WriteTo(w io.Writer) (int64, error) { panic("forge stub") }

func (c *Credentials) UnmarshalJSONFrom(dec *jsontext.Decoder) error { panic("forge stub") }

func (c *Credentials) ReadFrom(r io.Reader) (int64, error) { panic("forge stub") }

var (
	_ io.WriterTo          = *new(Credentials)
	_ io.ReaderFrom        = (*Credentials)(nil)
	_ json.MarshalerTo     = *new(Credentials)
	_ json.UnmarshalerFrom = (*Credentials)(nil)
	_ sort.Interface       = *new(Credentials)
)

var _ func(*Credentials) iter.Seq[Credential] = (*Credentials).All
