package templates_test

import (
	"strings"
	"testing"

	"github.com/okian/forge/internal/goldentest"
	"github.com/okian/forge/internal/templates"
)

// specialised rewrites a template and returns what it became, failing the test
// if it was refused.
func specialised(t *testing.T, source string, r templates.Rewrite) string {
	t.Helper()

	out, diags := templates.Apply(templates.Template{Name: "toy", Source: []byte(source)}, r, where)
	if !diags.Empty() {
		t.Fatalf("the template was refused:\n%s", diags.Render())
	}
	return rendered(t, out)
}

// compiles puts a specialised template through the same gate every layer's
// output goes through, since a rewrite that produces plausible-looking Go is
// not the same as one that produces Go.
//
// The imports are written from what the rewrite handed back rather than from
// what the template said, because that pair is the thing being checked: a body
// calling a package by a name the import block does not bind is a file that
// looks right and does not build.
func compiles(t *testing.T, source string) {
	t.Helper()

	out, diags := templates.Apply(templates.Template{Name: "toy", Source: []byte(source)}, ordinary, where)
	if !diags.Empty() {
		t.Fatalf("the template was refused:\n%s", diags.Render())
	}

	var imports strings.Builder
	if len(out.Imports) > 0 {
		imports.WriteString("import (\n")
		for _, one := range out.Imports {
			imports.WriteString("\t" + one.String() + "\n")
		}
		imports.WriteString(")\n\n")
	}

	generated := "// Code generated by forge. DO NOT EDIT.\n\npackage model\n\n" +
		imports.String() + rendered(t, out) + "\n"

	if err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			{Name: "person.go", Content: []byte("package model\n\ntype Person struct {\n\tName string\n\tAge  int\n}\n")},
			{Name: "forge.gen.go", Content: []byte(generated), Generated: true},
		},
	}); err != nil {
		t.Errorf("%v\n\n%s", err, generated)
	}
}

// The container appears in more shapes than a receiver, and each of them is a
// place a rewrite can leave a type nobody declared.
func TestTheContainerInEveryShapeItTakes(t *testing.T) {
	compiles(t, "package tmpl\n\n"+
		"type Collection[T any] []T\n\n"+
		// A pointer receiver, which wraps the instantiation in a star.
		"func (c *Collection[T]) Add(v T) { *c = append(*c, v) }\n\n"+
		// A slice of it, a map to it, and a field of it.
		"type holder[T any] struct {\n"+
		"\tone  Collection[T]\n"+
		"\tmany []Collection[T]\n"+
		"\tkeys map[string]Collection[T]\n"+
		"}\n\n"+
		// Returned, converted, and built as a literal.
		"func (c Collection[T]) Copy() Collection[T] {\n"+
		"\tout := Collection[T]{}\n"+
		"\treturn Collection[T](append(out, c...))\n"+
		"}\n\n"+
		// Asserted out of an empty interface, which is the shape that reaches
		// the rewrite through a type assertion rather than a declaration.
		"func (c Collection[T]) Same(v any) bool {\n"+
		"\t_, ok := v.(Collection[T])\n"+
		"\treturn ok\n"+
		"}\n")
}

// A generic name used with type arguments is one node, and the arguments have
// to lose the element along with the declaration that took it.
func TestATemplateNameUsedWithTypeArguments(t *testing.T) {
	text := specialised(t, "package tmpl\n\n"+
		"type Collection[T any] []T\n\n"+
		"func zero[T any]() T { var v T; return v }\n\n"+
		"func pick[T, U any](v T, u U) U { return u }\n\n"+
		"func (c Collection[T]) First() Person {\n"+
		"\tif len(c) == 0 {\n\t\treturn zero[T]()\n\t}\n"+
		"\treturn pick[T, Person](c[0], c[0])\n"+
		"}\n", ordinary)

	for _, want := range []string{
		// The declaration lost the element, so the call loses the argument.
		"func personsZero() Person",
		"return personsZero()",
		// The declaration kept its other parameter, so the call keeps it.
		"func personsPick[U any](v Person, u U) U",
		"personsPick[Person](c[0], c[0])",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("the output does not hold %q:\n%s", want, text)
		}
	}
}

// There is one element and one declared name, so a template using its own
// container over something else has nowhere for the second specialisation to
// go — and a rewrite that dropped the difference would emit a type that says
// something it does not mean.
func TestTheContainerOverSomethingElse(t *testing.T) {
	reported := refused(t, "package tmpl\n\n"+
		"type Collection[T any] []T\n\n"+
		"func mapped[T, U any](c Collection[T], f func(T) U) Collection[U] { return nil }\n", ordinary)

	if !strings.Contains(reported, "FRG4911") {
		t.Errorf("a container over something else was rewritten:\n%s", reported)
	}
	if !strings.Contains(reported, "over something other than T") {
		t.Errorf("the failure does not say what is wrong:\n%s", reported)
	}
}

// A method's name lives on its receiver's type rather than in the package, so
// renaming it would rewrite the declaration and leave every call saying the
// name it used to have.
func TestAMethodNamedLikeAFunction(t *testing.T) {
	compiles(t, "package tmpl\n\n"+
		"type Collection[T any] []T\n\n"+
		"func count[T any](c Collection[T]) int { return len(c) }\n\n"+
		"func (c Collection[T]) count() int { return count(c) }\n\n"+
		"func (c Collection[T]) Len() int { return c.count() }\n")
}

// A key in a composite literal names a field of whatever is being built, very
// often somebody else's type — and nothing here can see the fields of a type it
// did not parse.
func TestALiteralKeyOnAForeignType(t *testing.T) {
	text := specialised(t, "package tmpl\n\n"+
		"import \"go/ast\"\n\n"+
		"type Collection[T any] []T\n\n"+
		"func Name() string { return \"x\" }\n\n"+
		"func (c Collection[T]) Ident() *ast.Ident { return &ast.Ident{Name: Name()} }\n", ordinary)

	if !strings.Contains(text, "&ast.Ident{Name: personsName()}") {
		t.Errorf("a foreign field was renamed with the template's own name:\n%s", text)
	}
}

// The selected half of a selector is a name on something else, and renaming it
// would rewrite a use of a member into a use of a package-level function.
func TestASelectedNameThatMatchesADeclaredOne(t *testing.T) {
	text := specialised(t, "package tmpl\n\n"+
		"import \"go/ast\"\n\n"+
		"type Collection[T any] []T\n\n"+
		"func Name() string { return \"x\" }\n\n"+
		"func (c Collection[T]) N(id *ast.Ident) string { return id.Name + Name() }\n", ordinary)

	if !strings.Contains(text, "id.Name + personsName()") {
		t.Errorf("a selected name was rewritten:\n%s", text)
	}
}

// Two names that become one is a package holding two declarations of it, and
// the prefix is what makes that possible.
func TestTwoNamesThatBecomeOne(t *testing.T) {
	reported := refused(t, "package tmpl\n\n"+
		"type Collection[T any] []T\n\n"+
		"type counted struct{ n int }\n\n"+
		"type Counted struct{ n int }\n", ordinary)

	if !strings.Contains(reported, "FRG4911") {
		t.Errorf("two names that become one were accepted:\n%s", reported)
	}
	if !strings.Contains(reported, "become the same name") {
		t.Errorf("the failure does not say what is wrong:\n%s", reported)
	}
}

// A rewrite naming things that are not names writes them into the file exactly
// as given, since a printer prints an identifier verbatim — so a declared name
// with a space in it is a file that does not parse, blamed on a declaration
// whose author wrote nothing wrong.
func TestARewriteNamingThingsThatAreNotNames(t *testing.T) {
	const source = "package tmpl\n\ntype Collection[T any] []T\n"

	cases := map[string]templates.Rewrite{
		"a declared name that is not one": {Param: "T", Subject: "Person", Container: "Collection", Declared: "not an ident"},
		"a subject that is not a type":    {Param: "T", Subject: "Person{}", Container: "Collection", Declared: "Persons"},
		"a subject that is not anything":  {Param: "T", Subject: "model.", Container: "Collection", Declared: "Persons"},
		"a prefix that is not one":        {Param: "T", Subject: "Person", Container: "Collection", Declared: "Persons", Prefix: "x-y"},
		"a declared name like the subject": {
			Param: "T", Subject: "Person", Container: "Collection", Declared: "Person",
		},
		"a blank parameter": {Param: "_", Subject: "Person", Container: "Collection", Declared: "Persons"},
	}

	for name, r := range cases {
		t.Run(name, func(t *testing.T) {
			if reported := refused(t, source, r); !strings.Contains(reported, "FRG4911") {
				t.Errorf("a rewrite that names nothing usable was carried out:\n%s", reported)
			}
		})
	}
}

// The type parameter is rewritten wherever it appears, so a second thing called
// by its name becomes a second thing called Person: a field the subject does not
// have, or a variable shadowing the subject's own type for a whole body.
func TestTheParameterUsedForSomethingElse(t *testing.T) {
	cases := map[string]string{
		"as a field":     "package tmpl\n\ntype Collection[T any] []T\n\ntype pair struct{ T int }\n",
		"as a parameter": "package tmpl\n\ntype Collection[T any] []T\n\nfunc (c Collection[T]) N(T int) int { return T }\n",
		"as a local":     "package tmpl\n\ntype Collection[T any] []T\n\nfunc (c Collection[T]) N() int { T := len(c); return T }\n",
		"as a range variable": "package tmpl\n\ntype Collection[T any] []T\n\n" +
			"func (c Collection[T]) N() int {\n\tn := 0\n\tfor T := range c {\n\t\tn += T\n\t}\n\treturn n\n}\n",
	}

	for name, source := range cases {
		t.Run(name, func(t *testing.T) {
			if reported := refused(t, source, ordinary); !strings.Contains(reported, "FRG4912") {
				t.Errorf("the parameter's name was reused and rewritten anyway:\n%s", reported)
			}
		})
	}
}

// A local declared with var is a local, whatever the rule's examples say.
func TestADeclaredNameReusedForALocalVariable(t *testing.T) {
	const source = "package tmpl\n\ntype Collection[T any] []T\n\n" +
		"type counted struct{ n int }\n\n" +
		"func (c Collection[T]) N() int { var counted int; return counted }\n"

	if reported := refused(t, source, ordinary); !strings.Contains(reported, "FRG4912") {
		t.Errorf("a name reused for a variable was rewritten anyway:\n%s", reported)
	}
}

// A template calls a package by the name it imported it under, so an import
// block written from the path alone would leave the bodies naming a package
// that is not there.
func TestAnImportBoundToAName(t *testing.T) {
	compiles(t, "package tmpl\n\n"+
		"import (\n\tseq \"iter\"\n\t\"slices\"\n)\n\n"+
		"type Collection[T any] []T\n\n"+
		"func (c Collection[T]) All() seq.Seq[T] { return slices.Values(c) }\n")
}

// An import written for its effect alone has no name to call it by, and one
// written into the file scope has every name in it.
func TestImportsWithNoNameOfTheirOwn(t *testing.T) {
	compiles(t, "package tmpl\n\n"+
		"import (\n\t_ \"embed\"\n\t. \"strings\"\n)\n\n"+
		"type Collection[T any] []T\n\n"+
		"func (c Collection[T]) Shout(s string) string { return ToUpper(s) }\n")
}

// A template declaring a type called by its parameter's name is legal Go — the
// parameter shadows it inside the container — and unrewritable: one of the two
// would have to keep a name that means the other, and the name the parameter
// takes is the author's own subject.
func TestATemplateDeclaringTheParametersName(t *testing.T) {
	reported := refused(t, "package tmpl\n\n"+
		"type Collection[T any] []T\n\n"+
		"type T struct{ n int }\n", ordinary)

	if !strings.Contains(reported, "FRG4911") {
		t.Errorf("a type named like the parameter was rewritten anyway:\n%s", reported)
	}
	if !strings.Contains(reported, "also the name of its type parameter") {
		t.Errorf("the failure does not say what is wrong:\n%s", reported)
	}
}

// Two names that become one is reported the same way twice, since a message
// picked out of a map is a different message each run and the author reading it
// cannot tell whether anything changed.
func TestWhichCollisionIsReported(t *testing.T) {
	const source = "package tmpl\n\n" +
		"type Collection[T any] []T\n\n" +
		"type counted struct{ n int }\n\ntype Counted struct{ n int }\n\n" +
		"type seen struct{ n int }\n\ntype Seen struct{ n int }\n\n" +
		"type held struct{ n int }\n\ntype Held struct{ n int }\n\n" +
		"type used struct{ n int }\n\ntype Used struct{ n int }\n"

	first := refused(t, source, ordinary)
	if !strings.Contains(first, "become the same name") {
		t.Fatalf("names that become one were accepted:\n%s", first)
	}

	for range 50 {
		if again := refused(t, source, ordinary); again != first {
			t.Fatalf("one template was refused two ways:\n%s\n---\n%s", first, again)
		}
	}
}

// A helper generic over something of its own keeps what it was given, since the
// declaration it names still takes it — which is the other half of the rule that
// refuses the container over something else.
func TestAHelperInstantiatedWithSomethingElse(t *testing.T) {
	text := specialised(t, "package tmpl\n\n"+
		"type Collection[T any] []T\n\n"+
		"type box[U any] struct{ v U }\n\n"+
		"func (c Collection[T]) Boxed() box[int] { return box[int]{v: len(c)} }\n", ordinary)

	for _, want := range []string{"type personsBox[U any] struct", "personsBox[int]{v: len(c)}"} {
		if !strings.Contains(text, want) {
			t.Errorf("the output does not hold %q:\n%s", want, text)
		}
	}
}

// A name the template does not declare is somebody else's, and instantiating it
// is their business: a generic reached through a dot import takes the arguments
// it was written with.
func TestAGenericTheTemplateDoesNotDeclare(t *testing.T) {
	text := specialised(t, "package tmpl\n\n"+
		"import \"slices\"\n\n"+
		"type Collection[T any] []T\n\n"+
		"func (c Collection[T]) Sorted(less func(a, b T) int) []T {\n"+
		"\treturn slices.SortedFunc(slices.Values(c), less)\n}\n", ordinary)

	if !strings.Contains(text, "slices.SortedFunc(slices.Values(c), less)") {
		t.Errorf("a foreign generic was rewritten:\n%s", text)
	}
}

// A rewrite whose parameter and container are one name is refused before
// anything is read, since the two mean different things everywhere.
func TestAParameterNamedLikeTheContainer(t *testing.T) {
	reported := refused(t, "package tmpl\n\ntype Collection[T any] []T\n", templates.Rewrite{
		Param: "Collection", Subject: "Person", Container: "Collection", Declared: "Persons", Prefix: "persons",
	})

	if !strings.Contains(reported, "the type parameter and the container have the same name") {
		t.Errorf("the failure does not say what is wrong:\n%s", reported)
	}
}

// A name that binds nothing new is not a second use of one: assigning to a
// variable that already exists, or ranging over existing ones, is the template
// using what it declared rather than hiding it.
func TestNamesThatBindNothingNew(t *testing.T) {
	const source = "package tmpl\n\ntype Collection[T any] []T\n\n" +
		"var counted int\n\n" +
		"func (c Collection[T]) N() int {\n" +
		"\tcounted = len(c)\n" +
		"\tfor counted = range 3 {\n\t}\n" +
		"\treturn counted\n}\n"

	out, diags := templates.Apply(templates.Template{Name: "toy", Source: []byte(source)}, ordinary, where)
	if !diags.Empty() {
		t.Fatalf("a template using its own variable was refused:\n%s", diags.Render())
	}

	text := rendered(t, out)
	for _, want := range []string{"var personsCounted int", "personsCounted = len(c)", "for personsCounted = range 3"} {
		if !strings.Contains(text, want) {
			t.Errorf("the output does not hold %q:\n%s", want, text)
		}
	}
}
