package goldentest_test

import (
	"fmt"
	"go/build"
	"runtime"
	"strings"
	"testing"

	"github.com/okian/forge/internal/goldentest"
)

// subject is the fixture a generated file is compiled against, as a layer's
// golden test would supply it.
var subject = goldentest.Source{
	Name: "person.go",
	Content: []byte("package model\n\n" +
		"type Person struct {\n" +
		"\tName string `json:\"name\"`\n" +
		"\tAge  int    `json:\"age\"`\n" +
		"}\n"),
}

// generated returns a file in the shape generation produces.
func generated(body string) goldentest.Source {
	return goldentest.Source{
		Name:      "zz_forge_persons.go",
		Content:   []byte("// Code generated by forge. DO NOT EDIT.\n\npackage model\n\n" + body),
		Generated: true,
	}
}

// under builds a generated file guarded by a build constraint.
func under(name, build, body string) goldentest.Source {
	return goldentest.Source{
		Name:      name,
		Content:   []byte("//go:build " + build + "\n\n// Code generated by forge. DO NOT EDIT.\n\npackage model\n\n" + body),
		Generated: true,
	}
}

// against builds a package holding the fixture and one generated file.
func against(body string) goldentest.Package {
	return goldentest.Package{
		Path:  "model",
		Files: []goldentest.Source{subject, generated(body)},
	}
}

// Output that compiles against the fixture it was generated for is what the
// gate exists to confirm, and it has to be able to say so.
func TestOutputThatCompiles(t *testing.T) {
	err := goldentest.Compiles(against(
		"import (\n\t\"iter\"\n\t\"slices\"\n)\n\n" +
			"type Persons []Person\n\n" +
			"func (p Persons) All() iter.Seq[Person] { return slices.Values(p) }\n\n" +
			"func (p Persons) Len() int { return len(p) }\n"))
	if err != nil {
		t.Errorf("output that compiles was refused: %v", err)
	}
}

// A golden is a recorded copy of something, and a recording of something broken
// is still a recording. Compiling is what says the output was ever right.
func TestOutputThatDoesNotCompile(t *testing.T) {
	cases := map[string]struct {
		body     string
		fragment string
	}{
		"a type nobody declared": {
			body:     "func (p Persons) First() Person { return p[0] }\n",
			fragment: "undefined: Persons",
		},
		"a field the subject does not have": {
			body:     "type Persons []Person\n\nfunc (p Persons) Firsts() []string {\n\treturn []string{p[0].Nickname}\n}\n",
			fragment: "Nickname",
		},
		"a method that returns the wrong thing": {
			body:     "type Persons []Person\n\nfunc (p Persons) Len() string { return len(p) }\n",
			fragment: "cannot use",
		},
		"an import it does not use": {
			body:     "import \"iter\"\n\ntype Persons []Person\n",
			fragment: "not used",
		},
		"a type argument the constraint refuses": {
			body: "import \"cmp\"\n\n" +
				"type Persons []Person\n\n" +
				"func highest[T cmp.Ordered](in []T) T { return in[0] }\n\n" +
				"func (p Persons) Highest() Person { return highest(p) }\n",
			fragment: "does not satisfy",
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			err := goldentest.Compiles(against(tc.body))

			if err == nil {
				t.Fatal("output that does not compile was accepted")
			}
			if !strings.Contains(err.Error(), tc.fragment) {
				t.Errorf("failure does not mention %q:\n%v", tc.fragment, err)
			}
		})
	}
}

// Generated code imports the standard library and the package it lands in, and
// never a third party — a generated file that needed one would version-skew
// against the binary that wrote it. Refusing the import is what makes that a
// property rather than a paragraph.
func TestOutputThatReachesOutsideTheStandardLibrary(t *testing.T) {
	cases := map[string]string{
		"a package that exists nowhere":   "import \"example.com/somewhere/other\"\n\ntype Persons []other.Thing\n",
		"a package of this very module":   "import \"github.com/okian/forge/internal/model\"\n\ntype Persons []model.Field\n",
		"a dependency of this module":     "import \"golang.org/x/tools/go/packages\"\n\ntype Persons []packages.Package\n",
		"one imported only for its init":  "import _ \"golang.org/x/tools/go/packages\"\n\ntype Persons []Person\n",
		"one imported under another name": "import pkgs \"golang.org/x/tools/go/packages\"\n\ntype Persons []pkgs.Package\n",
		"one imported into the file scope": "import . \"golang.org/x/tools/go/packages\"\n\n" +
			"type Persons []Package\n",
	}

	for name, body := range cases {
		t.Run(name, func(t *testing.T) {
			err := goldentest.Compiles(against(body))

			if err == nil {
				t.Fatal("output reaching outside the standard library was accepted")
			}
			if !strings.Contains(err.Error(), "not in the standard library") {
				t.Errorf("failure does not say what it refused:\n%v", err)
			}
		})
	}
}

// The fixture is held to the same rule. It stands in for the package the output
// lands in, and a fixture that could reach anywhere would let a layer's test
// prove its output compiles against something the real package cannot have.
func TestAFixtureThatReachesOutsideTheStandardLibrary(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			{Name: "person.go", Content: []byte("package model\n\nimport \"golang.org/x/tools/go/packages\"\n\ntype Person struct {\n\tPkg packages.Package\n}\n")},
			generated("type Persons []Person\n"),
		},
	})

	if err == nil {
		t.Fatal("a fixture reaching outside the standard library was accepted")
	}
	if !strings.Contains(err.Error(), "not in the standard library") {
		t.Errorf("failure does not say what it refused:\n%v", err)
	}
}

// A package given alongside the one under test resolves, so that output naming
// a type the subject reached in a package of its own can be compiled.
//
// It is the case that matters most for an element layer: what it writes about a
// struct in another package is a function in this one, naming that package's
// types, and a gate that could only see one package at a time could not build
// the very case where a method could not be declared.
func TestAPackageGivenAlongsideResolves(t *testing.T) {
	beside := goldentest.Package{
		Path: "example.com/model/domain",
		Files: []goldentest.Source{
			{Name: "domain.go", Content: []byte("package domain\n\ntype Place struct {\n\tCity string\n}\n")},
		},
	}

	err := goldentest.Compiles(goldentest.Package{
		Path:     "example.com/model",
		Requires: []goldentest.Package{beside},
		Files: []goldentest.Source{
			{Name: "person.go", Content: []byte("package model\n\nimport \"example.com/model/domain\"\n\ntype Person struct {\n\tHome domain.Place\n}\n")},
			generated("import \"example.com/model/domain\"\n\n" +
				"func cloneDomainPlace(v domain.Place) domain.Place { return v }\n"),
		},
	})
	if err != nil {
		t.Errorf("output naming a package given alongside was refused: %v", err)
	}
}

// A package given alongside may have packages of its own, and they resolve too.
//
// The field is a list of packages, so nesting is expressible; a caller who
// nested one and got a missing-import error would be reading a complaint about
// their fixture when the harness was the thing that could not see it.
func TestAPackageGivenAlongsideMayHaveItsOwn(t *testing.T) {
	deepest := goldentest.Package{
		Path: "example.com/model/domain/geo",
		Files: []goldentest.Source{
			{Name: "geo.go", Content: []byte("package geo\n\ntype Point struct {\n\tLat float64\n}\n")},
		},
	}

	beside := goldentest.Package{
		Path:     "example.com/model/domain",
		Requires: []goldentest.Package{deepest},
		Files: []goldentest.Source{
			{Name: "domain.go", Content: []byte("package domain\n\nimport \"example.com/model/domain/geo\"\n\ntype Place struct {\n\tAt geo.Point\n}\n")},
		},
	}

	err := goldentest.Compiles(goldentest.Package{
		Path:     "example.com/model",
		Requires: []goldentest.Package{beside},
		Files: []goldentest.Source{
			{Name: "person.go", Content: []byte("package model\n\nimport \"example.com/model/domain\"\n\ntype Person struct {\n\tHome domain.Place\n}\n")},
			generated("import \"example.com/model/domain\"\n\n" +
				"func cloneDomainPlace(v domain.Place) domain.Place { return v }\n"),
		},
	})
	if err != nil {
		t.Errorf("a package given alongside could not see its own: %v", err)
	}
}

// What is given alongside has to compile too, and a failure in one says which
// package it was in.
func TestAPackageGivenAlongsideIsCheckedItself(t *testing.T) {
	beside := goldentest.Package{
		Path: "example.com/model/domain",
		Files: []goldentest.Source{
			{Name: "domain.go", Content: []byte("package domain\n\ntype Place struct {\n\tCity nothing\n}\n")},
		},
	}

	err := goldentest.Compiles(goldentest.Package{
		Path:     "example.com/model",
		Requires: []goldentest.Package{beside},
		Files:    []goldentest.Source{generated("type Persons []int\n")},
	})

	if err == nil {
		t.Fatal("a package given alongside that does not compile was accepted")
	}
	if !strings.Contains(err.Error(), "example.com/model/domain does not compile") {
		t.Errorf("failure does not say which package was wrong:\n%v", err)
	}
}

// The standard library itself has to keep resolving, including the parts a
// generated file leans on hardest.
func TestOutputThatReachesIntoTheStandardLibrary(t *testing.T) {
	err := goldentest.Compiles(against(
		"import (\n\t\"encoding/json/v2\"\n\t\"iter\"\n)\n\n" +
			"type Persons []Person\n\n" +
			"func (p Persons) All() iter.Seq[Person] {\n" +
			"\treturn func(yield func(Person) bool) {\n" +
			"\t\tfor _, one := range p {\n" +
			"\t\t\tif !yield(one) {\n\t\t\t\treturn\n\t\t\t}\n" +
			"\t\t}\n\t}\n}\n\n" +
			"func (p Persons) Bytes() ([]byte, error) { return json.Marshal(p) }\n"))
	if err != nil {
		t.Errorf("output importing the standard library was refused: %v", err)
	}
}

// Output that will not parse is a different failure from output that will not
// type-check, and saying which is the difference between one look at the file
// and several.
func TestOutputThatDoesNotParse(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path:  "model",
		Files: []goldentest.Source{generated("type Persons struct {\n")},
	})

	if err == nil {
		t.Fatal("output that does not parse was accepted")
	}
	if !strings.Contains(err.Error(), "does not parse") {
		t.Errorf("failure does not say the output would not parse:\n%v", err)
	}
}

// A parse reports a list, and printing that list as one error shows its first
// entry and a count of the rest.
func TestEveryReasonOutputDoesNotParse(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path:  "model",
		Files: []goldentest.Source{generated("func One() { return ] }\n\nfunc Two() { return ] }\n")},
	})

	if err == nil {
		t.Fatal("output that does not parse was accepted")
	}
	if strings.Contains(err.Error(), "more errors") {
		t.Errorf("the failure counts what it did not print:\n%v", err)
	}
	if lines := strings.Count(err.Error(), "zz_forge_persons.go:"); lines < 2 {
		t.Errorf("only %d of the parse failures were reported:\n%v", lines, err)
	}
}

// A file that does not parse must not hide what a file that does would have
// said, and a first failing file must not stop the ones after it being read.
func TestEveryFileThatDoesNotParse(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			{Name: "person.go", Content: []byte("package model\n\ntype Person struct {\n")},
			generated("type Persons struct {\n"),
		},
	})

	if err == nil {
		t.Fatal("output that does not parse was accepted")
	}
	for _, want := range []string{"person.go", "zz_forge_persons.go"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the failure does not mention %s:\n%v", want, err)
		}
	}
}

// Generated output is committed, so output gofmt would move is a diff waiting
// for the first person who runs the formatter over the tree. The lint
// configuration excludes generated files from the formatter on the grounds that
// this suite checks them, which is only true if it does.
func TestOutputThatIsNotFormatted(t *testing.T) {
	err := goldentest.Compiles(against("type   Persons   []Person\n"))

	if err == nil {
		t.Fatal("output gofmt would rewrite was accepted")
	}
	if !strings.Contains(err.Error(), "not formatted") {
		t.Errorf("failure does not say the output was unformatted:\n%v", err)
	}
}

// A fixture is laid out by whoever wrote the test, and holding it to gofmt
// would be this package having an opinion about somebody else's file.
func TestAFixtureThatIsNotFormatted(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			{Name: "person.go", Content: []byte("package model\n\ntype    Person   struct{ Name string }\n")},
			generated("type Persons []Person\n"),
		},
	})
	if err != nil {
		t.Errorf("a fixture was held to gofmt: %v", err)
	}
}

// Generation emits files constrained against each other, so which files are in
// a package has more than one answer and each one has to type-check on its own.
// Reading them all at once reports a redeclaration that exists in no build.
func TestEachBuildConfiguration(t *testing.T) {
	pkg := goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			subject,
			{
				Name:      "zz_forge_persons.go",
				Content:   []byte("//go:build !forgespec\n\npackage model\n\ntype Persons []Person\n\nfunc (p Persons) Len() int { return len(p) }\n"),
				Generated: true,
			},
			{
				Name:      "zz_forge_stubs.go",
				Content:   []byte("//go:build forgespec\n\npackage model\n\ntype Persons []Person\n\nfunc (p Persons) Len() int { panic(\"forge stub\") }\n"),
				Generated: true,
			},
		},
	}

	if err := goldentest.Compiles(pkg); err != nil {
		t.Errorf("the ordinary build was refused: %v", err)
	}

	pkg.Tags = []string{"forgespec"}
	if err := goldentest.Compiles(pkg); err != nil {
		t.Errorf("the tagged build was refused: %v", err)
	}
}

// The constraint has to hold for what it excludes as much as for what it keeps,
// or a stub file could lean on something only the file it replaces declares and
// nothing would notice.
func TestAConfigurationThatExcludesWhatItNeeds(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Tags: []string{"forgespec"},
		Files: []goldentest.Source{
			subject,
			{
				Name:      "zz_forge_persons.go",
				Content:   []byte("//go:build !forgespec\n\npackage model\n\ntype Persons []Person\n"),
				Generated: true,
			},
			{
				Name:      "zz_forge_stubs.go",
				Content:   []byte("//go:build forgespec\n\npackage model\n\nfunc (p Persons) Len() int { panic(\"forge stub\") }\n"),
				Generated: true,
			},
		},
	})

	if err == nil {
		t.Fatal("a configuration missing the type it declares methods on was accepted")
	}
	if !strings.Contains(err.Error(), "undefined: Persons") {
		t.Errorf("failure does not name what the configuration lacked:\n%v", err)
	}
}

// A constraint nobody can read is a mistake in the output, and quietly keeping
// the file would compile a configuration that does not exist.
func TestABuildConstraintThatDoesNotRead(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{subject, {
			Name:      "zz_forge_persons.go",
			Content:   []byte("//go:build forgespec &&\n\npackage model\n\ntype Persons []Person\n"),
			Generated: true,
		}},
	})

	if err == nil {
		t.Fatal("a constraint that does not read was accepted")
	}
	if !strings.Contains(err.Error(), "build constraint") {
		t.Errorf("failure does not say the constraint was the problem:\n%v", err)
	}
}

// The same text below the package clause is a comment about a constraint rather
// than one, which is how the go command reads it too. Were it read as a
// constraint, this file would be excluded and the type it declares undefined.
func TestABuildConstraintTooLateToBeOne(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			{Name: "person.go", Content: []byte("package model\n\n//go:build forgespec\n\ntype Person struct{ Name string }\n")},
			generated("type Persons []Person\n"),
		},
	})
	if err != nil {
		t.Errorf("a file whose constraint comes too late was excluded: %v", err)
	}
}

// Compiling is not the whole of being right. These are the mistakes a generator
// can make that the type-checker has no opinion about, one per analysis — so an
// analysis that has quietly stopped catching anything shows up as a test that
// passes when it should not.
func TestOutputThatCompilesAndDoesNotHoldUp(t *testing.T) {
	cases := map[string]struct {
		body     string
		analysis string
	}{
		// A tag written without the quotes around its value is a tag that says
		// nothing, and a codec generated from it encodes the wrong names.
		"a struct tag that is not one": {
			body:     "type Persons struct {\n\tItems []Person `json:name`\n}\n",
			analysis: "structtag",
		},
		// A field set from itself is a projection that lost its source.
		"a field assigned to itself": {
			body: "type Persons []Person\n\n" +
				"func (p Persons) Rename() {\n\tp[0].Name = p[0].Name\n}\n",
			analysis: "assign",
		},
		// The same condition on both sides of an operator is a template that
		// substituted one field twice.
		"a condition repeated": {
			body: "type Persons []Person\n\n" +
				"func (p Persons) Any() bool { return len(p) > 0 && len(p) > 0 }\n",
			analysis: "bools",
		},
		// Copying a value that holds a lock copies the lock, and the copy
		// guards nothing.
		"a lock copied by value": {
			body: "import \"sync\"\n\n" +
				"type Persons struct {\n\tmu    sync.Mutex\n\titems []Person\n}\n\n" +
				"func (p Persons) Copy() Persons { return p }\n",
			analysis: "copylocks",
		},
		// Comparing a function to nil compares the function itself, which is
		// never nil, rather than calling it.
		"a comparison against a function": {
			body: "type Persons []Person\n\n" +
				"func (p Persons) Len() int { return len(p) }\n\n" +
				"func (p Persons) Empty() bool { return p.Len == nil }\n",
			analysis: "nilfunc",
		},
		// Code after a return is code that was meant to run.
		"code after a return": {
			body: "type Persons []Person\n\n" +
				"func (p Persons) Len() int {\n\treturn len(p)\n\treturn 0\n}\n",
			analysis: "unreachable",
		},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			err := goldentest.Compiles(against(tc.body))

			if err == nil {
				t.Fatalf("output the %s analysis objects to was accepted", tc.analysis)
			}
			if !strings.Contains(err.Error(), tc.analysis) {
				t.Errorf("failure does not name the analysis that objected:\n%v", err)
			}
			// The position is the payload: a finding nobody can navigate to is
			// one somebody reads twice and acts on once.
			if !strings.Contains(err.Error(), "zz_forge_persons.go:") {
				t.Errorf("failure does not say where in the file:\n%v", err)
			}
		})
	}
}

// A package with nothing in it is a mistake in the test rather than in the
// output, and saying so is quicker than a type-checker's answer to it.
func TestAPackageWithNoFiles(t *testing.T) {
	if err := goldentest.Compiles(goldentest.Package{Path: "model"}); err == nil {
		t.Error("a package with no files was accepted")
	}
}

// The path is what a failure is reported under and what the package is
// type-checked as, and a package without one reports against nothing.
func TestAPackageWithNoPath(t *testing.T) {
	if err := goldentest.Compiles(goldentest.Package{Files: []goldentest.Source{subject}}); err == nil {
		t.Error("a package with no import path was accepted")
	}
}

// Two files under one name would each be recorded over the other's golden, so
// the run that wrote them passes and the next one fails against whichever won.
func TestAPackageThatNamesOneFileTwice(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path:  "model",
		Files: []goldentest.Source{subject, generated("type A int\n"), generated("type B int\n")},
	})

	if err == nil {
		t.Fatal("a package naming one file twice was accepted")
	}
	if !strings.Contains(err.Error(), "zz_forge_persons.go") {
		t.Errorf("failure does not name the file that was repeated:\n%v", err)
	}
}

// A file with no name has no golden to be recorded under and no position to be
// reported against.
func TestAPackageWithAnUnnamedFile(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path:  "model",
		Files: []goldentest.Source{{Content: []byte("package model\n")}},
	})

	if err == nil {
		t.Error("a file with no name was accepted")
	}
}

// A failure reads the same way twice, or a suite that runs on every layer
// produces a different message for one mistake depending on the day.
func TestFailuresAreReportedInOneOrder(t *testing.T) {
	pkg := against("type Persons struct {\n\tItems []Person `json:name`\n\tMore  []Person `db:more`\n}\n")

	first := goldentest.Compiles(pkg)
	if first == nil {
		t.Fatal("output the analyses object to was accepted")
	}

	for range 5 {
		if again := goldentest.Compiles(pkg); again.Error() != first.Error() {
			t.Fatalf("one package failed two ways:\n%v\n---\n%v", first, again)
		}
	}
}

// Findings are reported down the file rather than in whichever order the
// analyses happened to run, since a reader works through a file once.
func TestFindingsAreReportedDownTheFile(t *testing.T) {
	err := goldentest.Compiles(against(
		"type Persons []Person\n\n" +
			"func (p Persons) Len() int {\n\treturn len(p)\n\treturn 0\n}\n\n" +
			"func (p Persons) Rename() {\n\tp[0].Name = p[0].Name\n}\n"))

	if err == nil {
		t.Fatal("output the analyses object to was accepted")
	}

	report := err.Error()
	if !strings.Contains(report, "unreachable") || !strings.Contains(report, "assign") {
		t.Fatalf("both analyses were expected to object:\n%v", err)
	}
	if strings.Index(report, "unreachable") > strings.Index(report, "assign") {
		t.Errorf("the later finding was reported first:\n%v", err)
	}
}

// Type errors are reported in one order too, and the order the files arrive in
// is the caller's — a layer test that builds its file list from a map would
// otherwise report differently every run.
func TestTypeErrorsDoNotFollowTheOrderOfTheFiles(t *testing.T) {
	broken := goldentest.Source{
		Name:    "person.go",
		Content: []byte("package model\n\ntype Person struct{ Name string }\n\nvar _ = missingFromTheFixture\n"),
	}
	output := generated("var _ = missingFromTheOutput\n")

	forwards := goldentest.Compiles(goldentest.Package{Path: "model", Files: []goldentest.Source{broken, output}})
	backwards := goldentest.Compiles(goldentest.Package{Path: "model", Files: []goldentest.Source{output, broken}})

	if forwards == nil || backwards == nil {
		t.Fatal("output that does not compile was accepted")
	}
	if forwards.Error() != backwards.Error() {
		t.Errorf("the order of the files reached the report:\n%v\n---\n%v", forwards, backwards)
	}
}

// A tag this harness answers differently from go build selects a different set
// of files, and then certifies a configuration that no build produces. These
// are the tags a generated file is most likely to carry.
func TestTheTagsAGeneratedFileCarries(t *testing.T) {
	held := map[string]bool{
		// The language floor. A layer emitting an implementation under the
		// version it needs and a fallback under the negation would otherwise
		// have the fallback checked and the implementation dropped.
		"go1.1":  true,
		"go1.27": true,
		"go1.99": false,

		// The system it is being built for.
		runtime.GOOS:   true,
		runtime.GOARCH: true,
		"unix":         runtime.GOOS != "windows" && runtime.GOOS != "plan9" && runtime.GOOS != "js" && runtime.GOOS != "wasip1",

		// The toolchain building it.
		"gc":     true,
		"gccgo":  false,
		"purego": false,
		"cgo":    build.Default.CgoEnabled,

		// And one nobody has ever set.
		"forgespec": false,
	}

	for tag, want := range held {
		t.Run(tag, func(t *testing.T) {
			// The constrained file declares the type; an unconstrained one uses
			// it. Whether the package compiles is then the whole of the answer
			// to whether the constraint held — asking the harness directly
			// would only ask it to agree with itself.
			err := goldentest.Compiles(goldentest.Package{
				Path: "model",
				Files: []goldentest.Source{
					subject,
					under("zz_forge_impl.go", tag, "type Persons []Person\n"),
					generated("var _ = func(p Persons) int { return len(p) }\n"),
				},
			})

			if held := err == nil; held != want {
				t.Errorf("with //go:build %s the file was held %v (%v)", tag, held, err)
			}
		})
	}
}

// Two files guarded by unrelated tags is what tells an evaluator that answers
// honestly from one that answers the same way to everything: any consistent
// answer keeps exactly one file out of a tag and its negation.
func TestTagsThatHaveNothingToDoWithEachOther(t *testing.T) {
	pkg := goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			subject,
			under("zz_forge_one.go", "alpha", "type One []Person\n"),
			under("zz_forge_two.go", "zulu", "type Two []Person\n"),
		},
	}

	// Neither tag is set, so neither type is declared and a file that mentions
	// one is the way to ask whether it is there.
	pkg.Files = append(pkg.Files, generated("var _ = func() { var _ One; var _ Two }\n"))

	err := goldentest.Compiles(pkg)
	if err == nil {
		t.Fatal("types declared only under tags nobody set were found anyway")
	}
	for _, want := range []string{"undefined: One", "undefined: Two"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the failure does not mention %q:\n%v", want, err)
		}
	}

	pkg.Tags = []string{"alpha", "zulu"}
	if err := goldentest.Compiles(pkg); err != nil {
		t.Errorf("with both tags set the files were still excluded: %v", err)
	}
}

// A configuration that leaves nothing to compile is a mistake in the tag list
// rather than in the package, and being sent to look at the wrong one costs a
// layer author the time it takes to rule the package out.
func TestAConfigurationThatExcludesEverything(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path:  "model",
		Tags:  []string{"forgespec"},
		Files: []goldentest.Source{under("zz_forge_persons.go", "!forgespec", "type Persons []int\n")},
	})

	if err == nil {
		t.Fatal("a configuration with nothing left in it was accepted")
	}
	if !strings.Contains(err.Error(), "constrained out") || !strings.Contains(err.Error(), "forgespec") {
		t.Errorf("the failure does not say the tags excluded everything:\n%v", err)
	}

	// And the ordinary build, which is a configuration with no tags in it at
	// all, has to be describable too.
	err = goldentest.Compiles(goldentest.Package{
		Path:  "model",
		Files: []goldentest.Source{under("zz_forge_persons.go", "forgespec", "type Persons []int\n")},
	})

	if err == nil {
		t.Fatal("a configuration with nothing left in it was accepted")
	}
	if !strings.Contains(err.Error(), "with no tags") {
		t.Errorf("the failure does not describe the configuration:\n%v", err)
	}
}

// Generation writes one constraint into every file of a configuration, so a
// report that does not name the file sends the reader through all of them.
func TestWhichFileHasTheConstraintThatDoesNotRead(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			subject,
			under("zz_forge_persons.go", "forgespec &&", "type Persons []Person\n"),
		},
	})

	if err == nil {
		t.Fatal("a constraint that does not read was accepted")
	}
	if !strings.Contains(err.Error(), "zz_forge_persons.go:1") {
		t.Errorf("the failure does not say which file, or where in it:\n%v", err)
	}
}

// Saying that gofmt would rewrite a file is a report the reader has to redo by
// hand; saying where it would rewrite it is one they can act on.
func TestWhereOutputIsNotFormatted(t *testing.T) {
	err := goldentest.Compiles(against(
		"type Persons []Person\n\nfunc (p Persons) Len() int {\n\treturn  len(p)\n}\n"))

	if err == nil {
		t.Fatal("output gofmt would rewrite was accepted")
	}
	if !strings.Contains(err.Error(), "first difference at line") {
		t.Errorf("the failure does not say where gofmt would rewrite it:\n%v", err)
	}
}

// Formatting is the last thing checked, because a file gofmt would move still
// parses and still type-checks — and being sent to fix a space, only to be told
// about a type error on the next run, is two runs for one look at the file.
func TestFormattingIsNotWhatHidesARealProblem(t *testing.T) {
	err := goldentest.Compiles(against("type   Persons   []Person\n\nvar _ = missingEntirely\n"))

	if err == nil {
		t.Fatal("output that does not compile was accepted")
	}
	if !strings.Contains(err.Error(), "missingEntirely") {
		t.Errorf("the formatting report hid the type error:\n%v", err)
	}
}

// Type errors read down the file the way findings do. Agreeing with themselves
// across two orderings is not the same as being in the order somebody reads.
func TestTypeErrorsReadDownThePackage(t *testing.T) {
	err := goldentest.Compiles(goldentest.Package{
		Path: "model",
		Files: []goldentest.Source{
			{Name: "person.go", Content: []byte("package model\n\ntype Person struct{ Name string }\n\nvar _ = missingFromTheFixture\n")},
			generated("var _ = missingFromTheOutput\n"),
		},
	})

	if err == nil {
		t.Fatal("output that does not compile was accepted")
	}

	report := err.Error()
	if strings.Index(report, "person.go") > strings.Index(report, "zz_forge_persons.go") {
		t.Errorf("the later file is reported first:\n%v", err)
	}
}

// A failure holding a line of characters wider than a byte must not announce a
// clip that did not happen — which is the shape this repository's own comments
// take.
func TestALineOfWideCharacters(t *testing.T) {
	line := "// " + strings.Repeat("—", 70)
	if len(line) <= 200 {
		t.Fatalf("the line is %d bytes, which is not the case under test", len(line))
	}

	watching := recorded(t, line+"\n")
	goldentest.Compare(watching, "out.txt", []byte(line+" \n"))

	if !watching.failed {
		t.Fatal("output that does not match what was recorded was accepted")
	}
	if strings.Contains(watching.heard(), "characters more") {
		t.Errorf("a line short enough to read was reported as shortened:\n%s", watching.heard())
	}
	if !strings.Contains(watching.heard(), fmt.Sprintf("%q", line+" ")) {
		t.Errorf("the failure does not show the line in full:\n%s", watching.heard())
	}
}

// The one keystroke that accepts a deliberate change belongs in the failure
// that asks for the decision.
func TestTheFailureSaysHowToAcceptTheChange(t *testing.T) {
	watching := recorded(t, "what was recorded\n")

	goldentest.Compare(watching, "out.txt", []byte("what it produces now\n"))

	if !strings.Contains(watching.heard(), "-update") {
		t.Errorf("the failure does not say how to accept the change:\n%s", watching.heard())
	}
}

// And one long enough to shorten is counted the same way it was measured, or
// the reader is told a number that describes neither what was cut nor what is
// left.
func TestALongLineOfWideCharacters(t *testing.T) {
	line := strings.Repeat("—", 250)

	watching := recorded(t, line+"\n")
	goldentest.Compare(watching, "out.txt", []byte(line+" \n"))

	if !watching.failed {
		t.Fatal("output that does not match what was recorded was accepted")
	}
	// Two hundred and fifty characters, two hundred of them shown.
	if !strings.Contains(watching.heard(), "and 50 characters more") {
		t.Errorf("the failure does not say how much was left out:\n%s", watching.heard())
	}
	if strings.Contains(watching.heard(), strings.Repeat("—", 201)) {
		t.Errorf("more of the line was shown than the failure says:\n%s", watching.heard())
	}
}
