// Code generated by forge. DO NOT EDIT.
//
// forge v1.2.3
// markers v1.2.3
// go go1.27.0
// inputs 013993914a2a960c

//go:build !forgespec

package model

import (
	"bytes"
	"cmp"
	"encoding"
	"encoding/base64"
	"encoding/json/v2"
	"errors"
	"fmt"
	"io"
	"iter"
	"log/slog"
	"math"
	"slices"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode/utf8"
	"unsafe"
)

// PeopleSeq is a lazy view over the elements of People.
type PeopleSeq struct {
	Seq[Person]
}

// Seq returns a lazy view over the elements. Its combinators are the shared
// Seq[Person] view's.
func (c People) Seq() PeopleSeq {
	return PeopleSeq{Seq[Person](c.All())}
}

// IDs returns the ID of every element, in order.
func (c People) IDs() []int {
	return c.project(func(v Person) int {
		return v.ID
	})
}

// Names returns the Name of every element, in order.
func (c People) Names() []string {
	return c.project(func(v Person) string {
		return v.Name
	})
}

// Ages returns the Age of every element, in order.
func (c People) Ages() []int {
	return c.project(func(v Person) int {
		return v.Age
	})
}

// Secrets returns the Secret of every element, in order.
func (c People) Secrets() []string {
	return c.project(func(v Person) string {
		return v.Secret
	})
}

// SortedByID returns the elements ordered by ID, leaving equal ones as they
// were.
func (c People) SortedByID() []Person {
	return c.ordered(func(v Person) int {
		return v.ID
	})
}

// Less reports whether the element at i sorts before the one at j, by ID. It is
// one of the three sort.Sort takes: the storage answers the length, and Swap
// below is the other. The order is ID's because it is the one sort key this
// declaration names — one naming several has several orders and no reason to
// prefer any of them, and gets its sorted views without these. Unlike
// SortedByID, sorting through this rearranges the collection rather than
// answering with a copy of it in order.
func (c People) Less(i, j int) bool {
	return c[i].ID < c[j].ID
}

// Swap exchanges the elements at i and j, which is the last of the three
// sort.Sort takes.
func (c People) Swap(i, j int) {
	c[i], c[j] = c[j], c[i]
}

// project collects one value from every element, in the order the elements come
// in.
//
// The result is grown rather than sized ahead, because what is walked is not
// always something that can be counted first — a walk is all this needs of the
// collection, and needing a length as well would be needing more.
func (c People) project[V any](of func(Person) V) []V {
	var out []V
	for v := range c.All() {
		out = append(out, of(v))
	}
	return out
}

// ordered returns the elements sorted by the key taken from each of them,
// leaving equal ones in the order they came in.
//
// A new slice rather than a sort in place: the collection is what it was, and a
// method that quietly reordered it would make asking a question change the
// answer to the next one.
func (c People) ordered[K cmp.Ordered](by func(Person) K) []Person {
	out := slices.Collect(c.All())
	slices.SortStableFunc(out, func(a, b Person) int { return cmp.Compare(by(a), by(b)) })

	return out
}

// People holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type People []Person

// NewPeople returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewPeople(elems ...Person) People { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s People) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s People) All() iter.Seq[Person] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s People) Backward() iter.Seq[Person] {
	return func(yield func(Person) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *People) AppendSeq(seq iter.Seq[Person]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *People) Reset() { *s = (*s)[:0] }

// AppendJSON appends the container to dst as a JSON array, and returns the
// extended buffer.
//
// One pass over the elements and straight into the buffer. No part of the
// document is assembled anywhere else first, so what it costs to write a
// container is what it costs to write its elements and nothing besides.
func (c People) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	open := len(dst)
	for v := range c.All() {
		dst = append(dst, ',')
		if dst, err = appendModelPersonJSON(dst, v); err != nil {
			return dst, err
		}
	}
	if len(dst) == open {
		return append(dst, '[', ']'), nil
	}
	dst[open] = '['
	return append(dst, ']'), nil
}

// MarshalJSON writes the container as a compact JSON array.
//
// The document is assembled in a borrowed buffer and copied out, so the
// cost over AppendJSON is one exactly-sized allocation — the slice being
// returned.
func (c People) MarshalJSON() ([]byte, error) {
	scratch := jsonTakeScratch()
	held, err := c.AppendJSON((*scratch)[:0])
	return jsonFinish(scratch, held, err)
}

// WriteTo writes the container to w as a JSON array, and reports how many bytes
// reached w.
//
// The document is assembled in a borrowed window and handed over a flush at
// a time, so a container of any size costs one window and no more. What is
// reported is what w accepted rather than what was composed, which is the
// count a caller copying from the container is entitled to. The document
// ends with a newline, which is what a writer of a stream of them leaves
// between two.
func (c People) WriteTo(w io.Writer) (int64, error) {
	scratch := jsonTakeScratch()
	dst := append((*scratch)[:0], '[')
	var (
		counted int64
		failed  error
	)
	first := true
	for v := range c.All() {
		if !first {
			dst = append(dst, ',')
		}
		first = false
		if dst, failed = appendModelPersonJSON(dst, v); failed != nil {
			break
		}
		if len(dst) < jsonFlushWindow {
			continue
		}
		n, err := w.Write(dst)
		counted += int64(n)
		if err != nil {
			failed = err
			break
		}
		dst = dst[:0]
	}
	if failed != nil {
		*scratch = dst
		jsonDropScratch(scratch)
		return counted, failed
	}
	dst = append(dst, ']', '\n')
	n, err := w.Write(dst)
	counted += int64(n)
	*scratch = dst
	jsonDropScratch(scratch)
	return counted, err
}

// peopleReadJSON reads a JSON array into the container, borrowing or copying as
// the flag says.
//
// What the container held is dropped first, so reading into one twice leaves
// the second document rather than both — which is what reading a document
// into a value means everywhere else. A JSON null empties it and reads
// nothing else: a container is empty or holds elements, so null and an empty
// array are read alike and both are written back as an empty array.
//
// The elements are handed over one at a time as they are read, so the
// document is never assembled anywhere beside the container being filled
// from it.
func peopleReadJSON(c *People, data []byte, borrow bool) error {
	i := jsonSkipSpace(data, 0)
	if next, ok := jsonScanNull(data, i); ok {
		if err := jsonAtEnd(data, next); err != nil {
			return err
		}
		c.Reset()
		return nil
	}
	if i >= len(data) || data[i] != '[' {
		return jsonCannotRead("People", data, i)
	}
	i++
	c.Reset()

	var failed error
	first := true
	ended := false
	c.AppendSeq(func(yield func(Person) bool) {
		for {
			next, done, err := jsonElementNext(data, i, first)
			if err != nil {
				failed = err
				return
			}
			if done {
				i, ended = next, true
				return
			}
			first = false
			i = next
			var v Person
			n, err := decodeModelPersonJSON(data, i, 1, &v, borrow)
			if err != nil {
				failed = err
				return
			}
			i = n
			if !yield(v) {
				return
			}
		}
	})

	if failed != nil {
		return failed
	}
	if !ended {
		next, done, err := jsonElementNext(data, i, first)
		if err != nil {
			return err
		}
		if !done {
			return errors.New("People stopped taking elements before the JSON array ended")
		}
		i = next
	}
	return jsonAtEnd(data, i)
}

// UnmarshalJSON reads one JSON array into the container. Everything read out
// of data is copied, so data is the caller's again the moment this returns.
func (c *People) UnmarshalJSON(data []byte) error {
	return peopleReadJSON(c, data, false)
}

// UnmarshalJSONBorrowed reads one JSON array into the container, with the elements'
// strings pointing into data rather than copied out of it. It is the
// quickest way in and the sharpest: data must outlive the container and
// must not be modified, or the elements change underneath it. Where that
// cannot be promised, UnmarshalJSON copies.
func (c *People) UnmarshalJSONBorrowed(data []byte) error {
	return peopleReadJSON(c, data, true)
}

// ReadFrom reads one JSON array from r into the container, and reports how many
// bytes that array took.
//
// One array rather than everything r holds, because a JSON document ends
// where it ends. The window is refilled in blocks, so bytes following the
// array may already have been taken out of r and are dropped with it: this
// reads a reader holding one document. What it holds at a time is bounded
// by the largest single element rather than by the document, which is what
// a streaming reader is for. A reader holding nothing reports io.EOF.
func (c *People) ReadFrom(r io.Reader) (int64, error) {
	feed := jsonNewFeed(r)
	defer feed.close()
	kind, err := feed.peek()
	if err != nil {
		return feed.offset(), err
	}
	if kind == 'n' {
		ok, err := feed.null()
		if err != nil {
			return feed.offset(), err
		}
		if ok {
			c.Reset()
			return feed.offset(), nil
		}
	}
	if kind != '[' {
		return feed.offset(), feed.cannotRead("People")
	}
	feed.take()
	c.Reset()

	var failed error
	first := true
	ended := false
	c.AppendSeq(func(yield func(Person) bool) {
		for {
			kind, err := feed.peek()
			if err != nil {
				failed = err
				return
			}
			switch {
			case kind == ']':
				feed.take()
				ended = true
				return
			case first:
			case kind != ',':
				failed = errJSONSyntax
				return
			default:
				feed.take()
			}
			first = false
			held, err2 := feed.element()
			if err2 != nil {
				failed = err2
				return
			}
			var v Person
			n, err3 := decodeModelPersonJSON(held, 0, 1, &v, false)
			if err3 != nil {
				failed = err3
				return
			}
			if err3 := jsonAtEnd(held, n); err3 != nil {
				failed = err3
				return
			}
			if !yield(v) {
				return
			}
		}
	})

	if failed != nil {
		return feed.offset(), failed
	}
	if !ended {
		kind, err := feed.peek()
		if err != nil {
			return feed.offset(), err
		}
		if kind != ']' {
			return feed.offset(), errors.New("People stopped taking elements before the JSON array ended")
		}
		feed.take()
	}
	return feed.offset(), nil
}

// People satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ io.WriterTo      = *new(People)
	_ io.ReaderFrom    = (*People)(nil)
	_ json.Marshaler   = *new(People)
	_ json.Unmarshaler = (*People)(nil)
	_ sort.Interface   = *new(People)
)

// And the walk's own signature, checked without calling it.
//
// A method expression is resolved when the package is built and costs nothing
// at run time, where an interface assertion would have to name a value and
// initialise it.
var _ func(*People) iter.Seq[Person] = (*People).All

// Codes holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type Codes []Code

// NewCodes returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewCodes(elems ...Code) Codes { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Codes) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Codes) All() iter.Seq[Code] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Codes) Backward() iter.Seq[Code] {
	return func(yield func(Code) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Codes) AppendSeq(seq iter.Seq[Code]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *Codes) Reset() { *s = (*s)[:0] }

// The walk's own signature, checked when the package is built.
//
// A method expression is resolved by the compiler and costs nothing at run
// time, where an interface assertion would have to name a value and initialise
// it. What it holds the walk to is the element type of the declaration, so a
// container that walks something else fails here rather than wherever somebody
// ranges over it.
var _ func(*Codes) iter.Seq[Code] = (*Codes).All

// Crowd holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type Crowd []Person

// NewCrowd returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewCrowd(elems ...Person) Crowd { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Crowd) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Crowd) All() iter.Seq[Person] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Crowd) Backward() iter.Seq[Person] {
	return func(yield func(Person) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Crowd) AppendSeq(seq iter.Seq[Person]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *Crowd) Reset() { *s = (*s)[:0] }

// The walk's own signature, checked when the package is built.
//
// A method expression is resolved by the compiler and costs nothing at run
// time, where an interface assertion would have to name a value and initialise
// it. What it holds the walk to is the element type of the declaration, so a
// container that walks something else fails here rather than wherever somebody
// ranges over it.
var _ func(*Crowd) iter.Seq[Person] = (*Crowd).All

// Locked is Person behind a read-write lock.
//
// Everything the stack below offers is on lockedHeld, which this holds
// and nothing else can reach. What reaches it is a scope: Do under the
// write lock, RDo under the read lock, each handed a LockedView for
// as long as the call lasts.
//
// The zero value is ready to use, because the zero value of what it holds
// is.
//
// The lock must not be copied once it has been used, which is why every
// method here is on the pointer.
type Locked struct {
	mu   sync.RWMutex
	held lockedHeld
}

// Do runs f with the write lock held.
//
// Everything beneath the lock is reachable through the view for as long as
// the call lasts, and no longer: a view kept past it reaches the same data
// with nothing held. The lock is not reentrant, so a call back into this
// value from inside f deadlocks — which the view cannot be used to write,
// and the value f closed over still can.
func (g *Locked) Do(f func(v LockedView)) {
	g.mu.Lock()
	defer g.mu.Unlock()

	f(LockedView{held: &g.held})
}

// RDo runs f with the read lock held.
//
// Several readers run at once and a writer waits for all of them, so a long
// read is a writer held up.
//
// What f is handed reaches the whole of what is below, including whatever
// changes it — the read lock is what this holds and not what the view
// enforces. Changing anything through it is a data race against the other
// readers this let in, and Do is what to use instead. Nothing here
// stops it: telling a method that reads from one that writes needs
// something the layers do not currently say about themselves.
//
// Nor is a read lock reentrant, which is the less obvious half: a second
// RLock taken while a writer is waiting blocks behind that writer, so
// Len, Snapshot and the codec called from inside f deadlock under
// contention and pass every test that runs without it. Do from inside f
// deadlocks outright, since it waits for the read lock f is holding.
// Read what you need through the view.
func (g *Locked) RDo(f func(v LockedView)) {
	g.mu.RLock()
	defer g.mu.RUnlock()

	f(LockedView{held: &g.held})
}

// Snapshot returns the elements, copied under the read lock.
//
// The slice is nobody else's, so it can be walked, sorted and held with
// nothing locked. It costs a copy of the elements, which is the price of
// walking something a writer may be changing — and the alternative is not
// a cheaper walk but a walk that races.
//
// The elements are copied the way Go copies anything, which is to say
// shallowly: a field that is a slice, a map or a pointer still refers to
// what the element in the container refers to. Writing through one of
// those from here is a write to memory another goroutine reads under the
// lock, which the lock cannot see and will not stop. Treat what comes
// back as readable rather than as yours.
//
// One allocation, because the container can say how much it holds before
// the walk starts. A copy that grew as it went would allocate once per
// doubling and copy what it had each time — which is what collecting a
// sequence of unknown length has to do, and is not what this is.
func (g *Locked) Snapshot() []Person {
	g.mu.RLock()
	defer g.mu.RUnlock()

	return slices.AppendSeq(
		make([]Person, 0, g.held.Len()),
		g.held.All())
}

// Len returns how many elements there are.
//
// Reached directly rather than through a scope, because it is one number
// read and handed back: there is nothing a caller can hold open, and asking
// them to write a closure for it would teach them that scopes are ceremony.
//
// It is a fact about the past by the time it is read, like every count of
// something another goroutine may be changing.
func (g *Locked) Len() int {
	g.mu.RLock()
	defer g.mu.RUnlock()

	return g.held.Len()
}

// Lock and Unlock take and release the write lock, making this a
// sync.Locker.
//
// Written because the declaration asked for them. They are what the rest of
// this type exists to make unnecessary: a caller holding the lock directly
// can reach nothing the lock guards — everything beneath it is behind a
// scope, and a scope takes the lock itself.
//
// Which is the same sentence read the other way round: every method that
// reaches the data takes the lock, so calling one while holding it
// deadlocks. What these are for is handing this value to something that
// asks for a sync.Locker and does not otherwise touch it — a sync.Cond is
// the case worth having them for — and not for reaching the data.
func (g *Locked) Lock() { g.mu.Lock() }

// Unlock releases the write lock.
func (g *Locked) Unlock() { g.mu.Unlock() }

// LockedView is what a scope over Locked hands the function it runs.
//
// No method on it names this type or the one it guards, so the call that
// deadlocks by accident — reaching for the value you were just handed and
// finding a way back in — cannot be written through this.
//
// Four things that leaves you, and every one of them is ordinary Go.
//
// The value the scope was opened on is still in scope inside the call, so
// calling a method on that deadlocks as it always would. Nothing here can
// hold a value inside the call it came from, so this kept past the call —
// or a sequence taken from it and walked afterwards — reaches the same data
// with nothing held. A way out spelled some other way, through an
// interface or an alias, is a name this cannot recognise. And this type
// is declared in your own package, so its field is reachable by hand and
// its zero value exists — neither of which any arrangement of methods can
// prevent.
type LockedView struct {
	held *lockedHeld
}

// Len how many elements the container holds
//
// It is the same method the stack below declares, reached through the view.
func (v LockedView) Len() int {
	return v.held.Len()
}

// All walks from the first element to the last
//
// It is the same method the stack below declares, reached through the view.
func (v LockedView) All() iter.Seq[Person] {
	return v.held.All()
}

// Backward walks from the last element to the first
//
// It is the same method the stack below declares, reached through the view.
func (v LockedView) Backward() iter.Seq[Person] {
	return v.held.Backward()
}

// AppendSeq adds every element a sequence yields
//
// It is the same method the stack below declares, reached through the view.
func (v LockedView) AppendSeq(a0 iter.Seq[Person]) {
	v.held.AppendSeq(a0)
}

// Reset empties the container, keeping the memory it has taken
//
// It is the same method the stack below declares, reached through the view.
func (v LockedView) Reset() {
	v.held.Reset()
}

// lockedHeld holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type lockedHeld []Person

// newLockedHeld returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func newLockedHeld(elems ...Person) lockedHeld { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s lockedHeld) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s lockedHeld) All() iter.Seq[Person] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s lockedHeld) Backward() iter.Seq[Person] {
	return func(yield func(Person) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *lockedHeld) AppendSeq(seq iter.Seq[Person]) { *s = slices.AppendSeq(*s, seq) }

// Reset empties the container, keeping the memory it has already taken.
//
// It is what makes a container fillable a second time without allocating a
// second time: reading a document into one that has been reset costs nothing
// the first read did not already pay for.
//
// The elements that were there stay in the memory behind the container until
// something is appended over them, so a container holding the last reference to
// something large holds it until then. That is the ordinary bargain of reusing
// a buffer, and a caller who would rather have the memory back can assign a new
// container instead.
func (s *lockedHeld) Reset() { *s = (*s)[:0] }

// Locked satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var _ sync.Locker = (*Locked)(nil)

// String returns the subject as the display tags on its fields ask for it.
//
// The fields in the order they were written, separated by a space, each
// labelled where its tag gave it a name. It is a rendering for a person to
// read rather than a format anything should parse: nothing here escapes a
// separator that turns up inside a value, because a reader can see what
// happened and a parser was never the point.
func (v Code) String() string {
	var b strings.Builder

	b.WriteString(v.Value)

	return b.String()
}

// String returns the subject as the display tags on its fields ask for it.
//
// The fields in the order they were written, separated by a space, each
// labelled where its tag gave it a name. It is a rendering for a person to
// read rather than a format anything should parse: nothing here escapes a
// separator that turns up inside a value, because a reader can see what
// happened and a parser was never the point.
func (v Person) String() string {
	var b strings.Builder

	b.WriteString(v.Name)

	b.WriteString(" ")
	b.WriteString("age=")
	b.WriteString(strconv.FormatInt(int64(v.Age), 10))

	return b.String()
}

// appendModelPersonJSON appends a Person as JSON.
//
// The value's own method holds the body; this is what generated code
// calls, so that a caller names one function whether or not the type
// is one a method could be declared on.
func appendModelPersonJSON(dst []byte, v Person) ([]byte, error) {
	return v.AppendJSON(dst)
}

// AppendJSON appends the Person to dst as a JSON object, and returns the
// extended buffer.
//
// Members are written in the order the fields are declared, an embedded
// struct's where the embedded field is. Nothing is allocated beyond the
// growth of dst, which is what makes this the implementation the other
// entry points reach.
func (v Person) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	dst = append(dst, `{"ID":`...)
	dst = strconv.AppendInt(dst, int64(v.ID), 10)
	dst = append(dst, `,"Name":`...)
	if dst, err = jsonAppendString(dst, string(v.Name)); err != nil {
		return dst, err
	}
	dst = append(dst, `,"Age":`...)
	dst = strconv.AppendInt(dst, int64(v.Age), 10)
	dst = append(dst, `,"Secret":`...)
	if dst, err = jsonAppendString(dst, string(v.Secret)); err != nil {
		return dst, err
	}
	return append(dst, '}'), nil
}

// MarshalJSON writes the Person as a compact JSON document.
//
// The document is assembled in a borrowed buffer and copied out, so the
// cost over [Person.AppendJSON] is one exactly-sized allocation — the
// slice being returned. It is also what makes the standard library
// dispatch to this codec wherever a Person appears.
func (v Person) MarshalJSON() ([]byte, error) {
	scratch := jsonTakeScratch()
	held, err := v.AppendJSON((*scratch)[:0])
	return jsonFinish(scratch, held, err)
}

// UnmarshalJSON reads one JSON value into the Person.
//
// A member the document does not mention keeps the value the destination
// held, and on any error the destination holds what it held before the
// call. Everything read out of data is copied, so data is the caller's
// again the moment this returns.
func (v *Person) UnmarshalJSON(data []byte) error {
	held := *v
	next, err := decodeModelPersonJSON(data, 0, 0, &held, false)
	if err != nil {
		return err
	}
	if err := jsonAtEnd(data, next); err != nil {
		return err
	}
	*v = held
	return nil
}

// UnmarshalJSONBorrowed fills v with strings that point into data rather than
// copies of it. It is the quickest way in and the sharpest: data must
// outlive v and must not be modified, or v changes underneath its
// holder. Where that cannot be promised, UnmarshalJSON copies.
func (v *Person) UnmarshalJSONBorrowed(data []byte) error {
	held := *v
	next, err := decodeModelPersonJSON(data, 0, 0, &held, true)
	if err != nil {
		return err
	}
	if err := jsonAtEnd(data, next); err != nil {
		return err
	}
	*v = held
	return nil
}

// decodeModelPersonJSON reads one Person from b at i, and returns where the next value
// begins.
//
// The scanning half of the codec, which the entry points wrap: it holds
// the document to the grammar the standard library holds it to — syntax,
// UTF-8, no duplicate member names — and stops at the first thing wrong
// with it. depth is how many values this one is already inside, and
// borrow decides whether strings point into b or copy out of it.
func decodeModelPersonJSON(b []byte, i, depth int, v *Person, borrow bool) (int, error) {
	i = jsonSkipSpace(b, i)
	if next, ok := jsonScanNull(b, i); ok {
		*v = Person{}
		return next, nil
	}
	if i >= len(b) || b[i] != '{' {
		return 0, jsonCannotRead("Person", b, i)
	}
	depth++
	if depth > jsonMaxDepth {
		return 0, errJSONDeep
	}
	i++
	var names jsonNames
	var scratch []byte
	for first := true; ; first = false {
		next, done, err := jsonMemberNext(b, i, first)
		if err != nil {
			return 0, err
		}
		if done {
			return next, nil
		}
		lo, hi, at, esc, err := jsonMemberName(b, next)
		if err != nil {
			return 0, err
		}
		i = at
		switch string(jsonName(b, lo, hi, esc, &scratch)) {
		case "ID":
			if names.declare(0) {
				return 0, errJSONDuplicate
			}
			if next1, ok := jsonScanNull(b, i); ok {
				v.ID = 0
				i = next1
			} else if i >= len(b) || (b[i] < '0' || b[i] > '9') && b[i] != '-' {
				return 0, jsonCannotRead("int", b, i)
			} else {
				held, next1, err := jsonScanInt(b, i, strconv.IntSize)
				if err != nil {
					return 0, err
				}
				v.ID = int(held)
				i = next1
			}
		case "Name":
			if names.declare(1) {
				return 0, errJSONDuplicate
			}
			if next1, ok := jsonScanNull(b, i); ok {
				v.Name = ""
				i = next1
			} else if i >= len(b) || b[i] != '"' {
				return 0, jsonCannotRead("string", b, i)
			} else {
				lo, hi, next1, esc, err := jsonScanString(b, i)
				if err != nil {
					return 0, err
				}
				v.Name = string(jsonString(b, lo, hi, esc, borrow))
				i = next1
			}
		case "Age":
			if names.declare(2) {
				return 0, errJSONDuplicate
			}
			if next1, ok := jsonScanNull(b, i); ok {
				v.Age = 0
				i = next1
			} else if i >= len(b) || (b[i] < '0' || b[i] > '9') && b[i] != '-' {
				return 0, jsonCannotRead("int", b, i)
			} else {
				held, next1, err := jsonScanInt(b, i, strconv.IntSize)
				if err != nil {
					return 0, err
				}
				v.Age = int(held)
				i = next1
			}
		case "Secret":
			if names.declare(3) {
				return 0, errJSONDuplicate
			}
			if next1, ok := jsonScanNull(b, i); ok {
				v.Secret = ""
				i = next1
			} else if i >= len(b) || b[i] != '"' {
				return 0, jsonCannotRead("string", b, i)
			} else {
				lo, hi, next1, esc, err := jsonScanString(b, i)
				if err != nil {
					return 0, err
				}
				v.Secret = string(jsonString(b, lo, hi, esc, borrow))
				i = next1
			}
		default:
			if names.unknown(b, lo, hi, esc) {
				return 0, errJSONDuplicate
			}
			if i, err = jsonSkipValue(b, i, depth); err != nil {
				return 0, err
			}
		}
	}
}

// LogValue returns the subject as it may be logged.
//
// Every exported field, with the ones tagged redact replaced by a fixed
// string. Fixed rather than shortened or starred: a length is something,
// a prefix is more, and a field marked as not for logs was marked by
// somebody who did not want to work out which of those is safe.
//
// Implementing this is what takes the field out of a log. slog reaches for
// a value's fields when the value does not say otherwise, so a type with a
// secret in it and no LogValue prints the secret.
func (v Person) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Int64("ID", int64(v.ID)),
		slog.String("Name", v.Name),
		slog.Int64("Age", int64(v.Age)),
		slog.String("Secret", "[redacted]"),
	)
}

// AppendText appends the wrapped value's text form to b.
//
// The type wraps one scalar, so its text is that scalar's and nothing is
// decided here. Appending rather than returning is what lets a caller who
// has a buffer keep it: encoding.TextAppender exists for exactly that, and
// MarshalText below is written in terms of this rather than beside it.
func (v Code) AppendText(b []byte) ([]byte, error) {
	return append(b, v.Value...), nil
}

// MarshalText returns the wrapped value's text form.
//
// It allocates, because its signature says it hands back a slice the caller
// owns. A caller who would rather not can call AppendText with a buffer of
// their own, which is the same work without the allocation.
func (v Code) MarshalText() ([]byte, error) {
	return v.AppendText(nil)
}

// UnmarshalText reads the wrapped value back out of its text form.
//
// The receiver is a pointer because this assigns to the value, which is the
// one method here that does. Text that does not parse leaves the value
// untouched rather than half written: a caller who ignores the error and
// carries on gets what they had, not a field from one input beside a field
// from another.
func (v *Code) UnmarshalText(b []byte) error {
	v.Value = string(b)
	return nil
}

// Seq is a lazy view over a sequence of elements.
//
// Every operation on it is lazy: it returns another view and walks nothing. The
// walk happens once, when a terminal asks for it, and each element passes
// through the whole chain before the next one is read — so a chain over a
// million elements holds one of them at a time and allocates nothing per
// element. A chain costs a few allocations per link to build and to start, and
// that is the whole of what it costs: the same over a million elements as over
// ten.
//
// The zero view yields nothing through every method here, so one that was never
// given a sequence behaves like an empty one. Ranging over it directly is
// ranging over a function that is not there, which panics like any other nil
// call — All is what guards that, and is what to range over.
type Seq[U any] iter.Seq[U]

// All returns the view as an ordinary sequence, which is what everything taking
// an iter.Seq wants and what a range loop should read.
//
// It is also where the zero view is made safe. A view is a function underneath,
// so one that was never given a sequence is a nil function and ranging over it
// panics; this hands back an empty sequence instead, and every method below
// walks through here rather than over the view directly.
func (s Seq[U]) All() iter.Seq[U] {
	if s == nil {
		return func(func(U) bool) {}
	}
	return iter.Seq[U](s)
}

// Filter returns a view of the elements the predicate keeps.
func (s Seq[U]) Filter(keep func(U) bool) Seq[U] {
	return func(yield func(U) bool) {
		for v := range s.All() {
			if keep(v) && !yield(v) {
				return
			}
		}
	}
}

// Map returns a view of what the function makes of each element.
//
// Genuinely generic in its result, so a chain that changes type keeps chaining:
// the view a projection returns is a view like any other, and the combinators
// on it are these same ones rather than a second set written for the new type.
func (s Seq[U]) Map[V any](to func(U) V) Seq[V] {
	return func(yield func(V) bool) {
		for v := range s.All() {
			if !yield(to(v)) {
				return
			}
		}
	}
}

// Take returns a view of at most the first n elements, and of none for an n
// that is not positive.
//
// It stops the walk beneath it rather than reading on and discarding, which is
// what makes taking ten from a very long sequence cost ten.
func (s Seq[U]) Take(n int) Seq[U] {
	return func(yield func(U) bool) {
		if n <= 0 {
			return
		}

		left := n
		for v := range s.All() {
			if !yield(v) {
				return
			}

			left--
			if left == 0 {
				return
			}
		}
	}
}

// Skip returns a view of everything after the first n elements, and of
// everything for an n that is not positive.
func (s Seq[U]) Skip(n int) Seq[U] {
	return func(yield func(U) bool) {
		left := n
		for v := range s.All() {
			if left > 0 {
				left--
				continue
			}
			if !yield(v) {
				return
			}
		}
	}
}

// Dedup returns a view with runs of equal elements collapsed to their first.
//
// Adjacent elements only, which is the whole of what a lazy operation can do:
// dropping every repeat wherever it appears means remembering everything seen
// so far, and a view that grew a set as it walked would not be a view any more.
// Sort or group first if that is what is wanted.
//
// Each element is compared against the last one that was *yielded* rather than
// against the one immediately before it, so a run collapses to its first
// element however long it is. The two are the same thing for an equality, and
// differ for a comparison that is not one — a nearness test over 1, 2, 3 keeps
// 1 and 3 here, where comparing neighbours would keep only 1. The first
// argument is the element that was kept and the second the one being offered.
func (s Seq[U]) Dedup(same func(a, b U) bool) Seq[U] {
	return func(yield func(U) bool) {
		var last U
		seen := false

		for v := range s.All() {
			if seen && same(last, v) {
				continue
			}

			last, seen = v, true
			if !yield(v) {
				return
			}
		}
	}
}

// Chunk yields slices of n elements, the last of them shorter if the sequence
// does not divide evenly. It panics for an n below one, which asks for
// something there is no answer to.
//
// Each chunk is a slice of its own rather than one buffer handed out again and
// again. Reusing it would allocate less and would make a chunk kept past the
// next one silently become that one — a bug that shows up as data from the
// wrong batch, far from here. The cost is one allocation per chunk, which is
// still none per element.
//
// A plain sequence rather than another view, and that one is the language's.
// A method of this type returning a view of slices means the type mentioning
// itself over a bigger type than it was given, and the method set of that one
// mentioning a bigger one again, without end; the compiler calls it an
// instantiation cycle and refuses the file. A function beside the type could
// return one — the cycle is a property of method sets — at the price of a name
// in this package that everything else here keeps inside the view. Chunks are
// usually ranged over, which this is, and converting what it yields to a view
// of slices is the whole of the difference when they are not.
func (s Seq[U]) Chunk(n int) iter.Seq[[]U] {
	if n < 1 {
		panic("forge: Chunk of fewer than one element")
	}

	return func(yield func([]U) bool) {
		// Built on the first element that goes into it rather than ahead of
		// one, so a sequence that ends on a boundary does not pay for a batch
		// nothing is put in.
		var batch []U

		for v := range s.All() {
			if batch == nil {
				batch = make([]U, 0, n)
			}
			if batch = append(batch, v); len(batch) < n {
				continue
			}
			if !yield(batch) {
				return
			}
			batch = nil
		}

		if len(batch) > 0 {
			yield(batch)
		}
	}
}

// Collect walks the view and returns everything it yields.
func (s Seq[U]) Collect() []U { return slices.Collect(s.All()) }

// Into appends everything the view yields to a slice and returns it.
//
// It is Collect for a caller who owns the memory: passing a slice kept between
// calls turns the one allocation Collect makes into none.
func (s Seq[U]) Into(dst []U) []U { return slices.AppendSeq(dst, s.All()) }

// First returns the first element the view yields, and whether it yielded one.
// The walk stops there, so first-of-a-filter over a long sequence costs the
// elements up to the match and no more.
func (s Seq[U]) First() (U, bool) {
	for v := range s.All() {
		return v, true
	}

	var none U
	return none, false
}

// Reduce combines the elements into a single value, left to right.
//
// Generic in what it builds rather than in the element alone, so a sequence of
// values reduces to a count, a total or a map without being projected first.
func (s Seq[U]) Reduce[A any](initial A, combine func(A, U) A) A {
	out := initial
	for v := range s.All() {
		out = combine(out, v)
	}
	return out
}

// What a document can be wrong about.
//
// One sentence each and no position, because the position is the caller's: a
// generated codec knows which member it was reading and adds that, and a
// sentence naming the byte would be a sentence this file cannot write.
var (
	errJSONSyntax    = errors.New("json: invalid syntax")
	errJSONUTF8      = errors.New("json: invalid UTF-8")
	errJSONEscape    = errors.New("json: invalid escape")
	errJSONTruncated = errors.New("json: unexpected end of input")
	errJSONDuplicate = errors.New("json: duplicate object member name")
	errJSONSurrogate = errors.New("json: invalid surrogate pair")
	errJSONRange     = errors.New("json: number out of range for its Go type")
	errJSONDeep      = errors.New("json: value nested deeper than a reader reads")
	errJSONNonfinite = errors.New("json: a non-finite number has no JSON form")
)

// jsonMaxDepth is how deep a document may nest before it is refused.
//
// The bound the standard library holds a document to, and it is held here for
// the same reason: nesting is the one thing a document decides that costs the
// reader stack, and a reader whose stack a document decides is a reader the
// document can stop.
const jsonMaxDepth = 10000

// jsonScratchCap is the size a pooled buffer stops being worth keeping at.
//
// A document that arrived once and was enormous would otherwise park its
// buffer for the life of the process, which is the way a pool turns into a
// leak: the pool holds what the largest caller ever needed rather than what
// the ordinary one needs.
const jsonScratchCap = 1 << 16

// jsonScratch lends the buffers a codec assembles into and unescapes through.
//
// Nothing taken from it escapes the call that took it. A value built in one of
// these and handed back to a caller is copied on the way out, because handing
// back the buffer itself would let the next caller to take it write into bytes
// the first is still reading — which the race detector finds and nothing else
// does.
var jsonScratch = sync.Pool{New: func() any { b := make([]byte, 0, 256); return &b }}

// jsonTakeScratch borrows a buffer.
//
// The assertion is checked rather than assumed, because the pool holds what it
// is given and a panic inside a codec would be reported against the document
// rather than against whoever put the wrong thing in.
func jsonTakeScratch() *[]byte {
	if held, ok := jsonScratch.Get().(*[]byte); ok {
		return held
	}
	fresh := make([]byte, 0, 256)
	return &fresh
}

// jsonDropScratch returns a buffer, unless it has grown past what is worth
// keeping.
func jsonDropScratch(b *[]byte) {
	if cap(*b) <= jsonScratchCap {
		jsonScratch.Put(b)
	}
}

// jsonAppendString appends s as a JSON string.
//
// What is escaped is what encoding/json/v2 escapes when nobody has asked for
// anything else: the quote, the backslash, and the C0 controls — five of those
// by their short forms and the rest as \u00XX. Not the three characters HTML
// would want escaped, not U+007F, and not the two line separators JavaScript
// would want: those are things a caller asks an encoder for, and generated
// code has no encoder to be asked. A caller who needs them applies them to the
// bytes that come back.
//
// Invalid UTF-8 is an error rather than a replacement, which is also what the
// standard library does by default. The alternative writes a document that
// says something different from the value it came from, and says it silently.
func jsonAppendString(dst []byte, s string) ([]byte, error) {
	dst = append(dst, '"')

	// last is where the run of bytes that need nothing done to them began, and
	// wordly is where it is worth asking about eight at a time again.
	//
	// Copying a run at a time rather than a byte at a time is the whole of why
	// this is faster than asking about each one: an ordinary string is one run.
	//
	// The second of those is what keeps the word scan from costing more than
	// it saves. A string of ordinary text is one long run and the scan skips
	// it eight bytes at a time; a string that escapes something every second
	// byte has no run to skip, and asking about a word before each escape is
	// setup paid for nothing. So a failed ask moves the next one eight bytes
	// along: dense escaping falls back to a byte at a time, and text that
	// settles down is picked up again.
	last, wordly := 0, 0
	for i := 0; i < len(s); {
		c := s[i]
		switch {
		case c >= utf8.RuneSelf:
			// Multi-byte, and so nothing to escape — but it does have to be a
			// rune. DecodeRuneInString reports a byte that is not the start of
			// one as U+FFFD of width one, which is the only way it reports it.
			_, size := utf8.DecodeRuneInString(s[i:])
			if size == 1 {
				return dst, errJSONUTF8
			}
			i += size

		case c < ' ' || c == '"' || c == '\\':
			dst = append(dst, s[last:i]...)
			dst = jsonAppendEscape(dst, c)
			i++
			last = i

		case i >= wordly:
			// Worth asking about eight at once. A word that is all ordinary
			// bytes skips them; one that is not moves the next ask eight bytes
			// along, so that a string escaping something every second byte
			// stops paying for the ask.
			if next := jsonPlainWords(s, i); next > i {
				i = next
				continue
			}
			wordly, i = i+8, i+1

		default:
			i++
		}
	}

	dst = append(dst, s[last:]...)
	return append(dst, '"'), nil
}

// The bytes of a word, for asking about eight at once.
const (
	jsonOnes    = 0x0101010101010101
	jsonHighs   = 0x8080808080808080
	jsonQuotes  = 0x2222222222222222 // '"' in every byte
	jsonSlashes = 0x5c5c5c5c5c5c5c5c // '\\' in every byte
)

// jsonPlainWords advances past whole words of bytes a string carries as they
// are written, and returns where it stopped.
//
// It returns i unchanged when the next eight bytes are not all like that,
// which is how the caller learns to go a byte at a time instead — the whole
// point being that a word is asked about once and either skips eight bytes or
// costs nothing more than the ask.
//
// Eight at a time because the ordinary string is one long run of bytes that
// need nothing done to them, and asking about each one separately is what
// makes an escaper slower than the one it replaces. The word is assembled from
// eight indexed reads off a slice whose bounds were checked once, which the
// compiler turns into a single load — so this needs no unsafe and no
// dependency on the machine's byte order.
//
// A byte needs attention when it is a control byte, a quote, a backslash, or
// the start of something multi-byte. The tests below find each of those across
// a whole word: subtracting from every byte and looking at the borrow finds a
// byte below a bound, and exclusive-or against a repeated byte turns a match
// into a zero, which the same trick then finds.
func jsonPlainWords(s string, i int) int {
	for i+8 <= len(s) {
		chunk := s[i : i+8]
		w := uint64(chunk[0]) | uint64(chunk[1])<<8 | uint64(chunk[2])<<16 |
			uint64(chunk[3])<<24 | uint64(chunk[4])<<32 | uint64(chunk[5])<<40 |
			uint64(chunk[6])<<48 | uint64(chunk[7])<<56

		if jsonBelow(w, ' ')|w&jsonHighs|jsonAnyZero(w^jsonQuotes)|jsonAnyZero(w^jsonSlashes) != 0 {
			return i
		}
		i += 8
	}

	return i
}

// jsonAnyZero reports, in the high bit of each byte, which bytes of w are
// zero.
func jsonAnyZero(w uint64) uint64 { return (w - jsonOnes) & ^w & jsonHighs }

// jsonBelow reports, in the high bit of each byte, which bytes of w are less
// than n. Only valid for n below 0x80, which is every bound this file asks
// about.
func jsonBelow(w uint64, n byte) uint64 {
	return (w - jsonOnes*uint64(n)) & ^w & jsonHighs
}

// jsonAppendEscape appends the escape for one byte that needs one.
func jsonAppendEscape(dst []byte, c byte) []byte {
	switch c {
	case '"', '\\':
		return append(dst, '\\', c)
	case '\b':
		return append(dst, `\b`...)
	case '\f':
		return append(dst, `\f`...)
	case '\n':
		return append(dst, `\n`...)
	case '\r':
		return append(dst, `\r`...)
	case '\t':
		return append(dst, `\t`...)
	default:
		const hex = "0123456789abcdef"
		return append(dst, '\\', 'u', '0', '0', hex[c>>4], hex[c&0xf])
	}
}

// jsonAppendFloat appends a float as JSON writes one.
//
// Not what strconv writes with any single verb. JSON has no notion of a
// non-finite number and no preferred exponent form, so the standard library
// picks the verb from the magnitude: fixed notation inside the range where it
// is shorter, exponent notation outside it, and the shortest representation
// that reads back as the same value either way. The one adjustment after that
// is dropping the zero out of a two-digit negative exponent, so that 1e-9
// comes out as it is written here rather than as 1e-09.
//
// bits is 32 for a float32 widened to be passed, and 64 for a float64. It
// decides which value the shortest representation has to read back as.
func jsonAppendFloat(dst []byte, f float64, bits int) []byte {
	if bits == 32 {
		f = float64(float32(f))
	}

	// The comparison is made at the width being written, not at the widest
	// one. A float32 that is the nearest thing to 1e-6 is not less than 1e-6
	// when both are narrowed, and is less than it when both are widened — so
	// asking in float64 about a 32-bit value picks the exponent form for a
	// value the standard library writes in fixed notation.
	abs := math.Abs(f)
	verb := byte('f')
	if abs != 0 {
		if bits == 32 && (float32(abs) < 1e-6 || float32(abs) >= 1e21) ||
			bits == 64 && (abs < 1e-6 || abs >= 1e21) {
			verb = 'e'
		}
	}

	dst = strconv.AppendFloat(dst, f, verb, -1, bits)
	if verb != 'e' {
		return dst
	}

	// e-09 to e-9, and e+09 to e+9 is not a case: strconv writes a positive
	// exponent without the sign and without the padding.
	if n := len(dst); n >= 4 && dst[n-4] == 'e' && dst[n-3] == '-' && dst[n-2] == '0' {
		dst[n-2] = dst[n-1]
		dst = dst[:n-1]
	}

	return dst
}

// jsonAppendFinite appends a float that has a JSON form, and refuses the three
// that do not.
//
// JSON has no NaN and no infinities, and the standard library errors on all
// three unless a caller asks for something else — which generated code has no
// caller to be asked by.
func jsonAppendFinite(dst []byte, f float64, bits int) ([]byte, error) {
	if math.IsNaN(f) || math.IsInf(f, 0) {
		return dst, errJSONNonfinite
	}
	return jsonAppendFloat(dst, f, bits), nil
}

// jsonSkipSpace steps over the whitespace JSON allows between values.
func jsonSkipSpace(b []byte, i int) int {
	for i < len(b) {
		switch b[i] {
		case ' ', '\t', '\n', '\r':
			i++
		default:
			return i
		}
	}
	return i
}

// jsonAtEnd holds a whole document to being one value with nothing after it.
//
// Only a document asks. A value nested inside another is followed by the rest
// of its parent, so a reader that asked this question everywhere would refuse
// every object with two members in it.
func jsonAtEnd(b []byte, i int) error {
	if jsonSkipSpace(b, i) != len(b) {
		return errJSONSyntax
	}
	return nil
}

// jsonScanString finds the bounds of the string beginning at b[i].
//
// It returns where the contents begin and end, where the value after the
// string begins, and whether the contents carry an escape. The last of those
// is what lets the common case cost nothing: a string with no escape in it is
// already the bytes it means, so it can be taken whole rather than rebuilt.
//
// Everything JSON refuses in a string is refused here: a raw control byte, an
// escape that is not one of the eight, a \u that runs off the end, and a byte
// sequence that is not UTF-8. That is the same set encoding/json/jsontext
// refuses, and the tests beside this file are what keep it the same set.
func jsonScanString(b []byte, i int) (lo, hi, next int, esc bool, err error) {
	if i >= len(b) || b[i] != '"' {
		return 0, 0, 0, false, errJSONSyntax
	}
	i++
	lo = i

	// wordly is where it is worth asking about eight bytes at a time again,
	// under the same bargain the escaper strikes: a word of ordinary bytes
	// skips eight, and a word that is not moves the next ask eight along, so
	// escape-dense content stops paying for the ask.
	wordly := 0
	for i < len(b) {
		c := b[i]
		switch {
		case c == '"':
			return lo, i, i + 1, esc, nil

		case c == '\\':
			next, err := jsonScanEscape(b, i)
			if err != nil {
				return 0, 0, 0, false, err
			}
			esc, i = true, next

		case c < ' ':
			// A control byte written into a string rather than escaped. JSON
			// refuses it, and accepting it would let a document carry a byte
			// no document that came from an encoder could carry.
			return 0, 0, 0, false, errJSONSyntax

		case c < utf8.RuneSelf:
			if i >= wordly {
				if next := jsonPlainBytes(b, i); next > i {
					i = next
					continue
				}
				wordly = i + 8
			}
			i++

		default:
			_, size := utf8.DecodeRune(b[i:])
			if size == 1 {
				return 0, 0, 0, false, errJSONUTF8
			}
			i += size
		}
	}

	return 0, 0, 0, false, errJSONTruncated
}

// jsonPlainBytes advances past whole words of bytes a string carries as they
// are written, and returns where it stopped. The byte-slice twin of
// [jsonPlainWords], for the reading side.
func jsonPlainBytes(b []byte, i int) int {
	for i+8 <= len(b) {
		chunk := b[i : i+8]
		w := uint64(chunk[0]) | uint64(chunk[1])<<8 | uint64(chunk[2])<<16 |
			uint64(chunk[3])<<24 | uint64(chunk[4])<<32 | uint64(chunk[5])<<40 |
			uint64(chunk[6])<<48 | uint64(chunk[7])<<56

		if jsonBelow(w, ' ')|w&jsonHighs|jsonAnyZero(w^jsonQuotes)|jsonAnyZero(w^jsonSlashes) != 0 {
			return i
		}
		i += 8
	}

	return i
}

// jsonScanEscape steps over the escape beginning at b[i], which must be the
// backslash, and returns where the byte after it is.
//
// A \u escape is decoded rather than merely shaped, because half of what can
// be wrong with one is in its value: a surrogate half is four perfectly good
// hexadecimal digits naming something that is not a code point, and it is
// legal only as the first of a pair. The standard library refuses a lone half
// even in a value nothing reads, so a scan that waved it through would accept
// documents everything else refuses.
func jsonScanEscape(b []byte, i int) (int, error) {
	if i+1 >= len(b) {
		return 0, errJSONTruncated
	}

	switch b[i+1] {
	case '"', '\\', '/', 'b', 'f', 'n', 'r', 't':
		return i + 2, nil

	case 'u':
		return jsonScanUnicode(b, i)

	default:
		return 0, errJSONEscape
	}
}

// jsonScanUnicode steps over a \u escape and the pair it may be half of. i is
// the backslash.
func jsonScanUnicode(b []byte, i int) (int, error) {
	if i+6 > len(b) {
		return 0, errJSONTruncated
	}

	r, err := jsonHex4(b[i+2 : i+6])
	if err != nil {
		return 0, err
	}
	switch {
	case r < 0xd800 || r > 0xdfff:
		return i + 6, nil
	case r > 0xdbff:
		// A trailing surrogate with no leading one before it.
		return 0, errJSONSurrogate
	case i+12 > len(b):
		return 0, errJSONTruncated
	case b[i+6] != '\\' || b[i+7] != 'u':
		// A leading surrogate with nothing after it to pair with.
		return 0, errJSONSurrogate
	}

	low, err := jsonHex4(b[i+8 : i+12])
	if err != nil {
		return 0, err
	}
	if low < 0xdc00 || low > 0xdfff {
		return 0, errJSONSurrogate
	}
	return i + 12, nil
}

// jsonUnescape appends the contents of a JSON string with its escapes decoded.
//
// Only called for a string jsonScanString said carried one, so the ordinary
// string never reaches it. A lone surrogate is refused rather than replaced,
// which is what the standard library does when nobody has asked it to allow
// invalid UTF-8: a surrogate half is a well-formed escape naming something
// that is not a code point, and writing the replacement rune instead would
// hand back a string the document does not contain.
func jsonUnescape(dst, b []byte) ([]byte, error) {
	for i := 0; i < len(b); {
		c := b[i]
		if c != '\\' {
			dst = append(dst, c)
			i++
			continue
		}

		i++
		if i >= len(b) {
			return dst, errJSONTruncated
		}
		switch b[i] {
		case '"', '\\', '/':
			dst = append(dst, b[i])
			i++
		case 'b':
			dst = append(dst, '\b')
			i++
		case 'f':
			dst = append(dst, '\f')
			i++
		case 'n':
			dst = append(dst, '\n')
			i++
		case 'r':
			dst = append(dst, '\r')
			i++
		case 't':
			dst = append(dst, '\t')
			i++
		case 'u':
			r, size, err := jsonScanEscapedRune(b[i-1:])
			if err != nil {
				return dst, err
			}
			dst = utf8.AppendRune(dst, r)
			i += size - 1
		default:
			return dst, errJSONEscape
		}
	}

	return dst, nil
}

// jsonScanEscapedRune decodes one \u escape and the pair it may be half of.
//
// It returns the rune and how many bytes of b it read, counting the backslash.
func jsonScanEscapedRune(b []byte) (rune, int, error) {
	if len(b) < 6 {
		return 0, 0, errJSONTruncated
	}

	r, err := jsonHex4(b[2:6])
	if err != nil {
		return 0, 0, err
	}

	switch {
	case r < 0xd800 || r > 0xdfff:
		return r, 6, nil
	case r > 0xdbff:
		// A trailing surrogate with no leading one before it.
		return 0, 0, errJSONSurrogate
	case len(b) < 12 || b[6] != '\\' || b[7] != 'u':
		// A leading surrogate with nothing after it to pair with.
		return 0, 0, errJSONSurrogate
	}

	low, err := jsonHex4(b[8:12])
	if err != nil {
		return 0, 0, err
	}
	if low < 0xdc00 || low > 0xdfff {
		return 0, 0, errJSONSurrogate
	}

	return 0x10000 + (r-0xd800)<<10 + (low - 0xdc00), 12, nil
}

// jsonHex4 reads four hexadecimal digits.
func jsonHex4(b []byte) (rune, error) {
	var r rune
	for _, c := range b {
		r <<= 4
		switch {
		case c >= '0' && c <= '9':
			r |= rune(c - '0')
		case c >= 'a' && c <= 'f':
			r |= rune(c-'a') + 10
		case c >= 'A' && c <= 'F':
			r |= rune(c-'A') + 10
		default:
			return 0, errJSONEscape
		}
	}
	return r, nil
}

// jsonScanNumber finds the bounds of the number beginning at b[i].
//
// The grammar is JSON's and not Go's, which is stricter in three places that
// matter: no leading plus, no leading zero on a number with more digits after
// it, and a decimal point or an exponent that has to be followed by a digit.
// A reader that took Go's grammar would accept documents no encoder writes and
// no other reader reads.
func jsonScanNumber(b []byte, i int) (lo, hi int, err error) {
	lo = i

	if i < len(b) && b[i] == '-' {
		i++
	}

	i, err = jsonScanWhole(b, i)
	if err != nil {
		return 0, 0, err
	}
	if i, err = jsonScanFraction(b, i); err != nil {
		return 0, 0, err
	}
	if i, err = jsonScanExponent(b, i); err != nil {
		return 0, 0, err
	}

	return lo, i, nil
}

// jsonScanWhole steps over the digits before the point.
//
// One zero, or a digit that is not zero followed by as many as there are. That
// is where JSON differs from Go and from every language whose literals allow a
// leading zero: 007 is three characters JSON has no number for.
func jsonScanWhole(b []byte, i int) (int, error) {
	switch {
	case i >= len(b):
		return 0, errJSONTruncated
	case b[i] == '0':
		return i + 1, nil
	case b[i] >= '1' && b[i] <= '9':
		for i < len(b) && jsonIsDigit(b[i]) {
			i++
		}
		return i, nil
	default:
		return 0, errJSONSyntax
	}
}

// jsonScanFraction steps over a decimal point and the digits after it, if
// there is one. A point with no digit after it is not a number.
func jsonScanFraction(b []byte, i int) (int, error) {
	if i >= len(b) || b[i] != '.' {
		return i, nil
	}

	i++
	if i >= len(b) || !jsonIsDigit(b[i]) {
		return 0, errJSONSyntax
	}
	for i < len(b) && jsonIsDigit(b[i]) {
		i++
	}
	return i, nil
}

// jsonScanExponent steps over an exponent, if there is one. A sign is allowed
// there and nowhere else in a JSON number, and the digits are not optional.
func jsonScanExponent(b []byte, i int) (int, error) {
	if i >= len(b) || (b[i] != 'e' && b[i] != 'E') {
		return i, nil
	}

	i++
	if i < len(b) && (b[i] == '+' || b[i] == '-') {
		i++
	}
	if i >= len(b) || !jsonIsDigit(b[i]) {
		return 0, errJSONSyntax
	}
	for i < len(b) && jsonIsDigit(b[i]) {
		i++
	}
	return i, nil
}

// jsonIsDigit reports whether a byte is a decimal digit.
func jsonIsDigit(c byte) bool { return c >= '0' && c <= '9' }

// jsonScanInt reads a JSON number into a signed integer of the given width.
//
// A number with a fraction or an exponent is refused rather than truncated,
// which is what the standard library does with one: 1.0 into an int is a
// document describing a value the field cannot hold, and rounding it would be
// this codec deciding what the document meant.
//
// The digits are accumulated here rather than handed to strconv, because this
// is the hottest scan a numeric document has and the grammar was already being
// walked to find where the number ends — parsing it again would read every
// digit twice.
func jsonScanInt(b []byte, i, bits int) (int64, int, error) {
	neg := i < len(b) && b[i] == '-'
	if neg {
		i++
	}

	held, next, err := jsonDigits(b, i)
	if err != nil {
		return 0, 0, err
	}

	limit := uint64(1) << (bits - 1)
	if !neg {
		limit--
	}
	if held > limit {
		return 0, 0, errJSONRange
	}
	if neg {
		return -int64(held), next, nil //nolint:gosec // held is at most 1<<(bits-1), checked above, and negating carries the last unit.
	}
	return int64(held), next, nil //nolint:gosec // held is at most 1<<(bits-1)-1, checked above.
}

// jsonScanUint reads a JSON number into an unsigned integer of the given
// width.
func jsonScanUint(b []byte, i, bits int) (uint64, int, error) {
	if i < len(b) && b[i] == '-' {
		return 0, 0, errJSONRange
	}

	held, next, err := jsonDigits(b, i)
	if err != nil {
		return 0, 0, err
	}
	if bits < 64 && held >= uint64(1)<<bits {
		return 0, 0, errJSONRange
	}
	return held, next, nil
}

// jsonDigits accumulates the digits of an integer, holding them to JSON's
// grammar: one zero or a run that does not start with one, and no point or
// exponent after it, since an integer is what is being read.
func jsonDigits(b []byte, i int) (uint64, int, error) {
	if i >= len(b) {
		return 0, 0, errJSONTruncated
	}

	var held uint64
	switch {
	case b[i] == '0':
		i++
	case b[i] >= '1' && b[i] <= '9':
		for i < len(b) && jsonIsDigit(b[i]) {
			digit := uint64(b[i] - '0')
			if held > (math.MaxUint64-digit)/10 {
				return 0, 0, errJSONRange
			}
			held = held*10 + digit
			i++
		}
	default:
		return 0, 0, errJSONSyntax
	}

	if i < len(b) {
		switch b[i] {
		case '.', 'e', 'E', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			// A fraction or an exponent is a number the integer cannot hold,
			// and a digit here is only reachable after a leading zero, which
			// JSON gives no second digit.
			return 0, 0, errJSONSyntax
		}
	}
	return held, i, nil
}

// jsonScanFloat reads a JSON number into a float of the given width.
func jsonScanFloat(b []byte, i, bits int) (float64, int, error) {
	lo, hi, err := jsonScanNumber(b, i)
	if err != nil {
		return 0, 0, err
	}

	held, err := strconv.ParseFloat(string(b[lo:hi]), bits)
	if err != nil {
		// Out of range is the only way this fails on a number the grammar
		// above accepted, and it is refused rather than kept: ParseFloat
		// returns an infinity there, and an infinity is not a number JSON can
		// carry, so a codec that kept it would read a document into a value
		// that cannot be written back out.
		if errors.Is(err, strconv.ErrRange) {
			return 0, 0, errJSONRange
		}
		return 0, 0, errJSONSyntax
	}
	return held, hi, nil
}

// jsonScanBool reads true or false.
func jsonScanBool(b []byte, i int) (bool, int, error) {
	switch {
	case i+4 <= len(b) && string(b[i:i+4]) == "true":
		return true, i + 4, nil
	case i+5 <= len(b) && string(b[i:i+5]) == "false":
		return false, i + 5, nil
	default:
		return false, 0, errJSONSyntax
	}
}

// jsonScanNull reads null, and reports whether that is what was there.
//
// A reader asks before it reads anything else, because null is what every
// shape may be instead of itself.
func jsonScanNull(b []byte, i int) (int, bool) {
	if i+4 <= len(b) && string(b[i:i+4]) == "null" {
		return i + 4, true
	}
	return i, false
}

// jsonSkipValue steps over a value nobody asked for, which is what an unknown
// member gets.
//
// Stepping over is not looking away. The standard library holds a member
// nothing reads to the same grammar as one everything reads — the syntax, the
// escapes, the number grammar, UTF-8, duplicate names in an object nobody
// wanted — so a reader that relaxed any of it for the members it skips would
// accept documents the rest of the world refuses. depth is how many values
// this one is already inside, which is what bounds a document that nests
// forever.
func jsonSkipValue(b []byte, i, depth int) (int, error) {
	i = jsonSkipSpace(b, i)
	if i >= len(b) {
		return 0, errJSONTruncated
	}

	switch b[i] {
	case '"':
		_, _, next, _, err := jsonScanString(b, i)
		return next, err

	case 't', 'f':
		_, next, err := jsonScanBool(b, i)
		return next, err

	case 'n':
		next, ok := jsonScanNull(b, i)
		if !ok {
			return 0, errJSONSyntax
		}
		return next, nil

	case '{':
		return jsonSkipObject(b, i+1, depth+1)

	case '[':
		return jsonSkipArray(b, i+1, depth+1)

	default:
		_, hi, err := jsonScanNumber(b, i)
		return hi, err
	}
}

// jsonSkipObject steps over an object's members, holding each to the grammar
// and the whole set to the no-duplicates rule. i is just past the brace.
func jsonSkipObject(b []byte, i, depth int) (int, error) {
	if depth > jsonMaxDepth {
		return 0, errJSONDeep
	}

	var names jsonNames
	for first := true; ; first = false {
		next, done, err := jsonMemberNext(b, i, first)
		if err != nil {
			return 0, err
		}
		if done {
			return next, nil
		}

		lo, hi, at, esc, err := jsonMemberName(b, next)
		if err != nil {
			return 0, err
		}
		if names.unknown(b, lo, hi, esc) {
			return 0, errJSONDuplicate
		}

		if i, err = jsonSkipValue(b, at, depth); err != nil {
			return 0, err
		}
	}
}

// jsonSkipArray steps over an array's elements. i is just past the bracket.
func jsonSkipArray(b []byte, i, depth int) (int, error) {
	if depth > jsonMaxDepth {
		return 0, errJSONDeep
	}

	for first := true; ; first = false {
		next, done, err := jsonElementNext(b, i, first)
		if err != nil {
			return 0, err
		}
		if done {
			return next, nil
		}

		if i, err = jsonSkipValue(b, next, depth); err != nil {
			return 0, err
		}
	}
}

// jsonNames records the member names an object has already used, so that a
// name written twice is refused the way the standard library refuses it.
//
// Two halves, because the two cases are not alike. A member the subject
// declares is one of a set known when the code was written, so it is a bit in
// a word and the test is an and. A member nothing declares is an arbitrary
// string, and the only thing to compare it against is the ones before it —
// held as the spans they occupy in the document rather than as strings, so
// that an object with no unknown members in it allocates nothing and an object
// with a few costs a few comparisons.
//
// Quadratic in the number of unknown members, which is the right shape: a
// document carrying many members nothing reads is rare, and the map that would
// make it linear costs an allocation and a hash on every document that carries
// none.
// declared holds one bit per member the subject declares, and spilled the rest
// for a subject with more than sixty-four. few holds the first several member
// names nothing declared, in place, so that the ordinary object costs no
// allocation to check; more holds the rest of a document that turns out to
// carry many, and n counts what few holds.
type jsonNames struct {
	declared uint64
	spilled  []uint64
	few      [8]jsonSpan
	n        int
	more     []jsonSpan
}

// jsonSpan is where one member name sits in the document, and whether reading
// it means decoding an escape.
type jsonSpan struct {
	lo, hi int
	esc    bool
}

// declare records a declared member by its index, and reports whether it had
// already been recorded.
func (n *jsonNames) declare(index int) bool {
	word, bit := index/64, uint(index%64)
	if word == 0 {
		if n.declared&(1<<bit) != 0 {
			return true
		}
		n.declared |= 1 << bit
		return false
	}

	for len(n.spilled) < word {
		n.spilled = append(n.spilled, 0)
	}
	if n.spilled[word-1]&(1<<bit) != 0 {
		return true
	}
	n.spilled[word-1] |= 1 << bit
	return false
}

// saw reports whether a declared member arrived.
//
// What it is for is the rule a member cannot answer by arriving: a member the
// document never mentioned is one whose rules have to be held against whatever
// the destination already had, and this is how a reader knows which those are.
func (n *jsonNames) saw(index int) bool {
	word, bit := index/64, uint(index%64)
	if word == 0 {
		return n.declared&(1<<bit) != 0
	}
	if word > len(n.spilled) {
		return false
	}
	return n.spilled[word-1]&(1<<bit) != 0
}

// unknown records a member name nothing declared, and reports whether the same
// name has already been seen.
//
// Two names are the same name when they decode to the same string, which for
// the ordinary pair — neither carrying an escape — is their bytes being equal.
// A pair where either side carries one is decoded first, because "a" and
// "a" are one name written two ways and the standard library refuses the
// pair.
func (n *jsonNames) unknown(b []byte, lo, hi int, esc bool) bool {
	held := jsonSpan{lo: lo, hi: hi, esc: esc}
	for at := range n.n {
		if jsonSameName(b, n.few[at], held) {
			return true
		}
	}
	for _, seen := range n.more {
		if jsonSameName(b, seen, held) {
			return true
		}
	}

	if n.n < len(n.few) {
		n.few[n.n] = held
		n.n++
		return false
	}
	n.more = append(n.more, held)
	return false
}

// jsonSameName reports whether two spans hold one member name.
func jsonSameName(b []byte, a, c jsonSpan) bool {
	if !a.esc && !c.esc {
		return bytes.Equal(b[a.lo:a.hi], b[c.lo:c.hi])
	}

	// At least one side carries an escape, so both are decoded. The contents
	// were validated when they were scanned, so decoding cannot fail — and a
	// scratch pair per comparison is fine on a path only an escaped name
	// reaches.
	one, two := jsonTakeScratch(), jsonTakeScratch()
	left, _ := jsonUnescape((*one)[:0], b[a.lo:a.hi])
	right, _ := jsonUnescape((*two)[:0], b[c.lo:c.hi])
	same := bytes.Equal(left, right)
	*one, *two = left, right
	jsonDropScratch(one)
	jsonDropScratch(two)
	return same
}

// jsonMemberNext finds the next member of an object, stepping over the comma
// that separates it from the one before. It returns where the member's name
// begins, or that the closing brace ended the object.
//
// The grammar lives here so that every reader of an object — a generated
// decoder, the skipper above, a map — refuses the same documents: a comma
// before the first member, a missing one between two, and a trailing one
// before the brace.
func jsonMemberNext(b []byte, i int, first bool) (int, bool, error) {
	i = jsonSkipSpace(b, i)
	if i >= len(b) {
		return 0, false, errJSONTruncated
	}

	switch b[i] {
	case '}':
		return i + 1, true, nil
	case ',':
		if first {
			return 0, false, errJSONSyntax
		}
		return jsonSkipSpace(b, i+1), false, nil
	default:
		if !first {
			return 0, false, errJSONSyntax
		}
		return i, false, nil
	}
}

// jsonMemberName reads a member's name and the colon after it, and returns
// where the member's value begins.
func jsonMemberName(b []byte, i int) (lo, hi, next int, esc bool, err error) {
	lo, hi, next, esc, err = jsonScanString(b, i)
	if err != nil {
		return 0, 0, 0, false, err
	}

	next = jsonSkipSpace(b, next)
	if next >= len(b) {
		return 0, 0, 0, false, errJSONTruncated
	}
	if b[next] != ':' {
		return 0, 0, 0, false, errJSONSyntax
	}
	return lo, hi, jsonSkipSpace(b, next+1), esc, nil
}

// jsonElementNext finds the next element of an array, stepping over the comma
// that separates it from the one before. It returns where the element begins,
// or that the closing bracket ended the array.
func jsonElementNext(b []byte, i int, first bool) (int, bool, error) {
	i = jsonSkipSpace(b, i)
	if i >= len(b) {
		return 0, false, errJSONTruncated
	}

	switch b[i] {
	case ']':
		return i + 1, true, nil
	case ',':
		if first {
			return 0, false, errJSONSyntax
		}
		return jsonSkipSpace(b, i+1), false, nil
	default:
		if !first {
			return 0, false, errJSONSyntax
		}
		return i, false, nil
	}
}

// jsonName returns a member name's bytes, decoding them through scratch when
// the name carries an escape.
//
// The ordinary name is handed back as the span it already is, so dispatching
// on it costs nothing; switch string(name) compares without allocating by
// compiler rule. The contents were validated by the scan, so decoding cannot
// fail.
func jsonName(b []byte, lo, hi int, esc bool, scratch *[]byte) []byte {
	if !esc {
		return b[lo:hi]
	}
	*scratch, _ = jsonUnescape((*scratch)[:0], b[lo:hi])
	return *scratch
}

// jsonString returns the string a scanned span holds.
//
// borrow is the sharp edge, asked for by name: the string returned points into
// b rather than copying out of it, so it is exact as long as b outlives it and
// is not written over, and wrong the moment either fails. A span with an
// escape in it is decoded into fresh bytes either way, so borrowing buys
// nothing there and the copy is not a choice.
func jsonString(b []byte, lo, hi int, esc, borrow bool) string {
	if esc {
		scratch := jsonTakeScratch()
		held, _ := jsonUnescape((*scratch)[:0], b[lo:hi])
		out := string(held)
		*scratch = held
		jsonDropScratch(scratch)
		return out
	}

	if lo == hi {
		return ""
	}
	if borrow {
		return unsafe.String(&b[lo], hi-lo) //nolint:gosec // The borrow is the function's contract, stated above; the span was bounds-checked by the scan.
	}
	return string(b[lo:hi])
}

// jsonAppendBytes appends a byte slice as JSON carries one: base64 in a
// string. A nil slice is the empty string rather than null, which is the
// standard library's encoding and not a choice available here.
func jsonAppendBytes(dst, held []byte) []byte {
	dst = append(dst, '"')
	dst = base64.StdEncoding.AppendEncode(dst, held)
	return append(dst, '"')
}

// jsonScanBytes decodes the base64 a scanned string span holds, into dst's
// capacity where it fits.
//
// Line breaks are refused by hand, because the two libraries disagree about
// them: the base64 package skips a newline inside an encoding and the standard
// library's JSON reader refuses it, and the reader is the behaviour being
// promised. Padding bits under the final character are not checked, because
// the reader does not check them either.
func jsonScanBytes(b []byte, lo, hi int, esc bool, dst []byte) ([]byte, error) {
	src := b[lo:hi]
	if esc {
		scratch := jsonTakeScratch()
		defer jsonDropScratch(scratch)
		held, _ := jsonUnescape((*scratch)[:0], src)
		*scratch = held
		src = held
	}

	for _, c := range src {
		if c == '\r' || c == '\n' {
			return nil, errJSONSyntax
		}
	}

	need := base64.StdEncoding.DecodedLen(len(src))
	if cap(dst) < need {
		dst = make([]byte, need)
	} else {
		dst = dst[:need]
	}
	n, err := base64.StdEncoding.Decode(dst, src)
	if err != nil {
		return nil, errJSONSyntax
	}
	return dst[:n], nil
}

// jsonWroteEmpty reports whether the value written at b[at:] is one of the
// four JSON empties, which is what omitempty leaves out: null, the empty
// string, the empty object and the empty array.
func jsonWroteEmpty(b []byte, at int) bool {
	switch len(b) - at {
	case 2:
		return (b[at] == '"' && b[at+1] == '"') ||
			(b[at] == '{' && b[at+1] == '}') ||
			(b[at] == '[' && b[at+1] == ']')
	case 4:
		return b[at] == 'n' && b[at+1] == 'u' && b[at+2] == 'l' && b[at+3] == 'l'
	default:
		return false
	}
}

// jsonKeysScratch lends the slices a map's keys are gathered and sorted in.
var jsonKeysScratch = sync.Pool{New: func() any { held := make([]string, 0, 16); return &held }}

// jsonSortedKeys gathers a map's keys and sorts them, into a borrowed slice.
//
// Members of an object come out in sorted key order, always: range order
// varies between two runs over one map, and generated output that differed
// between runs would be a diff nobody could account for. The slice is borrowed
// rather than made because gathering keys is the entire allocation profile of
// writing a map, and give it back with [jsonDropKeys].
func jsonSortedKeys[K ~string, V any](m map[K]V) *[]string {
	keys := jsonTakeKeys()
	held := (*keys)[:0]
	for k := range m {
		held = append(held, string(k))
	}
	slices.Sort(held)
	*keys = held
	return keys
}

// jsonTakeKeys borrows a key slice.
func jsonTakeKeys() *[]string {
	if held, ok := jsonKeysScratch.Get().(*[]string); ok {
		return held
	}
	fresh := make([]string, 0, 16)
	return &fresh
}

// jsonDropKeys returns a key slice, unless it has grown past what is worth
// keeping. What it held is cleared first, so the pool does not keep somebody's
// strings alive for the life of the process.
func jsonDropKeys(keys *[]string) {
	if cap(*keys) > 1<<12 {
		return
	}
	clear(*keys)
	jsonKeysScratch.Put(keys)
}

// jsonFinish turns an appended document into the slice MarshalJSON answers
// with: an exact copy, with the borrowed buffer handed back.
//
// The copy is not hesitancy. The buffer is pooled, and a caller holding a
// slice of it while the next caller appends over it is a race only the
// detector would ever see.
func jsonFinish(scratch *[]byte, b []byte, err error) ([]byte, error) {
	*scratch = b
	var out []byte
	if err == nil {
		out = make([]byte, len(b))
		copy(out, b)
	}
	jsonDropScratch(scratch)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// jsonCannotRead says that a value of the wrong kind arrived for a target,
// naming both.
func jsonCannotRead(what string, b []byte, i int) error {
	return fmt.Errorf("cannot read %s from a JSON %s", what, jsonKindName(b, i))
}

// jsonKindName names the kind of the value beginning at b[i], for an error a
// person reads.
func jsonKindName(b []byte, i int) string {
	if i >= len(b) {
		return "end of input"
	}
	switch b[i] {
	case '"':
		return "string"
	case '{':
		return "object"
	case '[':
		return "array"
	case 't', 'f':
		return "boolean"
	case 'n':
		return "null"
	case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
		return "number"
	default:
		return "value no grammar names"
	}
}

// jsonFlushWindow is how many bytes a streaming writer gathers before handing
// them to the writer beneath it.
const jsonFlushWindow = 1 << 12

// jsonScanState carries the search for the end of one value across refills,
// which is what lets a reader hand a decoder whole elements while holding only
// the largest one.
// depth is how many objects and arrays the scan is inside. str records being
// inside a string, and esc that the next byte of it is escaped — both needed
// so that a brace inside a string does not close the object it appears in, and
// a refill can resume mid-string.
type jsonScanState struct {
	depth int
	str   bool
	esc   bool
}

// jsonValueEnd scans b from i for the end of the value the state is in the
// middle of. It returns where the value ends, or that the window ran out and
// the scan should resume, with the same state, once more bytes arrive.
//
// It finds the end without judging what it finds: the bytes are handed whole
// to a decoder that validates them, so validating here would read everything
// twice. What it cannot get wrong is strings and nesting, since those decide
// where the end is.
func jsonValueEnd(b []byte, i int, st *jsonScanState) (int, bool) {
	for ; i < len(b); i++ {
		c := b[i]

		if st.str {
			switch {
			case st.esc:
				st.esc = false
			case c == '\\':
				st.esc = true
			case c == '"':
				st.str = false
				if st.depth == 0 {
					return i + 1, false
				}
			}
			continue
		}

		switch c {
		case '"':
			st.str = true
		case '{', '[':
			st.depth++
		case '}', ']':
			if st.depth == 0 {
				// The bracket closing whatever holds a bare scalar, which is
				// not part of it.
				return i, false
			}
			st.depth--
			if st.depth == 0 {
				return i + 1, false
			}
		case ',', ' ', '\t', '\n', '\r':
			if st.depth == 0 {
				// The delimiter after a bare scalar, which is not part of it.
				return i, false
			}
		}
	}
	return len(b), true
}

// jsonFeed reads a document out of a reader a window at a time, handing over
// one complete value's bytes at a time.
//
// The window grows to the largest single value and no further, which is the
// bound a streaming reader promises: the document as a whole never has to fit.
// The bytes handed out are valid until the next call that reads, because the
// window is compacted and refilled underneath them.
// i is where the scan stands in the window, and done counts the bytes already
// dropped off the front of it — their sum is the position in the stream, which
// is what a caller reporting how much it consumed needs.
type jsonFeed struct {
	r    io.Reader
	buf  *[]byte
	i    int
	done int64
}

// jsonNewFeed starts a feed over a reader, on a borrowed window.
//
// The window is emptied before it is read into, because a borrowed buffer
// arrives holding whatever its last user composed in it — and a feed that
// started past index zero would read a stale document nobody sent.
func jsonNewFeed(r io.Reader) jsonFeed {
	buf := jsonTakeScratch()
	*buf = (*buf)[:0]
	return jsonFeed{r: r, buf: buf}
}

// close hands the window back. The feed is not usable after it.
func (f *jsonFeed) close() {
	if f.buf != nil {
		jsonDropScratch(f.buf)
		f.buf = nil
	}
}

// offset is how many bytes of the stream have been consumed.
func (f *jsonFeed) offset() int64 { return f.done + int64(f.i) }

// more reads another chunk into the window, growing it when it is full.
//
// A read that returns bytes and an error keeps the bytes and holds the error
// for the call that finds the window empty, which is the contract io.Reader
// asks its callers to follow.
func (f *jsonFeed) more() error {
	held := *f.buf
	if cap(held)-len(held) < 128 {
		held = slices.Grow(held, max(512, cap(held)))
	}

	n, err := f.r.Read(held[len(held):cap(held)])
	held = held[:len(held)+n]
	*f.buf = held
	if n == 0 {
		if err == nil {
			return io.ErrNoProgress
		}
		return err
	}
	return nil
}

// peek returns the first byte of the next value, past whatever whitespace
// stands before it, without consuming it. An exhausted reader answers io.EOF.
func (f *jsonFeed) peek() (byte, error) {
	for {
		f.i = jsonSkipSpace(*f.buf, f.i)
		if f.i < len(*f.buf) {
			return (*f.buf)[f.i], nil
		}
		if err := f.more(); err != nil {
			return 0, err
		}
	}
}

// take consumes the byte peek answered with.
func (f *jsonFeed) take() { f.i++ }

// null consumes the null literal beginning at the scan position, and reports
// whether that is what was there.
func (f *jsonFeed) null() (bool, error) {
	for len(*f.buf)-f.i < 4 {
		if err := f.more(); err != nil {
			return false, err
		}
	}
	if next, ok := jsonScanNull(*f.buf, f.i); ok {
		f.i = next
		return true, nil
	}
	return false, nil
}

// cannotRead names the kind of the value the scan stands before, for an error
// a person reads.
func (f *jsonFeed) cannotRead(what string) error {
	return jsonCannotRead(what, *f.buf, f.i)
}

// element returns the complete bytes of the next value, refilling from the
// reader until its end is in the window.
//
// The bytes are the window's and stay right only until the next call that
// reads, so a caller decodes them before asking again — and never lends them
// out, which is why a streaming reader cannot offer borrowing.
func (f *jsonFeed) element() ([]byte, error) {
	// What was consumed is dropped first, so the window holds this value and
	// not the document so far.
	if f.i > 0 {
		held := *f.buf
		f.done += int64(f.i)
		*f.buf = held[:copy(held, held[f.i:])]
		f.i = 0
	}

	var st jsonScanState
	at := 0
	for {
		end, needs := jsonValueEnd(*f.buf, at, &st)
		if !needs {
			f.i = end
			return (*f.buf)[:end], nil
		}
		at = end
		if err := f.more(); err != nil {
			return nil, err
		}
	}
}

// Person satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ json.Marshaler   = *new(Person)
	_ json.Unmarshaler = (*Person)(nil)
	_ fmt.Stringer     = *new(Person)
	_ slog.LogValuer   = *new(Person)
)

// Code satisfies these.
//
// The claim is checked when the package is built rather than when a caller
// first tries, so a stack that stops satisfying one of these fails here
// rather than at somebody's call site. And a reader who is not going to read
// forty methods can see what they add up to.
var (
	_ fmt.Stringer             = *new(Code)
	_ encoding.TextAppender    = *new(Code)
	_ encoding.TextMarshaler   = *new(Code)
	_ encoding.TextUnmarshaler = (*Code)(nil)
)
