// Code generated by forge. DO NOT EDIT.
//
// forge v1.2.3
// markers v1.2.3
// go go1.27.0
// inputs ecc36f3b4fd95a22

//go:build forgespec

package model

import (
	"cmp"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"io"
	"iter"
	"sort"
)

type PeopleSeq struct {
	Seq[Person]
}

func (c People) Seq() PeopleSeq {
	panic("forge stub")
}
func (c People) IDs() []int {
	panic("forge stub")
}
func (c People) Names() []string {
	panic("forge stub")
}
func (c People) Ages() []int {
	panic("forge stub")
}
func (c People) Secrets() []string {
	panic("forge stub")
}
func (c People) SortedByID() []Person {
	panic("forge stub")
}
func (c People) Less(i, j int) bool {
	panic("forge stub")
}
func (c People) Swap(i, j int) {
	panic("forge stub")
}

func (c People) project[V any](of func(Person) V) []V { panic("forge stub") }

func (c People) ordered[K cmp.Ordered](by func(Person) K) []Person { panic("forge stub") }

func NewPeople(elems ...Person) People { panic("forge stub") }

func (s People) Len() int { panic("forge stub") }

func (s People) All() iter.Seq[Person] { panic("forge stub") }

func (s People) Backward() iter.Seq[Person] { panic("forge stub") }

func (s *People) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (s *People) Reset() { panic("forge stub") }

func (c People) MarshalJSONTo(enc *jsontext.Encoder) error { panic("forge stub") }

type peopleCounting struct {
	to io.Writer
	n  int64
}

func (w *peopleCounting) Write(p []byte) (int, error) { panic("forge stub") }

func (c People) WriteTo(w io.Writer) (int64, error) { panic("forge stub") }

func (c *People) UnmarshalJSONFrom(dec *jsontext.Decoder) error { panic("forge stub") }

func (c *People) ReadFrom(r io.Reader) (int64, error) { panic("forge stub") }

var (
	_ io.WriterTo          = *new(People)
	_ io.ReaderFrom        = (*People)(nil)
	_ json.MarshalerTo     = *new(People)
	_ json.UnmarshalerFrom = (*People)(nil)
	_ sort.Interface       = *new(People)
)

var _ func(*People) iter.Seq[Person] = (*People).All

func NewCodes(elems ...Code) Codes { panic("forge stub") }

func (s Codes) Len() int { panic("forge stub") }

func (s Codes) All() iter.Seq[Code] { panic("forge stub") }

func (s Codes) Backward() iter.Seq[Code] { panic("forge stub") }

func (s *Codes) AppendSeq(seq iter.Seq[Code]) { panic("forge stub") }

func (s *Codes) Reset() { panic("forge stub") }

var _ func(*Codes) iter.Seq[Code] = (*Codes).All

func NewCrowd(elems ...Person) Crowd { panic("forge stub") }

func (s Crowd) Len() int { panic("forge stub") }

func (s Crowd) All() iter.Seq[Person] { panic("forge stub") }

func (s Crowd) Backward() iter.Seq[Person] { panic("forge stub") }

func (s *Crowd) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (s *Crowd) Reset() { panic("forge stub") }

var _ func(*Crowd) iter.Seq[Person] = (*Crowd).All
