package generate

import "strings"

// The names generated files take.
//
// One file per package, holding everything every declaration in it asked for.
// A file per declaration read well in a diff — the name said which declaration
// had changed before anybody opened it — and cost more than it was worth
// everywhere else: a package's output was spread over as many files as it had
// declarations plus two, a rename left one behind, two declarations whose names
// differed only in case wanted one file, and a declaration called Windows or
// Data_linux wanted a file the compiler quietly leaves out of the build. None
// of those exists when the name is a constant.
//
// The gen.go ending is the convention Go tools have settled on, and it is worth
// more than the zz prefix that came before it: the prefix sorted forge's output
// below hand-written files in a listing, and the suffix says what the file is
// wherever it is read.
const (
	// file is what every ordinary build reads.
	file = "forge.gen.go"

	// stub is what stands in for it under the tag. See [Stubs].
	stub = "forge_stubs.gen.go"

	// legacy is what forge called its output when there was one file per
	// declaration. Nothing writes it any more and [Ours] still knows it, so
	// that upgrading forge reports the files left behind rather than leaving a
	// package that does not build with nothing to say why.
	legacy = "zz_forge_"
)

// Name returns the file a package's generated code goes in.
func Name() string { return file }

// Stubs names the file standing in for a package's output under the tag.
//
// A package holding a spec-form declaration writes two files rather than one,
// and there is no arrangement in which it writes fewer. The declaration's type
// is written by forge in one build and by the author's own spec file in the
// other, so the two can never be in scope together — which is what the
// complementary constraints are for, and what makes a second file a property of
// the language rather than a choice made here.
//
// Exactly one of the two is in any build, so a package still has one generated
// file however it is compiled.
func Stubs() string { return stub }

// Names returns every file forge writes into a package, so that a caller
// looking for its output asks for the convention rather than spelling it again.
//
// A second spelling is one that agrees until somebody changes this one, and
// what it would then find is nothing — silently, since a search that matches no
// files looks exactly like a directory with no generated files in it.
func Names() []string { return []string{file, stub} }

// Ours reports whether a file is named the way generation names one.
//
// It is only about the name, which is a convention anybody could follow — what
// says a file is forge's is the line inside it. A caller deciding whether to
// touch a file asks both, and asks this one first because it costs no read.
//
// The names forge used to write are still recognised, and that is the whole of
// what makes upgrading survivable. A package generated by an older forge holds
// a file per declaration, all of them declaring methods the new file declares
// as well; the package stops building, and the only thing that can say why is
// something that still knows what those files were called.
func Ours(name string) bool {
	if !strings.HasSuffix(name, ".go") {
		return false
	}
	return name == file || name == stub || strings.HasPrefix(name, legacy)
}

// Superseded reports whether a file is one an older forge wrote and this one
// does not.
//
// Told apart from [Ours] because the two are acted on differently: a file this
// forge writes is one it overwrites, and a file an older one wrote is one
// nobody will overwrite ever again — it has to be deleted, and saying so is the
// only help an author gets.
func Superseded(name string) bool {
	return Ours(name) && name != file && name != stub
}
