// Code generated by forge. DO NOT EDIT.
//
// forge v1.2.3
// markers v1.2.3
// go go1.27.0
// inputs 76cc5f31ede511be

//go:build forgespec

package matrix

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"iter"
	"sync"
)

func NewGuardedPersons() *GuardedPersons { panic("forge stub") }

func (g *GuardedPersons) Do(f func(v GuardedPersonsView)) { panic("forge stub") }

func (g *GuardedPersons) RDo(f func(v GuardedPersonsView)) { panic("forge stub") }

func (g *GuardedPersons) Snapshot() []Person { panic("forge stub") }

func (g *GuardedPersons) Len() int { panic("forge stub") }

func (g *GuardedPersons) MarshalJSONTo(enc *jsontext.Encoder) error { panic("forge stub") }

type GuardedPersonsView struct {
	held *guardedPersonsHeld
}

func (v GuardedPersonsView) Cap() int { panic("forge stub") }

func (v GuardedPersonsView) Len() int { panic("forge stub") }

func (v GuardedPersonsView) All() iter.Seq[Person] { panic("forge stub") }

func (v GuardedPersonsView) Backward() iter.Seq[Person] { panic("forge stub") }

func (v GuardedPersonsView) Reset() { panic("forge stub") }

func (v GuardedPersonsView) Push(a0 Person) { panic("forge stub") }

func (v GuardedPersonsView) AppendSeq(a0 iter.Seq[Person]) { panic("forge stub") }

const guardedPersonsHeldFixedCap = 64

type guardedPersonsHeld struct {
	buf  []Person
	head int
	n    int
}

func newGuardedPersonsHeld() *guardedPersonsHeld { panic("forge stub") }

func (r *guardedPersonsHeld) Cap() int { panic("forge stub") }

func (r *guardedPersonsHeld) Len() int { panic("forge stub") }

func (r *guardedPersonsHeld) Push(v Person) { panic("forge stub") }

func (r *guardedPersonsHeld) All() iter.Seq[Person] { panic("forge stub") }

func (r *guardedPersonsHeld) Backward() iter.Seq[Person] { panic("forge stub") }

func (r *guardedPersonsHeld) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (r *guardedPersonsHeld) Reset() { panic("forge stub") }

func (r *guardedPersonsHeld) built() { panic("forge stub") }

func guardedPersonsHeldIndexOf(from, i, size int) int { panic("forge stub") }

var (
	_ json.MarshalerTo = (*GuardedPersons)(nil)
)

func NewGuardedPersonsEncodeLocked() *GuardedPersonsEncodeLocked { panic("forge stub") }

func (g *GuardedPersonsEncodeLocked) Do(f func(v GuardedPersonsEncodeLockedView)) {
	panic("forge stub")
}

func (g *GuardedPersonsEncodeLocked) RDo(f func(v GuardedPersonsEncodeLockedView)) {
	panic("forge stub")
}

func (g *GuardedPersonsEncodeLocked) Snapshot() []Person { panic("forge stub") }

func (g *GuardedPersonsEncodeLocked) Len() int { panic("forge stub") }

func (g *GuardedPersonsEncodeLocked) MarshalJSONTo(enc *jsontext.Encoder) error { panic("forge stub") }

type GuardedPersonsEncodeLockedView struct {
	held *guardedPersonsEncodeLockedHeld
}

func (v GuardedPersonsEncodeLockedView) Cap() int { panic("forge stub") }

func (v GuardedPersonsEncodeLockedView) Len() int { panic("forge stub") }

func (v GuardedPersonsEncodeLockedView) All() iter.Seq[Person] { panic("forge stub") }

func (v GuardedPersonsEncodeLockedView) Backward() iter.Seq[Person] { panic("forge stub") }

func (v GuardedPersonsEncodeLockedView) Reset() { panic("forge stub") }

func (v GuardedPersonsEncodeLockedView) Push(a0 Person) { panic("forge stub") }

func (v GuardedPersonsEncodeLockedView) AppendSeq(a0 iter.Seq[Person]) { panic("forge stub") }

const guardedPersonsEncodeLockedHeldFixedCap = 64

type guardedPersonsEncodeLockedHeld struct {
	buf  []Person
	head int
	n    int
}

func newGuardedPersonsEncodeLockedHeld() *guardedPersonsEncodeLockedHeld { panic("forge stub") }

func (r *guardedPersonsEncodeLockedHeld) Cap() int { panic("forge stub") }

func (r *guardedPersonsEncodeLockedHeld) Len() int { panic("forge stub") }

func (r *guardedPersonsEncodeLockedHeld) Push(v Person) { panic("forge stub") }

func (r *guardedPersonsEncodeLockedHeld) All() iter.Seq[Person] { panic("forge stub") }

func (r *guardedPersonsEncodeLockedHeld) Backward() iter.Seq[Person] { panic("forge stub") }

func (r *guardedPersonsEncodeLockedHeld) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (r *guardedPersonsEncodeLockedHeld) Reset() { panic("forge stub") }

func (r *guardedPersonsEncodeLockedHeld) built() { panic("forge stub") }

func guardedPersonsEncodeLockedHeldIndexOf(from, i, size int) int { panic("forge stub") }

var (
	_ json.MarshalerTo = (*GuardedPersonsEncodeLocked)(nil)
)

func NewGuardedPersonsExposeLocker() *GuardedPersonsExposeLocker { panic("forge stub") }

func (g *GuardedPersonsExposeLocker) Do(f func(v GuardedPersonsExposeLockerView)) {
	panic("forge stub")
}

func (g *GuardedPersonsExposeLocker) RDo(f func(v GuardedPersonsExposeLockerView)) {
	panic("forge stub")
}

func (g *GuardedPersonsExposeLocker) Snapshot() []Person { panic("forge stub") }

func (g *GuardedPersonsExposeLocker) Len() int { panic("forge stub") }

func (g *GuardedPersonsExposeLocker) Lock() { panic("forge stub") }

func (g *GuardedPersonsExposeLocker) Unlock() { panic("forge stub") }

func (g *GuardedPersonsExposeLocker) MarshalJSONTo(enc *jsontext.Encoder) error { panic("forge stub") }

type GuardedPersonsExposeLockerView struct {
	held *guardedPersonsExposeLockerHeld
}

func (v GuardedPersonsExposeLockerView) Cap() int { panic("forge stub") }

func (v GuardedPersonsExposeLockerView) Len() int { panic("forge stub") }

func (v GuardedPersonsExposeLockerView) All() iter.Seq[Person] { panic("forge stub") }

func (v GuardedPersonsExposeLockerView) Backward() iter.Seq[Person] { panic("forge stub") }

func (v GuardedPersonsExposeLockerView) Reset() { panic("forge stub") }

func (v GuardedPersonsExposeLockerView) Push(a0 Person) { panic("forge stub") }

func (v GuardedPersonsExposeLockerView) AppendSeq(a0 iter.Seq[Person]) { panic("forge stub") }

const guardedPersonsExposeLockerHeldFixedCap = 64

type guardedPersonsExposeLockerHeld struct {
	buf  []Person
	head int
	n    int
}

func newGuardedPersonsExposeLockerHeld() *guardedPersonsExposeLockerHeld { panic("forge stub") }

func (r *guardedPersonsExposeLockerHeld) Cap() int { panic("forge stub") }

func (r *guardedPersonsExposeLockerHeld) Len() int { panic("forge stub") }

func (r *guardedPersonsExposeLockerHeld) Push(v Person) { panic("forge stub") }

func (r *guardedPersonsExposeLockerHeld) All() iter.Seq[Person] { panic("forge stub") }

func (r *guardedPersonsExposeLockerHeld) Backward() iter.Seq[Person] { panic("forge stub") }

func (r *guardedPersonsExposeLockerHeld) AppendSeq(seq iter.Seq[Person]) { panic("forge stub") }

func (r *guardedPersonsExposeLockerHeld) Reset() { panic("forge stub") }

func (r *guardedPersonsExposeLockerHeld) built() { panic("forge stub") }

func guardedPersonsExposeLockerHeldIndexOf(from, i, size int) int { panic("forge stub") }

var (
	_ json.MarshalerTo = (*GuardedPersonsExposeLocker)(nil)
	_ sync.Locker      = (*GuardedPersonsExposeLocker)(nil)
)
