package main

import (
	"bytes"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"

	"github.com/okian/forge/internal/discover"
	"github.com/okian/forge/internal/load"
	"github.com/okian/forge/internal/model"
	"github.com/okian/forge/internal/resolve"
)

// generating builds a run holding one declaration in a package whose files live in
// dir, which is what generation writes beside.
//
// Built rather than loaded. What generation does with a resolved declaration is
// the thing under test, and a fixture module would put a go/packages session
// and a type-checker between this file and a written file.
func generating(t *testing.T, dir, declared string) *stack {
	t.Helper()

	source := filepath.Join(dir, "person.go")
	if err := os.WriteFile(source, []byte("package model\n"), 0o600); err != nil {
		t.Fatalf("making the fixture: %v", err)
	}

	pkg := &packages.Package{
		PkgPath: "example.com/model",
		Name:    "model",
		GoFiles: []string{source},
	}

	held := types.NewPackage("example.com/model", "model")
	obj := types.NewTypeName(token.NoPos, held, "Person", nil)

	subject := &model.Struct{
		Named:  types.NewNamed(obj, types.NewStruct(nil, nil), nil),
		Fields: []model.Field{{Name: "Name", Exported: true, Type: model.Classified{Type: types.Typ[types.String]}}},
	}

	candidate := discover.Candidate{
		Name: declared, Pkg: pkg, Form: model.FormInline,
		Pos: token.Position{Filename: source, Line: 8, Column: 6},
	}

	return &stack{
		session:    &load.Session{Fset: token.NewFileSet(), Packages: []*packages.Package{pkg}},
		candidates: []discover.Candidate{candidate},
		modelled: []request{{
			Declaration: resolve.Declaration{
				Candidate: candidate,
				Stack:     []model.LayerRef{{Origin: model.TypeRef{Pkg: model.MarkerPkg, Name: "Collection"}}},
			},
			Model: subject,
		}},
	}
}

// broken makes the package of a run one that does not build, which is the only
// state a file forge left behind is worth naming in.
func broken(s *stack) *stack {
	s.session.Packages[0].Errors = []packages.Error{{Msg: "undefined: Widgets"}}
	return s
}

// running drives the generate verb over a run, and returns what it said.
func running(t *testing.T, s *stack, args ...string) (string, string, error) {
	t.Helper()

	out, errs := &bytes.Buffer{}, &bytes.Buffer{}
	env := &environment{stdout: out, stderr: errs, pipeline: over(s), verbose: true}

	cmd, ok := lookup("generate")
	if !ok {
		t.Fatal("generate is not a command")
	}

	err := cmd.run(env, cmd, args)
	return out.String(), errs.String(), err
}

// A run writes what its declarations asked for, beside the source they were
// found in, and says what it did.
func TestARunWritesWhatWasAskedFor(t *testing.T) {
	dir := t.TempDir()
	s := generating(t, dir, "Persons")

	_, said, err := running(t, s, "./...")
	if err != nil {
		t.Fatalf("generating: %v\n%s", err, said)
	}

	for _, name := range []string{"zz_forge_persons.go", "zz_forge_shared.go"} {
		held, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("%s was not written: %v", name, err)
		}
		if !bytes.Contains(held, []byte("Code generated by forge")) {
			t.Errorf("%s does not say it was generated", name)
		}
	}

	if !strings.Contains(said, "wrote 2 files") {
		t.Errorf("the run said\n%s", said)
	}
}

// The second run over unchanged inputs writes nothing, which is what keeps a
// generated file out of every diff and every rebuild that did not touch it.
func TestASecondRunTouchesNothing(t *testing.T) {
	dir := t.TempDir()

	if _, said, err := running(t, generating(t, dir, "Persons"), "./..."); err != nil {
		t.Fatalf("the first run: %v\n%s", err, said)
	}

	before := modified(t, filepath.Join(dir, "zz_forge_persons.go"))

	_, said, err := running(t, generating(t, dir, "Persons"), "./...")
	if err != nil {
		t.Fatalf("the second run: %v\n%s", err, said)
	}
	if !strings.Contains(said, "wrote 0 files") {
		t.Errorf("the second run said\n%s", said)
	}
	if after := modified(t, filepath.Join(dir, "zz_forge_persons.go")); !after.Equal(before) {
		t.Error("the second run rewrote a file holding what it would have written")
	}
}

// Neither flag that holds a run back writes anything, and one of them says what
// the difference would have been.
func TestTheFlagsThatHoldARunBack(t *testing.T) {
	for _, flag := range []string{"--dry-run", "--diff"} {
		t.Run(flag, func(t *testing.T) {
			dir := t.TempDir()

			shown, said, err := running(t, generating(t, dir, "Persons"), flag, "./...")
			if err != nil {
				t.Fatalf("generating: %v\n%s", err, said)
			}

			if _, err := os.Stat(filepath.Join(dir, "zz_forge_persons.go")); err == nil {
				t.Error("a run that was held back wrote a file")
			}
			if !strings.Contains(said, "would write 2 files") {
				t.Errorf("the run said\n%s", said)
			}

			if flag == "--diff" && !strings.Contains(shown, "+func (c Persons) Seq()") {
				t.Errorf("the difference does not show what would arrive:\n%s", shown)
			}
		})
	}
}

// A declaration whose subject was refused is one nothing can be generated for,
// and a run that found only those writes nothing rather than failing.
func TestARunWithNothingToGenerateFor(t *testing.T) {
	dir := t.TempDir()

	s := generating(t, dir, "Persons")
	s.modelled[0].Model = nil

	_, said, err := running(t, s, "./...")
	if err != nil {
		t.Fatalf("generating: %v\n%s", err, said)
	}
	if !strings.Contains(said, "wrote 0 files") {
		t.Errorf("the run said\n%s", said)
	}
}

// A declaration found in no package has nowhere to be written, and is passed
// over rather than written to the working directory.
func TestADeclarationInNoPackage(t *testing.T) {
	s := generating(t, t.TempDir(), "Persons")
	s.modelled[0].Declaration.Candidate.Pkg = nil

	_, said, err := running(t, s, "./...")
	if err != nil {
		t.Fatalf("generating: %v\n%s", err, said)
	}
	if !strings.Contains(said, "wrote 0 files") {
		t.Errorf("the run said\n%s", said)
	}
}

// A package whose files are known only as compiled ones, or as neither, is
// still a package with a directory or without one.
func TestWhereAPackagesFilesAre(t *testing.T) {
	cases := map[string]*packages.Package{
		"the ordinary files": {GoFiles: []string{"/a/b/person.go"}},
		"the compiled ones":  {CompiledGoFiles: []string{"/a/b/person.go"}},
		"anything else":      {OtherFiles: []string{"/a/b/person.s"}},
	}

	for name, pkg := range cases {
		if got := directory(pkg); got != filepath.Clean("/a/b") {
			t.Errorf("%s put the package in %q", name, got)
		}
	}

	if got := directory(&packages.Package{}); got != "" {
		t.Errorf("a package with no files at all is in %q", got)
	}
}

// A package is written whole or not at all. Its files reach into each other —
// a declaration's own file calls helpers that live in the one the package
// shares — so writing the half that succeeded leaves a package holding an
// answer to a question the other half was going to ask.
func TestAPackageIsWrittenWholeOrNotAtAll(t *testing.T) {
	dir := t.TempDir()

	s := generating(t, dir, "Persons")
	broken := generating(t, dir, "Widgets")

	// One declaration that generates and one that cannot: an option naming a
	// field the subject does not have.
	broken.modelled[0].Declaration.Candidate.Directives = []discover.Directive{{
		Layer: "collection", Args: "sort=Nonesuch",
		Text: "//forge:collection sort=Nonesuch", ArgsOffset: 19,
		Pos: token.Position{Filename: filepath.Join(dir, "person.go"), Line: 7, Column: 1},
	}}
	s.modelled = append(s.modelled, broken.modelled...)

	_, said, err := running(t, s, "./...")
	if err == nil {
		t.Fatalf("a package with a declaration that cannot generate reported success\n%s", said)
	}

	held, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("reading the package back: %v", err)
	}
	for _, entry := range held {
		if strings.HasPrefix(entry.Name(), "zz_forge_") {
			t.Errorf("%s was written for a package that could not be generated whole", entry.Name())
		}
	}
}

// --dry-run answers the question it was asked. A run that reported nothing
// would be indistinguishable from one that found nothing to do, which is the
// one thing the flag exists to tell apart.
func TestWhatDryRunSaysWithoutBeingAskedTwice(t *testing.T) {
	dir := t.TempDir()

	out, errs := &bytes.Buffer{}, &bytes.Buffer{}
	env := &environment{stdout: out, stderr: errs, pipeline: over(generating(t, dir, "Persons"))}

	cmd, _ := lookup("generate")
	if err := cmd.run(env, cmd, []string{"--dry-run", "./..."}); err != nil {
		t.Fatalf("generating: %v", err)
	}

	// Without -v, which is the ordinary way somebody runs it.
	if !strings.Contains(errs.String(), "would write") {
		t.Errorf("a run held back said nothing:\n%s", errs.String())
	}
	if out.String() != "" {
		t.Errorf("it wrote to stdout, where a script reads:\n%s", out.String())
	}
}

// A file forge wrote for a declaration that is gone is what a rename leaves
// behind, and it is very often why the package no longer builds — so it is
// named rather than left to be inferred from a dozen errors about generated
// code, which is the last place an author who has just renamed a type looks.
func TestAFileLeftBehindByARename(t *testing.T) {
	dir := t.TempDir()

	if _, said, err := running(t, generating(t, dir, "Widgets"), "./..."); err != nil {
		t.Fatalf("the first run: %v\n%s", err, said)
	}

	// The same package with the declaration renamed, and no longer building —
	// which is what the file left behind did to it.
	_, said, err := running(t, broken(generating(t, dir, "Gadgets")), "./...")
	if err == nil {
		t.Fatalf("a package that does not build reported success\n%s", said)
	}

	if !strings.Contains(said, "FRG5003") || !strings.Contains(said, "zz_forge_widgets.go") {
		t.Errorf("the report does not name what was left behind:\n%s", said)
	}
	if !strings.Contains(said, "delete it") {
		t.Errorf("the report does not say what to do:\n%s", said)
	}

	// And the files the package still asks for are not named.
	for _, held := range []string{"zz_forge_gadgets.go", "zz_forge_shared.go"} {
		if strings.Contains(said, held+" does not belong") {
			t.Errorf("a file the package still asks for was named:\n%s", said)
		}
	}
}

// A leftover that breaks nothing is not worth stopping a run over. A package
// that builds is a package whose files, whatever else is true of them, are not
// stopping anybody — and a run refused because of one would refuse --dry-run
// and --diff too, which exist to answer a question without touching anything.
func TestALeftoverThatBreaksNothing(t *testing.T) {
	dir := t.TempDir()

	held := filepath.Join(dir, "zz_forge_ancient.go")
	if err := os.WriteFile(held, []byte("// Code generated by forge. DO NOT EDIT.\n\npackage model\n"), 0o600); err != nil {
		t.Fatalf("making the fixture: %v", err)
	}

	_, said, err := running(t, generating(t, dir, "Persons"), "./...")
	if err != nil {
		t.Fatalf("a package that builds was refused: %v\n%s", err, said)
	}
	if strings.Contains(said, "FRG5003") {
		t.Errorf("a leftover that breaks nothing stopped the run:\n%s", said)
	}
}

// A declaration whose subject was refused is still a declaration in the
// package, and the file generated for it is still its file. Naming it would
// tell an author to delete a current file, on top of the refusal they are
// already being told about.
func TestAFileBelongingToARefusedDeclaration(t *testing.T) {
	dir := t.TempDir()

	if _, said, err := running(t, generating(t, dir, "Persons"), "./..."); err != nil {
		t.Fatalf("the first run: %v\n%s", err, said)
	}

	// The same declaration, with no model: the subject was refused, which is
	// reported by the stage that refused it.
	s := broken(generating(t, dir, "Persons"))
	s.modelled[0].Model = nil

	_, said, _ := running(t, s, "./...")

	if strings.Contains(said, "zz_forge_persons.go does not belong") {
		t.Errorf("a refused declaration's own file was reported as belonging to nobody:\n%s", said)
	}
}

// A file that merely looks generated is not, since the name is a convention
// anybody could follow and reporting somebody's own file as abandoned is worse
// than leaving a stale one behind.
func TestAFileThatOnlyLooksGenerated(t *testing.T) {
	dir := t.TempDir()

	held := filepath.Join(dir, "zz_forge_notes.go")
	if err := os.WriteFile(held, []byte("package model\n\n// notes\n"), 0o600); err != nil {
		t.Fatalf("making the fixture: %v", err)
	}

	_, said, _ := running(t, broken(generating(t, dir, "Persons")), "./...")

	if strings.Contains(said, "FRG5003") {
		t.Errorf("a file forge did not write was named:\n%s", said)
	}
}

// A package whose last declaration was removed is the shape this matters most
// in — one collection per package is the common arrangement — and it is the one
// a scan driven by the declarations that were found would never reach, because
// there are none.
func TestAPackageWhoseLastDeclarationWentAway(t *testing.T) {
	dir := t.TempDir()

	if _, said, err := running(t, generating(t, dir, "Items"), "./..."); err != nil {
		t.Fatalf("the first run: %v\n%s", err, said)
	}

	// The same package, with nothing left in it and no longer building.
	s := broken(generating(t, dir, "Items"))
	s.candidates, s.modelled = nil, nil

	_, said, err := running(t, s, "./...")
	if err == nil {
		t.Fatalf("a package that does not build reported success\n%s", said)
	}

	for _, held := range []string{"zz_forge_items.go", "zz_forge_shared.go"} {
		if !strings.Contains(said, held) {
			t.Errorf("%s was left behind and not named:\n%s", held, said)
		}
	}
}
