package main

import (
	"fmt"
	"runtime"
	"runtime/debug"
)

// unknown is what a version reads as when the build did not record one, which
// is what `go run` and a build from a dirty tree both produce.
const unknown = "(devel)"

// build reads the version stamped into this binary, so that a test can say what
// it read.
var build = debug.ReadBuildInfo

// version reports what this binary is and what it was built from.
//
// Three lines, because three versions can disagree and each disagreement means
// something different. forge's own version says which generator wrote a file.
// The marker module's says which declarations it can resolve — markers are what
// a spec file is written against, and a spec naming one this build has never
// heard of is the failure this line explains. The Go version says which
// language the output has to compile under, which is the one of the three that
// changes what is emitted.
func version(env *environment, cmd command, args []string) error {
	flags := flagsFor(cmd)

	rest, on, err := parse(env, cmd, flags, args)
	if !on || err != nil {
		return err
	}

	if len(rest) > 0 {
		return answered(cmd, flags, "version takes no arguments, got %q", rest[0])
	}

	self, markers, toolchain := versions()
	say(env.stdout, "forge %s\nmarkers %s\ngo %s\n", self, markers, toolchain)

	return nil
}

// versions returns what this binary is, what markers it resolves, and what
// built it.
func versions() (self, markers, toolchain string) {
	self, markers, toolchain = unknown, unknown, runtime.Version()

	info, ok := build()
	if !ok {
		// A binary with no build information is one somebody assembled by hand,
		// and saying so is more use than reporting a version invented here.
		return self, markers, toolchain
	}

	if info.Main.Version != "" {
		self = info.Main.Version
	}
	if info.GoVersion != "" {
		toolchain = info.GoVersion
	}

	// The markers ship in this module, so today the two versions are one. They
	// are printed separately because they are two facts: the markers are what a
	// spec file imports, and if they ever move to a module of their own, a spec
	// written against one version and generated by another is exactly the skew
	// this line is here to show.
	markers = fmt.Sprintf("%s %s", markerPath(info), self)

	return self, markers, toolchain
}

// markerPath returns the import path a spec file names to reach the markers.
func markerPath(info *debug.BuildInfo) string {
	if info.Main.Path != "" {
		return info.Main.Path
	}
	return unknown
}
