// Code generated by forge. DO NOT EDIT.

package model

import (
	"iter"
	"slices"
)

// Persons holds elements in the order they were appended.
//
// The underlying type is a real slice, so everything the language does to one
// can be done to this: index it, range over it, take a part of it, pass it
// where a slice is wanted. The methods add to that rather than stand in for it.
//
// Reading a container does not need a pointer to one, so those methods take it
// by value: a value of this type satisfies an interface asking for them, and a
// container returned by a function can be read without being stored in a
// variable first. Only the method that changes the container takes a pointer,
// because appending may move it.
type Persons []Person

// NewPersons returns a container holding the given elements, in order.
//
// The elements are copied, so the container does not follow the slice they were
// passed in.
func NewPersons(elems ...Person) Persons { return slices.Clone(elems) }

// Len reports how many elements the container holds.
func (s Persons) Len() int { return len(s) }

// All walks the container from the first element to the last.
//
// The walk is fixed when All is called, so appending during one does not extend
// it.
func (s Persons) All() iter.Seq[Person] { return slices.Values(s) }

// Backward walks the container from the last element to the first. Like All,
// the walk is fixed when it is called.
func (s Persons) Backward() iter.Seq[Person] {
	return func(yield func(Person) bool) {
		for _, elem := range slices.Backward(s) {
			if !yield(elem) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, in the order it yields
// them.
//
// It appends rather than replaces, so several sequences can be gathered into
// one container by calling it more than once.
func (s *Persons) AppendSeq(seq iter.Seq[Person]) { *s = slices.AppendSeq(*s, seq) }
