// Code generated by forge. DO NOT EDIT.

package model

import (
	"errors"
	"iter"
)

// personsFixedCap is how many elements the buffer holds.
//
// It is a constant rather than a field, so the size is part of the type rather
// than of a value: every container of this type holds the same number, the
// compiler knows it, and no caller can be handed one sized differently from the
// one it expected.
const personsFixedCap = 64

// ErrPersonsFull is returned by a push that would have overwritten an element that is
// still there.
//
// One value rather than one per call, so that a caller can compare against it
// with errors.Is and act on the answer, which is the whole reason for refusing
// rather than overwriting.
var ErrPersonsFull = errors.New("the buffer is full")

// Persons holds a fixed number of the most recent elements.
//
// The buffer is allocated once and never grows, so a producer that outruns its
// consumer costs a bounded amount of memory rather than an increasing one. That
// is the whole of what this type is for, and it is why every method that adds
// an element has an answer for a buffer that is already full.
//
// The elements live in a slice that is treated as a circle: head is where the
// oldest one is, and n is how many there are. Reading walks from head, wrapping
// at the end, so the order elements come back in is the order they went in
// — the oldest first — regardless of where in the slice they happen to sit.
//
// The zero value has no buffer at all, which is not the same as an empty
// container and is not something any method can make sense of. Adding to one
// says so rather than carrying on. Use the constructor.
type Persons struct {
	buf  []Person
	head int
	n    int
}

// NewPersons returns an empty container, whose capacity is the one the
// declaration fixed.
func NewPersons() *Persons {
	return &Persons{buf: make([]Person, personsFixedCap)}
}

// Cap reports how many elements the container can hold, which does not change.
func (r *Persons) Cap() int { return len(r.buf) }

// Len reports how many elements the container holds, which is never more than
// its capacity.
func (r *Persons) Len() int { return r.n }

// Push adds an element, and reports that it did not when the buffer is
// full.
//
// The element already in the buffer stays. A caller that would rather lose the
// oldest than the newest wants the other policy, which is chosen where the
// container is declared rather than where it is pushed to.
func (r *Persons) Push(v Person) error {
	r.built()

	if r.n == len(r.buf) {
		return ErrPersonsFull
	}

	r.buf[personsIndexOf(r.head, r.n, len(r.buf))] = v
	r.n++

	return nil
}

// All walks the container from the oldest element to the newest.
//
// Which slots the walk covers is fixed when All is called, so pushing during
// one neither lengthens it nor makes it come back round to a slot it has been
// to. What is in a slot is read when the walk reaches it: pushing to a full
// container overwrites the oldest slot, and a walk that has not yet reached
// that slot yields what was written there rather than what it displaced.
//
// Fixing that too would mean copying the elements, which is the one thing a
// container that exists to bound its memory should not do behind a caller's
// back. Walk it, or push to it, or take a copy and do both.
func (r *Persons) All() iter.Seq[Person] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Person) bool) {
		for i := range held {
			if !yield(r.buf[personsIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// Backward walks the container from the newest element to the oldest. Like All,
// which slots it covers is fixed when it is called.
func (r *Persons) Backward() iter.Seq[Person] {
	held, from, size := r.n, r.head, len(r.buf)

	return func(yield func(Person) bool) {
		for i := held - 1; i >= 0; i-- {
			if !yield(r.buf[personsIndexOf(from, i, size)]) {
				return
			}
		}
	}
}

// AppendSeq adds every element the sequence yields, and stops at the
// first one that does not fit.
//
// What was added stays. The sequence is not read past the element that was
// refused, so a caller holding one that is expensive to produce does not pay to
// produce the rest of it.
func (r *Persons) AppendSeq(seq iter.Seq[Person]) error {
	for v := range seq {
		if err := r.Push(v); err != nil {
			return err
		}
	}
	return nil
}

// Reset empties the container, keeping the buffer it was constructed with.
//
// The capacity is what the container is rather than what it holds, so emptying
// does not give it up: a container that has been reset takes as many elements
// as it did when it was new, and takes them without allocating again.
//
// The elements that were there stay in the buffer until they are pushed over,
// so a container holding the last reference to something large holds it until
// then. Nothing can read them: what a walk covers is the count, and the count
// is what this sets to none.
func (r *Persons) Reset() { r.head, r.n = 0, 0 }

// built stops a container that was never constructed from being added to.
//
// A zero value has no buffer, so it can hold nothing and never will. Under the
// policy that overwrites, adding to one indexes an empty slice and panics on
// its own; under the policy that refuses, it would report the container full —
// which is true and useless, since a caller checking for a full container reads
// that as back-pressure and retries for ever. Saying the same thing both ways
// makes the mistake one answer rather than two.
func (r *Persons) built() {
	if len(r.buf) == 0 {
		panic("forge: this container was never constructed; use the constructor")
	}
}

// personsIndexOf returns where the element i places after the one at from is kept.
//
// Given the buffer's own head and size it answers for the container as it is;
// given a head a walk took when it started, it answers for the container as it
// was, which is what keeps a walk on the positions it set out to visit.
//
// One subtraction rather than a remainder: i is never more than the number of
// elements held, which is never more than the size, so the sum passes the end
// of the buffer at most once.
func personsIndexOf(from, i, size int) int {
	if slot := from + i; slot < size {
		return slot
	}
	return from + i - size
}
