// Code generated by forge. DO NOT EDIT.
//
// forge v1.2.3
// markers v1.2.3
// inputs 0000000000000000

package model

import "declsfixture/markers"

// Seq is the shape forge's own shared view has: a defined type over an
// instantiation, which is exactly what a candidate is recognised by.
//
// It is here so that a run that read its own output back would be caught doing
// it. Everything else in this fixture is somebody's source; this is the one
// file that is not.
type Seq markers.Collection[Person]
